// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: altAnswers.sql

package db

import (
	"context"
)

const countAltAnswerByAltQuestionID = `-- name: CountAltAnswerByAltQuestionID :one
SELECT COUNT(id)
FROM alt_answers
WHERE alt_question_id = ?1 AND user_id = ?2
`

type CountAltAnswerByAltQuestionIDParams struct {
	AltQuestionID int64
	UserID        int64
}

func (q *Queries) CountAltAnswerByAltQuestionID(ctx context.Context, arg CountAltAnswerByAltQuestionIDParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAltAnswerByAltQuestionID, arg.AltQuestionID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAltAnswer = `-- name: CreateAltAnswer :exec
INSERT INTO
    alt_answers (alt_question_id, state, content, user_id)
VALUES
    (?1, ?2, ?3, ?4)
`

type CreateAltAnswerParams struct {
	AltQuestionID int64
	State         int64
	Content       string
	UserID        int64
}

func (q *Queries) CreateAltAnswer(ctx context.Context, arg CreateAltAnswerParams) error {
	_, err := q.db.ExecContext(ctx, createAltAnswer,
		arg.AltQuestionID,
		arg.State,
		arg.Content,
		arg.UserID,
	)
	return err
}

const deleteAltAnswer = `-- name: DeleteAltAnswer :exec
DELETE FROM
    alt_answers
WHERE
    id = ?1
    AND user_id = ?2
`

type DeleteAltAnswerParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteAltAnswer(ctx context.Context, arg DeleteAltAnswerParams) error {
	_, err := q.db.ExecContext(ctx, deleteAltAnswer, arg.ID, arg.UserID)
	return err
}

const getAllAltAnswersByAltQuestionID = `-- name: GetAllAltAnswersByAltQuestionID :many
SELECT
    id, alt_question_id, state, content, user_id
FROM
    alt_answers
WHERE
    alt_question_id = ?1
    AND user_id = ?2
`

type GetAllAltAnswersByAltQuestionIDParams struct {
	AltQuestionID int64
	UserID        int64
}

func (q *Queries) GetAllAltAnswersByAltQuestionID(ctx context.Context, arg GetAllAltAnswersByAltQuestionIDParams) ([]AltAnswer, error) {
	rows, err := q.db.QueryContext(ctx, getAllAltAnswersByAltQuestionID, arg.AltQuestionID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AltAnswer
	for rows.Next() {
		var i AltAnswer
		if err := rows.Scan(
			&i.ID,
			&i.AltQuestionID,
			&i.State,
			&i.Content,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAltAnswerByID = `-- name: GetAltAnswerByID :one
SELECT
    id, alt_question_id, state, content, user_id
FROM
    alt_answers
WHERE
    id = ?1
    AND user_id = ?2
`

type GetAltAnswerByIDParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetAltAnswerByID(ctx context.Context, arg GetAltAnswerByIDParams) (AltAnswer, error) {
	row := q.db.QueryRowContext(ctx, getAltAnswerByID, arg.ID, arg.UserID)
	var i AltAnswer
	err := row.Scan(
		&i.ID,
		&i.AltQuestionID,
		&i.State,
		&i.Content,
		&i.UserID,
	)
	return i, err
}

const updateAltAnswer = `-- name: UpdateAltAnswer :exec
UPDATE
    alt_answers
SET
    state = ?1,
    content = ?2
WHERE
    id = ?3
    AND user_id = ?4
`

type UpdateAltAnswerParams struct {
	State   int64
	Content string
	ID      int64
	UserID  int64
}

func (q *Queries) UpdateAltAnswer(ctx context.Context, arg UpdateAltAnswerParams) error {
	_, err := q.db.ExecContext(ctx, updateAltAnswer,
		arg.State,
		arg.Content,
		arg.ID,
		arg.UserID,
	)
	return err
}
