// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: altImages.sql

package db

import (
	"context"
)

const createAltImage = `-- name: CreateAltImage :execrows
INSERT INTO
    alt_images (
        alt_question_id,
        image_name,
        resize_percentage,
        user_id
    )
SELECT ?1, ?2, ?3, ?4
WHERE EXISTS (SELECT 1 FROM alt_questions a
              WHERE a.id = ?1 AND a.question_id = ?5 AND a.user_id = ?4)
`

type CreateAltImageParams struct {
	AltQuestionID    int64
	ImageName        string
	ResizePercentage int64
	UserID           int64
	QuestionID       int64
}

func (q *Queries) CreateAltImage(ctx context.Context, arg CreateAltImageParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createAltImage,
		arg.AltQuestionID,
		arg.ImageName,
		arg.ResizePercentage,
		arg.UserID,
		arg.QuestionID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteAltImage = `-- name: DeleteAltImage :execrows
DELETE FROM
    alt_images
WHERE
    alt_images.alt_question_id = ?1
    AND alt_images.user_id = ?2
    AND EXISTS (SELECT 1 FROM alt_questions a
                WHERE a.id = alt_images.alt_question_id AND a.question_id = ?3 AND a.user_id = ?2)
`

type DeleteAltImageParams struct {
	AltQuestionID int64
	UserID        int64
	QuestionID    int64
}

func (q *Queries) DeleteAltImage(ctx context.Context, arg DeleteAltImageParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAltImage, arg.AltQuestionID, arg.UserID, arg.QuestionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAltImageByAltQuestionID = `-- name: GetAltImageByAltQuestionID :one
SELECT
    id, alt_question_id, image_name, resize_percentage, user_id
FROM
    alt_images
WHERE
    alt_images.alt_question_id = ?1
    AND alt_images.user_id = ?2
    AND EXISTS (SELECT 1 FROM alt_questions a
                WHERE a.id = alt_images.alt_question_id AND a.question_id = ?3 AND a.user_id = ?2)
`

type GetAltImageByAltQuestionIDParams struct {
	AltQuestionID int64
	UserID        int64
	QuestionID    int64
}

func (q *Queries) GetAltImageByAltQuestionID(ctx context.Context, arg GetAltImageByAltQuestionIDParams) (AltImage, error) {
	row := q.db.QueryRowContext(ctx, getAltImageByAltQuestionID, arg.AltQuestionID, arg.UserID, arg.QuestionID)
	var i AltImage
	err := row.Scan(
		&i.ID,
		&i.AltQuestionID,
		&i.ImageName,
		&i.ResizePercentage,
		&i.UserID,
	)
	return i, err
}

const listAllAltImageNames = `-- name: ListAllAltImageNames :many
SELECT image_name
FROM alt_images
ORDER BY image_name
`

func (q *Queries) ListAllAltImageNames(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listAllAltImageNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var image_name string
		if err := rows.Scan(&image_name); err != nil {
			return nil, err
		}
		items = append(items, image_name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSizeAltImage = `-- name: UpdateSizeAltImage :execrows
UPDATE
    alt_images
SET
    resize_percentage = ?1
WHERE
    alt_images.alt_question_id = ?2
    AND alt_images.user_id = ?3
    AND EXISTS (SELECT 1 FROM alt_questions a
                WHERE a.id = alt_images.alt_question_id AND a.question_id = ?4 AND a.user_id = ?3)
`

type UpdateSizeAltImageParams struct {
	ResizePercentage int64
	AltQuestionID    int64
	UserID           int64
	QuestionID       int64
}

func (q *Queries) UpdateSizeAltImage(ctx context.Context, arg UpdateSizeAltImageParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateSizeAltImage,
		arg.ResizePercentage,
		arg.AltQuestionID,
		arg.UserID,
		arg.QuestionID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
