// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: altImages.sql

package db

import (
	"context"
)

const createAltImage = `-- name: CreateAltImage :exec
INSERT INTO
    alt_images (
        alt_question_id,
        image_name,
        resize_percentage,
        user_id
    )
VALUES
    (
        ?1,
        ?2,
        ?3,
        ?4
    )
`

type CreateAltImageParams struct {
	AltQuestionID    int64
	ImageName        string
	ResizePercentage int64
	UserID           int64
}

func (q *Queries) CreateAltImage(ctx context.Context, arg CreateAltImageParams) error {
	_, err := q.db.ExecContext(ctx, createAltImage,
		arg.AltQuestionID,
		arg.ImageName,
		arg.ResizePercentage,
		arg.UserID,
	)
	return err
}

const deleteAltImage = `-- name: DeleteAltImage :execrows
DELETE FROM
    alt_images
WHERE
    alt_question_id = ?1
    AND user_id = ?2
`

type DeleteAltImageParams struct {
	AltQuestionID int64
	UserID        int64
}

func (q *Queries) DeleteAltImage(ctx context.Context, arg DeleteAltImageParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAltImage, arg.AltQuestionID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAltImageByAltQuestionID = `-- name: GetAltImageByAltQuestionID :one
SELECT
    id, alt_question_id, image_name, resize_percentage, user_id
FROM
    alt_images
WHERE
    alt_question_id = ?1
    AND user_id = ?2
`

type GetAltImageByAltQuestionIDParams struct {
	AltQuestionID int64
	UserID        int64
}

func (q *Queries) GetAltImageByAltQuestionID(ctx context.Context, arg GetAltImageByAltQuestionIDParams) (AltImage, error) {
	row := q.db.QueryRowContext(ctx, getAltImageByAltQuestionID, arg.AltQuestionID, arg.UserID)
	var i AltImage
	err := row.Scan(
		&i.ID,
		&i.AltQuestionID,
		&i.ImageName,
		&i.ResizePercentage,
		&i.UserID,
	)
	return i, err
}

const updateSizeAltImage = `-- name: UpdateSizeAltImage :exec
UPDATE
    alt_images
SET
    resize_percentage = ?1
WHERE
    alt_question_id = ?2
    AND user_id = ?3
`

type UpdateSizeAltImageParams struct {
	ResizePercentage int64
	AltQuestionID    int64
	UserID           int64
}

func (q *Queries) UpdateSizeAltImage(ctx context.Context, arg UpdateSizeAltImageParams) error {
	_, err := q.db.ExecContext(ctx, updateSizeAltImage, arg.ResizePercentage, arg.AltQuestionID, arg.UserID)
	return err
}
