// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: altQuestions.sql

package db

import (
	"context"
)

const createAltQuestion = `-- name: CreateAltQuestion :execrows
INSERT INTO
    alt_questions (
        question_id,
        content,
        user_id
    )
SELECT ?1, ?2, ?3
WHERE EXISTS (SELECT 1 FROM questions q WHERE q.id = ?1 AND q.user_id = ?3)
`

type CreateAltQuestionParams struct {
	QuestionID int64
	Content    string
	UserID     int64
}

func (q *Queries) CreateAltQuestion(ctx context.Context, arg CreateAltQuestionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createAltQuestion, arg.QuestionID, arg.Content, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteAltQuestion = `-- name: DeleteAltQuestion :execrows
DELETE FROM
    alt_questions
WHERE
    alt_questions.id = ?1
    AND alt_questions.question_id = ?2
    AND alt_questions.user_id = ?3
    AND EXISTS (SELECT 1 FROM questions q WHERE q.id = alt_questions.question_id AND q.user_id = ?3)
`

type DeleteAltQuestionParams struct {
	ID         int64
	QuestionID int64
	UserID     int64
}

func (q *Queries) DeleteAltQuestion(ctx context.Context, arg DeleteAltQuestionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAltQuestion, arg.ID, arg.QuestionID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAllAltQuestions = `-- name: GetAllAltQuestions :many
SELECT
    id, question_id, content, user_id
FROM
    alt_questions
WHERE
    alt_questions.question_id = ?1
    AND alt_questions.user_id = ?2
    AND EXISTS (SELECT 1 FROM questions q WHERE q.id = alt_questions.question_id AND q.user_id = ?2)
`

type GetAllAltQuestionsParams struct {
	QuestionID int64
	UserID     int64
}

func (q *Queries) GetAllAltQuestions(ctx context.Context, arg GetAllAltQuestionsParams) ([]AltQuestion, error) {
	rows, err := q.db.QueryContext(ctx, getAllAltQuestions, arg.QuestionID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AltQuestion
	for rows.Next() {
		var i AltQuestion
		if err := rows.Scan(
			&i.ID,
			&i.QuestionID,
			&i.Content,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllOwnedAltQuestions = `-- name: GetAllOwnedAltQuestions :many
SELECT
    alt_questions.id, alt_questions.question_id, alt_questions.content, alt_questions.user_id
FROM
    alt_questions
WHERE
    alt_questions.user_id = ?1
    AND EXISTS (
        SELECT 1
        FROM questions q
        WHERE q.id = alt_questions.question_id
          AND q.user_id = ?1
    )
ORDER BY
    alt_questions.question_id,
    alt_questions.id
`

func (q *Queries) GetAllOwnedAltQuestions(ctx context.Context, userID int64) ([]AltQuestion, error) {
	rows, err := q.db.QueryContext(ctx, getAllOwnedAltQuestions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AltQuestion
	for rows.Next() {
		var i AltQuestion
		if err := rows.Scan(
			&i.ID,
			&i.QuestionID,
			&i.Content,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAltQuestionByID = `-- name: GetAltQuestionByID :one
SELECT
    id, question_id, content, user_id
FROM
    alt_questions
WHERE
    alt_questions.id = ?1
    AND alt_questions.user_id = ?2
    AND EXISTS (SELECT 1 FROM questions q WHERE q.id = alt_questions.question_id AND q.user_id = ?2)
`

type GetAltQuestionByIDParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetAltQuestionByID(ctx context.Context, arg GetAltQuestionByIDParams) (AltQuestion, error) {
	row := q.db.QueryRowContext(ctx, getAltQuestionByID, arg.ID, arg.UserID)
	var i AltQuestion
	err := row.Scan(
		&i.ID,
		&i.QuestionID,
		&i.Content,
		&i.UserID,
	)
	return i, err
}

const getAltQuestionByParentID = `-- name: GetAltQuestionByParentID :one
SELECT id, question_id, content, user_id FROM alt_questions
WHERE alt_questions.id = ?1
  AND alt_questions.question_id = ?2
  AND alt_questions.user_id = ?3
  AND EXISTS (SELECT 1 FROM questions q WHERE q.id = alt_questions.question_id AND q.user_id = ?3)
`

type GetAltQuestionByParentIDParams struct {
	ID         int64
	QuestionID int64
	UserID     int64
}

func (q *Queries) GetAltQuestionByParentID(ctx context.Context, arg GetAltQuestionByParentIDParams) (AltQuestion, error) {
	row := q.db.QueryRowContext(ctx, getAltQuestionByParentID, arg.ID, arg.QuestionID, arg.UserID)
	var i AltQuestion
	err := row.Scan(
		&i.ID,
		&i.QuestionID,
		&i.Content,
		&i.UserID,
	)
	return i, err
}

const updateAltQuestion = `-- name: UpdateAltQuestion :execrows
UPDATE
    alt_questions
SET
    content = ?1
WHERE
    alt_questions.id = ?2
    AND alt_questions.question_id = ?3
    AND alt_questions.user_id = ?4
    AND EXISTS (SELECT 1 FROM questions q WHERE q.id = alt_questions.question_id AND q.user_id = ?4)
`

type UpdateAltQuestionParams struct {
	Content    string
	ID         int64
	QuestionID int64
	UserID     int64
}

func (q *Queries) UpdateAltQuestion(ctx context.Context, arg UpdateAltQuestionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateAltQuestion,
		arg.Content,
		arg.ID,
		arg.QuestionID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
