// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: altQuestions.sql

package db

import (
	"context"
)

const createAltQuestion = `-- name: CreateAltQuestion :exec
INSERT INTO
    alt_questions (
        question_id,
        content,
        user_id
    )
VALUES
    (
        ?1,
        ?2,
        ?3
    )
`

type CreateAltQuestionParams struct {
	QuestionID int64
	Content    string
	UserID     int64
}

func (q *Queries) CreateAltQuestion(ctx context.Context, arg CreateAltQuestionParams) error {
	_, err := q.db.ExecContext(ctx, createAltQuestion, arg.QuestionID, arg.Content, arg.UserID)
	return err
}

const deleteAltQuestion = `-- name: DeleteAltQuestion :exec
DELETE FROM
    alt_questions
WHERE
    id = ?1
    AND user_id = ?2
`

type DeleteAltQuestionParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteAltQuestion(ctx context.Context, arg DeleteAltQuestionParams) error {
	_, err := q.db.ExecContext(ctx, deleteAltQuestion, arg.ID, arg.UserID)
	return err
}

const getAllAltQuestions = `-- name: GetAllAltQuestions :many
SELECT
    id, question_id, content, user_id
FROM
    alt_questions
WHERE
    question_id = ?1
    AND user_id = ?2
`

type GetAllAltQuestionsParams struct {
	QuestionID int64
	UserID     int64
}

func (q *Queries) GetAllAltQuestions(ctx context.Context, arg GetAllAltQuestionsParams) ([]AltQuestion, error) {
	rows, err := q.db.QueryContext(ctx, getAllAltQuestions, arg.QuestionID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AltQuestion
	for rows.Next() {
		var i AltQuestion
		if err := rows.Scan(
			&i.ID,
			&i.QuestionID,
			&i.Content,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAltQuestionByID = `-- name: GetAltQuestionByID :one
SELECT
    id, question_id, content, user_id
FROM
    alt_questions
WHERE
    id = ?1
    AND user_id = ?2
`

type GetAltQuestionByIDParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetAltQuestionByID(ctx context.Context, arg GetAltQuestionByIDParams) (AltQuestion, error) {
	row := q.db.QueryRowContext(ctx, getAltQuestionByID, arg.ID, arg.UserID)
	var i AltQuestion
	err := row.Scan(
		&i.ID,
		&i.QuestionID,
		&i.Content,
		&i.UserID,
	)
	return i, err
}

const updateAltQuestion = `-- name: UpdateAltQuestion :exec
UPDATE
    alt_questions
SET
    content = ?1
WHERE
    id = ?2
    AND user_id = ?3
`

type UpdateAltQuestionParams struct {
	Content string
	ID      int64
	UserID  int64
}

func (q *Queries) UpdateAltQuestion(ctx context.Context, arg UpdateAltQuestionParams) error {
	_, err := q.db.ExecContext(ctx, updateAltQuestion, arg.Content, arg.ID, arg.UserID)
	return err
}
