// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: answers.sql

package db

import (
	"context"
)

const countAnswerByQuestionID = `-- name: CountAnswerByQuestionID :one
SELECT COUNT(id)
FROM answers
WHERE answers.question_id = ?1 AND answers.user_id = ?2
  AND EXISTS (SELECT 1 FROM questions q WHERE q.id = answers.question_id AND q.user_id = ?2)
`

type CountAnswerByQuestionIDParams struct {
	QuestionID int64
	UserID     int64
}

func (q *Queries) CountAnswerByQuestionID(ctx context.Context, arg CountAnswerByQuestionIDParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAnswerByQuestionID, arg.QuestionID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAnswer = `-- name: CreateAnswer :execrows
INSERT INTO
    answers (question_id, state, content, user_id)
SELECT ?1, ?2, ?3, ?4
WHERE EXISTS (SELECT 1 FROM questions q WHERE q.id = ?1 AND q.user_id = ?4)
`

type CreateAnswerParams struct {
	QuestionID int64
	State      int64
	Content    string
	UserID     int64
}

func (q *Queries) CreateAnswer(ctx context.Context, arg CreateAnswerParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createAnswer,
		arg.QuestionID,
		arg.State,
		arg.Content,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteAnswer = `-- name: DeleteAnswer :execrows
DELETE FROM
    answers
WHERE
    answers.id = ?1
    AND answers.question_id = ?2
    AND answers.user_id = ?3
    AND EXISTS (SELECT 1 FROM questions q WHERE q.id = answers.question_id AND q.user_id = ?3)
`

type DeleteAnswerParams struct {
	ID         int64
	QuestionID int64
	UserID     int64
}

func (q *Queries) DeleteAnswer(ctx context.Context, arg DeleteAnswerParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteAnswer, arg.ID, arg.QuestionID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAllAnswersByQuestionID = `-- name: GetAllAnswersByQuestionID :many
SELECT
    id, question_id, state, content, user_id
FROM
    answers
WHERE
    answers.question_id = ?1
    AND answers.user_id = ?2
    AND EXISTS (SELECT 1 FROM questions q WHERE q.id = answers.question_id AND q.user_id = ?2)
`

type GetAllAnswersByQuestionIDParams struct {
	QuestionID int64
	UserID     int64
}

func (q *Queries) GetAllAnswersByQuestionID(ctx context.Context, arg GetAllAnswersByQuestionIDParams) ([]Answer, error) {
	rows, err := q.db.QueryContext(ctx, getAllAnswersByQuestionID, arg.QuestionID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Answer
	for rows.Next() {
		var i Answer
		if err := rows.Scan(
			&i.ID,
			&i.QuestionID,
			&i.State,
			&i.Content,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAnswerByID = `-- name: GetAnswerByID :one
SELECT
    id, question_id, state, content, user_id
FROM
    answers
WHERE
    answers.id = ?1
    AND answers.question_id = ?2
    AND answers.user_id = ?3
    AND EXISTS (SELECT 1 FROM questions q WHERE q.id = answers.question_id AND q.user_id = ?3)
`

type GetAnswerByIDParams struct {
	ID         int64
	QuestionID int64
	UserID     int64
}

func (q *Queries) GetAnswerByID(ctx context.Context, arg GetAnswerByIDParams) (Answer, error) {
	row := q.db.QueryRowContext(ctx, getAnswerByID, arg.ID, arg.QuestionID, arg.UserID)
	var i Answer
	err := row.Scan(
		&i.ID,
		&i.QuestionID,
		&i.State,
		&i.Content,
		&i.UserID,
	)
	return i, err
}

const updateAnswer = `-- name: UpdateAnswer :execrows
UPDATE
    answers
SET
    state = ?1,
    content = ?2
WHERE
    answers.id = ?3
    AND answers.question_id = ?4
    AND answers.user_id = ?5
    AND EXISTS (SELECT 1 FROM questions q WHERE q.id = answers.question_id AND q.user_id = ?5)
`

type UpdateAnswerParams struct {
	State      int64
	Content    string
	ID         int64
	QuestionID int64
	UserID     int64
}

func (q *Queries) UpdateAnswer(ctx context.Context, arg UpdateAnswerParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateAnswer,
		arg.State,
		arg.Content,
		arg.ID,
		arg.QuestionID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
