// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: answers.sql

package db

import (
	"context"
)

const countAnswerByQuestionID = `-- name: CountAnswerByQuestionID :one
SELECT COUNT(id)
FROM answers
WHERE question_id = ?1 AND user_id = ?2
`

type CountAnswerByQuestionIDParams struct {
	QuestionID int64
	UserID     int64
}

func (q *Queries) CountAnswerByQuestionID(ctx context.Context, arg CountAnswerByQuestionIDParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAnswerByQuestionID, arg.QuestionID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAnswer = `-- name: CreateAnswer :exec
INSERT INTO
    answers (question_id, state, content, user_id)
VALUES
    (?1, ?2, ?3, ?4)
`

type CreateAnswerParams struct {
	QuestionID int64
	State      int64
	Content    string
	UserID     int64
}

func (q *Queries) CreateAnswer(ctx context.Context, arg CreateAnswerParams) error {
	_, err := q.db.ExecContext(ctx, createAnswer,
		arg.QuestionID,
		arg.State,
		arg.Content,
		arg.UserID,
	)
	return err
}

const deleteAnswer = `-- name: DeleteAnswer :exec
DELETE FROM
    answers
WHERE
    id = ?1
    AND user_id = ?2
`

type DeleteAnswerParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteAnswer(ctx context.Context, arg DeleteAnswerParams) error {
	_, err := q.db.ExecContext(ctx, deleteAnswer, arg.ID, arg.UserID)
	return err
}

const getAllAnswersByQuestionID = `-- name: GetAllAnswersByQuestionID :many
SELECT
    id, question_id, state, content, user_id
FROM
    answers
WHERE
    question_id = ?1
    AND user_id = ?2
`

type GetAllAnswersByQuestionIDParams struct {
	QuestionID int64
	UserID     int64
}

func (q *Queries) GetAllAnswersByQuestionID(ctx context.Context, arg GetAllAnswersByQuestionIDParams) ([]Answer, error) {
	rows, err := q.db.QueryContext(ctx, getAllAnswersByQuestionID, arg.QuestionID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Answer
	for rows.Next() {
		var i Answer
		if err := rows.Scan(
			&i.ID,
			&i.QuestionID,
			&i.State,
			&i.Content,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAnswerByID = `-- name: GetAnswerByID :one
SELECT
    id, question_id, state, content, user_id
FROM
    answers
WHERE
    id = ?1
    AND user_id = ?2
`

type GetAnswerByIDParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetAnswerByID(ctx context.Context, arg GetAnswerByIDParams) (Answer, error) {
	row := q.db.QueryRowContext(ctx, getAnswerByID, arg.ID, arg.UserID)
	var i Answer
	err := row.Scan(
		&i.ID,
		&i.QuestionID,
		&i.State,
		&i.Content,
		&i.UserID,
	)
	return i, err
}

const updateAnswer = `-- name: UpdateAnswer :exec
UPDATE
    answers
SET
    state = ?1,
    content = ?2
WHERE
    id = ?3
    AND user_id = ?4
`

type UpdateAnswerParams struct {
	State   int64
	Content string
	ID      int64
	UserID  int64
}

func (q *Queries) UpdateAnswer(ctx context.Context, arg UpdateAnswerParams) error {
	_, err := q.db.ExecContext(ctx, updateAnswer,
		arg.State,
		arg.Content,
		arg.ID,
		arg.UserID,
	)
	return err
}
