// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: classcodes.sql

package db

import (
	"context"
)

const createClassCode = `-- name: CreateClassCode :exec
INSERT INTO
    class_codes (name, user_id)
VALUES
    (?1, ?2)
`

type CreateClassCodeParams struct {
	Name   string
	UserID int64
}

func (q *Queries) CreateClassCode(ctx context.Context, arg CreateClassCodeParams) error {
	_, err := q.db.ExecContext(ctx, createClassCode, arg.Name, arg.UserID)
	return err
}

const deleteClassCode = `-- name: DeleteClassCode :exec
DELETE FROM
    class_codes
WHERE
    id = ?1
    AND user_id = ?2
`

type DeleteClassCodeParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteClassCode(ctx context.Context, arg DeleteClassCodeParams) error {
	_, err := q.db.ExecContext(ctx, deleteClassCode, arg.ID, arg.UserID)
	return err
}

const getAllClassCodes = `-- name: GetAllClassCodes :many
SELECT
    id, name, user_id
FROM
    class_codes
WHERE
    user_id = ?1
ORDER BY
    name
`

func (q *Queries) GetAllClassCodes(ctx context.Context, userID int64) ([]ClassCode, error) {
	rows, err := q.db.QueryContext(ctx, getAllClassCodes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClassCode
	for rows.Next() {
		var i ClassCode
		if err := rows.Scan(&i.ID, &i.Name, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getClassCodeNameByID = `-- name: GetClassCodeNameByID :one
SELECT
    name
FROM
    class_codes
WHERE
    id = ?1
    AND user_id = ?2
`

type GetClassCodeNameByIDParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetClassCodeNameByID(ctx context.Context, arg GetClassCodeNameByIDParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getClassCodeNameByID, arg.ID, arg.UserID)
	var name string
	err := row.Scan(&name)
	return name, err
}

const listClassCodesByUser = `-- name: ListClassCodesByUser :many
SELECT
    id,
    name
FROM class_codes
WHERE user_id = ?1
ORDER BY name
`

type ListClassCodesByUserRow struct {
	ID   int64
	Name string
}

func (q *Queries) ListClassCodesByUser(ctx context.Context, userID int64) ([]ListClassCodesByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listClassCodesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClassCodesByUserRow
	for rows.Next() {
		var i ListClassCodesByUserRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClassCode = `-- name: UpdateClassCode :exec
UPDATE
    class_codes
SET
    name = ?1
WHERE
    id = ?2
    AND user_id = ?3
`

type UpdateClassCodeParams struct {
	Name   string
	ID     int64
	UserID int64
}

func (q *Queries) UpdateClassCode(ctx context.Context, arg UpdateClassCodeParams) error {
	_, err := q.db.ExecContext(ctx, updateClassCode, arg.Name, arg.ID, arg.UserID)
	return err
}
