// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: difficulties.sql

package db

import (
	"context"
)

const createDifficulty = `-- name: CreateDifficulty :exec
INSERT INTO
    difficulties (name, user_id)
VALUES
    (?1, ?2)
`

type CreateDifficultyParams struct {
	Name   string
	UserID int64
}

func (q *Queries) CreateDifficulty(ctx context.Context, arg CreateDifficultyParams) error {
	_, err := q.db.ExecContext(ctx, createDifficulty, arg.Name, arg.UserID)
	return err
}

const deleteDifficulty = `-- name: DeleteDifficulty :exec
DELETE FROM
    difficulties
WHERE
    id = ?1
    AND user_id = ?2
`

type DeleteDifficultyParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteDifficulty(ctx context.Context, arg DeleteDifficultyParams) error {
	_, err := q.db.ExecContext(ctx, deleteDifficulty, arg.ID, arg.UserID)
	return err
}

const getAllDifficulties = `-- name: GetAllDifficulties :many
SELECT
    id, name, user_id
FROM
    difficulties
WHERE
    user_id = ?1
ORDER BY
    name
`

func (q *Queries) GetAllDifficulties(ctx context.Context, userID int64) ([]Difficulty, error) {
	rows, err := q.db.QueryContext(ctx, getAllDifficulties, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Difficulty
	for rows.Next() {
		var i Difficulty
		if err := rows.Scan(&i.ID, &i.Name, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDifficulty = `-- name: UpdateDifficulty :exec
UPDATE
    difficulties
SET
    name = ?1
WHERE
    id = ?2
    AND user_id = ?3
`

type UpdateDifficultyParams struct {
	Name   string
	ID     int64
	UserID int64
}

func (q *Queries) UpdateDifficulty(ctx context.Context, arg UpdateDifficultyParams) error {
	_, err := q.db.ExecContext(ctx, updateDifficulty, arg.Name, arg.ID, arg.UserID)
	return err
}
