// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: examsGenerated.sql

package db

import (
	"context"
)

const createExamGenerated = `-- name: CreateExamGenerated :one
INSERT INTO
    exams_generated (exam_id, user_id)
VALUES
    (?1, ?2) RETURNING id
`

type CreateExamGeneratedParams struct {
	ExamID int64
	UserID int64
}

func (q *Queries) CreateExamGenerated(ctx context.Context, arg CreateExamGeneratedParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createExamGenerated, arg.ExamID, arg.UserID)
	var id int64
	err := row.Scan(&id)
	return id, err
}
