// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: examsGenerated.sql

package db

import (
	"context"
)

const completeExamGeneration = `-- name: CompleteExamGeneration :execrows
UPDATE
    exams_generated
SET
    status = 'success'
WHERE
    id = ?1
    AND user_id = ?2
    AND status = 'running'
`

type CompleteExamGenerationParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) CompleteExamGeneration(ctx context.Context, arg CompleteExamGenerationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, completeExamGeneration, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const completeExamGenerationWithReferences = `-- name: CompleteExamGenerationWithReferences :execrows
UPDATE exams_generated
SET status = 'success'
WHERE exams_generated.id = ?1
  AND exams_generated.user_id = ?2
  AND exams_generated.status = 'running'
  AND EXISTS (
      SELECT 1
      FROM student_exam AS se
      JOIN student_exam_page_content AS sep
        ON sep.student_exam_id = se.id
       AND sep.user_id = se.user_id
      WHERE se.exam_generated_id = exams_generated.id
        AND se.user_id = exams_generated.user_id
  )
  AND NOT EXISTS (
      SELECT 1
      FROM student_exam AS se
      JOIN student_exam_page_content AS sep
        ON sep.student_exam_id = se.id
       AND sep.user_id = se.user_id
      WHERE se.exam_generated_id = exams_generated.id
        AND se.user_id = exams_generated.user_id
        AND (
            sep.reference_storage_key IS NULL
            OR sep.reference_width IS NULL
            OR sep.reference_height IS NULL
            OR sep.reference_dpi IS NULL
            OR sep.reference_sha256 IS NULL
        )
  )
  AND NOT EXISTS (
      SELECT 1
      FROM student_exam AS se
      JOIN student_exam_page_content AS sep
        ON sep.student_exam_id = se.id
       AND sep.user_id = se.user_id
      WHERE se.exam_generated_id = exams_generated.id
        AND se.user_id = exams_generated.user_id
      GROUP BY sep.student_exam_id, sep.page, sep.user_id
      HAVING COUNT(*) != 1
  )
`

type CompleteExamGenerationWithReferencesParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) CompleteExamGenerationWithReferences(ctx context.Context, arg CompleteExamGenerationWithReferencesParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, completeExamGenerationWithReferences, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createExamGenerated = `-- name: CreateExamGenerated :one
INSERT INTO
    exams_generated (
        exam_id,
        total_students,
        user_id
    )
VALUES
    (
        ?1,
        ?2,
        ?3
    ) RETURNING id
`

type CreateExamGeneratedParams struct {
	ExamID        int64
	TotalStudents int64
	UserID        int64
}

func (q *Queries) CreateExamGenerated(ctx context.Context, arg CreateExamGeneratedParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createExamGenerated, arg.ExamID, arg.TotalStudents, arg.UserID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteExamGenerated = `-- name: DeleteExamGenerated :execrows
DELETE FROM
    exams_generated
WHERE
    id = ?1
    AND user_id = ?2
`

type DeleteExamGeneratedParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteExamGenerated(ctx context.Context, arg DeleteExamGeneratedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExamGenerated, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteFailedExamGenerated = `-- name: DeleteFailedExamGenerated :execrows
DELETE FROM
    exams_generated
WHERE
    id = ?1
    AND user_id = ?2
    AND status = 'failed'
`

type DeleteFailedExamGeneratedParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteFailedExamGenerated(ctx context.Context, arg DeleteFailedExamGeneratedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteFailedExamGenerated, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteRunningExamGenerated = `-- name: DeleteRunningExamGenerated :execrows
DELETE FROM
    exams_generated
WHERE
    id = ?1
    AND user_id = ?2
    AND status = 'running'
`

type DeleteRunningExamGeneratedParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteRunningExamGenerated(ctx context.Context, arg DeleteRunningExamGeneratedParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteRunningExamGenerated, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const failExamGeneration = `-- name: FailExamGeneration :execrows
UPDATE
    exams_generated
SET
    status = 'failed'
WHERE
    id = ?1
    AND user_id = ?2
    AND status = 'running'
`

type FailExamGenerationParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) FailExamGeneration(ctx context.Context, arg FailExamGenerationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, failExamGeneration, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getExamGeneratedProgress = `-- name: GetExamGeneratedProgress :one
SELECT
    processed_students,
    total_students
FROM
    exams_generated
WHERE
    id = ?1
    AND user_id = ?2
`

type GetExamGeneratedProgressParams struct {
	ID     int64
	UserID int64
}

type GetExamGeneratedProgressRow struct {
	ProcessedStudents int64
	TotalStudents     int64
}

func (q *Queries) GetExamGeneratedProgress(ctx context.Context, arg GetExamGeneratedProgressParams) (GetExamGeneratedProgressRow, error) {
	row := q.db.QueryRowContext(ctx, getExamGeneratedProgress, arg.ID, arg.UserID)
	var i GetExamGeneratedProgressRow
	err := row.Scan(&i.ProcessedStudents, &i.TotalStudents)
	return i, err
}

const getExamStatus = `-- name: GetExamStatus :one
SELECT
    status
FROM
    exams_generated
WHERE
    id = ?1
    AND user_id = ?2
`

type GetExamStatusParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetExamStatus(ctx context.Context, arg GetExamStatusParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getExamStatus, arg.ID, arg.UserID)
	var status string
	err := row.Scan(&status)
	return status, err
}

const getExamsGeneratedSuccess = `-- name: GetExamsGeneratedSuccess :many
SELECT
    exams_generated.id AS exam_generated_id,
    exams.name AS exam_name,
    class_codes.name AS class_code_name,
    strftime('%Y-%m-%d %H:%M', exams_generated.created_at) AS created_at
FROM
    exams_generated
    JOIN exams ON exams_generated.exam_id = exams.id
    JOIN class_codes ON exams.class_code_id = class_codes.id
WHERE
    exams_generated.status = 'success'
    AND exams_generated.user_id = ?1
    AND exams.user_id = ?1
    AND class_codes.user_id = ?1
ORDER BY
    exams_generated.created_at DESC
`

type GetExamsGeneratedSuccessRow struct {
	ExamGeneratedID int64
	ExamName        string
	ClassCodeName   string
	CreatedAt       interface{}
}

func (q *Queries) GetExamsGeneratedSuccess(ctx context.Context, userID int64) ([]GetExamsGeneratedSuccessRow, error) {
	rows, err := q.db.QueryContext(ctx, getExamsGeneratedSuccess, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetExamsGeneratedSuccessRow
	for rows.Next() {
		var i GetExamsGeneratedSuccessRow
		if err := rows.Scan(
			&i.ExamGeneratedID,
			&i.ExamName,
			&i.ClassCodeName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFailedExamGenerations = `-- name: ListFailedExamGenerations :many
SELECT
    exams_generated.id,
    exams_generated.user_id,
    users.username
FROM
    exams_generated
    JOIN users ON users.id = exams_generated.user_id
WHERE
    exams_generated.status = 'failed'
ORDER BY
    exams_generated.id
`

type ListFailedExamGenerationsRow struct {
	ID       int64
	UserID   int64
	Username string
}

func (q *Queries) ListFailedExamGenerations(ctx context.Context) ([]ListFailedExamGenerationsRow, error) {
	rows, err := q.db.QueryContext(ctx, listFailedExamGenerations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFailedExamGenerationsRow
	for rows.Next() {
		var i ListFailedExamGenerationsRow
		if err := rows.Scan(&i.ID, &i.UserID, &i.Username); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunningExamGenerations = `-- name: ListRunningExamGenerations :many
SELECT
    exams_generated.id,
    exams_generated.user_id,
    users.username
FROM
    exams_generated
    JOIN users ON users.id = exams_generated.user_id
WHERE
    exams_generated.status = 'running'
ORDER BY
    exams_generated.id
`

type ListRunningExamGenerationsRow struct {
	ID       int64
	UserID   int64
	Username string
}

func (q *Queries) ListRunningExamGenerations(ctx context.Context) ([]ListRunningExamGenerationsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRunningExamGenerations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRunningExamGenerationsRow
	for rows.Next() {
		var i ListRunningExamGenerationsRow
		if err := rows.Scan(&i.ID, &i.UserID, &i.Username); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExamGeneratedProcessedStudent = `-- name: UpdateExamGeneratedProcessedStudent :execrows
UPDATE
    exams_generated
SET
    processed_students = processed_students + 1
WHERE
    id = ?1
    AND user_id = ?2
    AND status = 'running'
    AND processed_students < total_students
`

type UpdateExamGeneratedProcessedStudentParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) UpdateExamGeneratedProcessedStudent(ctx context.Context, arg UpdateExamGeneratedProcessedStudentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateExamGeneratedProcessedStudent, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
