// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exams.sql

package db

import (
	"context"
)

const createExam = `-- name: CreateExam :exec
INSERT INTO
    exams (
        name,
        qcm_id,
        class_code_id,
        period_id,
        year_id,
        user_id
    )
VALUES
    (
        ?1,
        ?2,
        ?3,
        ?4,
        ?5,
        ?6
    )
`

type CreateExamParams struct {
	Name        string
	QcmID       int64
	ClassCodeID int64
	PeriodID    int64
	YearID      int64
	UserID      int64
}

func (q *Queries) CreateExam(ctx context.Context, arg CreateExamParams) error {
	_, err := q.db.ExecContext(ctx, createExam,
		arg.Name,
		arg.QcmID,
		arg.ClassCodeID,
		arg.PeriodID,
		arg.YearID,
		arg.UserID,
	)
	return err
}

const deleteExam = `-- name: DeleteExam :exec
DELETE FROM
    exams
WHERE
    id = ?1
    AND user_id = ?2
`

type DeleteExamParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteExam(ctx context.Context, arg DeleteExamParams) error {
	_, err := q.db.ExecContext(ctx, deleteExam, arg.ID, arg.UserID)
	return err
}

const getExamByID = `-- name: GetExamByID :one
SELECT
    id, name, qcm_id, class_code_id, period_id, year_id, user_id
FROM
    exams
WHERE
    id = ?1
    and user_id = ?2
`

type GetExamByIDParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetExamByID(ctx context.Context, arg GetExamByIDParams) (Exam, error) {
	row := q.db.QueryRowContext(ctx, getExamByID, arg.ID, arg.UserID)
	var i Exam
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.QcmID,
		&i.ClassCodeID,
		&i.PeriodID,
		&i.YearID,
		&i.UserID,
	)
	return i, err
}

const getExamNameAndClassCodeName = `-- name: GetExamNameAndClassCodeName :one
SELECT
    exams.name AS exam_name,
    class_codes.name AS class_name
FROM
    exams
    JOIN class_codes ON exams.class_code_id = class_codes.id
WHERE
    exams.id = ?1
    AND exams.user_id = ?2
`

type GetExamNameAndClassCodeNameParams struct {
	ID     int64
	UserID int64
}

type GetExamNameAndClassCodeNameRow struct {
	ExamName  string
	ClassName string
}

func (q *Queries) GetExamNameAndClassCodeName(ctx context.Context, arg GetExamNameAndClassCodeNameParams) (GetExamNameAndClassCodeNameRow, error) {
	row := q.db.QueryRowContext(ctx, getExamNameAndClassCodeName, arg.ID, arg.UserID)
	var i GetExamNameAndClassCodeNameRow
	err := row.Scan(&i.ExamName, &i.ClassName)
	return i, err
}

const getExamsAllInfos = `-- name: GetExamsAllInfos :many
SELECT
    exams.id,
    exams.name AS exam_name,
    years.name AS year_name,
    periods.name AS period_name,
    qcm.name AS qcm_name,
    class_codes.name AS class_code_name
FROM
    exams
    JOIN years ON years.id = exams.year_id
    JOIN periods ON periods.id = exams.period_id
    JOIN qcm ON qcm.id = exams.qcm_id
    JOIN class_codes ON class_codes.id = exams.class_code_id
WHERE
    exams.user_id = ?1
ORDER BY
    exams.id DESC
`

type GetExamsAllInfosRow struct {
	ID            int64
	ExamName      string
	YearName      string
	PeriodName    string
	QcmName       string
	ClassCodeName string
}

func (q *Queries) GetExamsAllInfos(ctx context.Context, userID int64) ([]GetExamsAllInfosRow, error) {
	rows, err := q.db.QueryContext(ctx, getExamsAllInfos, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetExamsAllInfosRow
	for rows.Next() {
		var i GetExamsAllInfosRow
		if err := rows.Scan(
			&i.ID,
			&i.ExamName,
			&i.YearName,
			&i.PeriodName,
			&i.QcmName,
			&i.ClassCodeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExam = `-- name: UpdateExam :exec
UPDATE
    exams
SET
    name = ?1,
    qcm_id = ?2,
    class_code_id = ?3,
    period_id = ?4,
    year_id = ?5
WHERE
    id = ?6
    AND user_id = ?7
`

type UpdateExamParams struct {
	Name        string
	QcmID       int64
	ClassCodeID int64
	PeriodID    int64
	YearID      int64
	ID          int64
	UserID      int64
}

func (q *Queries) UpdateExam(ctx context.Context, arg UpdateExamParams) error {
	_, err := q.db.ExecContext(ctx, updateExam,
		arg.Name,
		arg.QcmID,
		arg.ClassCodeID,
		arg.PeriodID,
		arg.YearID,
		arg.ID,
		arg.UserID,
	)
	return err
}
