// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: exams.sql

package db

import (
	"context"
)

const getExamsAllInfos = `-- name: GetExamsAllInfos :many
SELECT 
exams.id,
exams.name AS exam_name,
years.name AS year_name,
periods.name AS period_name,
qcm.name AS qcm_name,
class_codes.name AS class_code_name
FROM exams
JOIN years ON years.id = exams.year_id
JOIN periods ON periods.id = exams.period_id
JOIN qcm ON qcm.id = exams.qcm_id
JOIN class_codes ON class_codes.id = exams.class_code_id
WHERE exams.user_id = ?1
ORDER BY exams.id DESC
`

type GetExamsAllInfosRow struct {
	ID            int64
	ExamName      string
	YearName      string
	PeriodName    string
	QcmName       string
	ClassCodeName string
}

func (q *Queries) GetExamsAllInfos(ctx context.Context, userID int64) ([]GetExamsAllInfosRow, error) {
	rows, err := q.db.QueryContext(ctx, getExamsAllInfos, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetExamsAllInfosRow
	for rows.Next() {
		var i GetExamsAllInfosRow
		if err := rows.Scan(
			&i.ID,
			&i.ExamName,
			&i.YearName,
			&i.PeriodName,
			&i.QcmName,
			&i.ClassCodeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
