// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: images.sql

package db

import (
	"context"
)

const createImage = `-- name: CreateImage :execrows
INSERT INTO
    images (
        question_id,
        image_name,
        resize_percentage,
        user_id
    )
SELECT ?1, ?2, ?3, ?4
WHERE EXISTS (SELECT 1 FROM questions q WHERE q.id = ?1 AND q.user_id = ?4)
`

type CreateImageParams struct {
	QuestionID       int64
	ImageName        string
	ResizePercentage int64
	UserID           int64
}

func (q *Queries) CreateImage(ctx context.Context, arg CreateImageParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createImage,
		arg.QuestionID,
		arg.ImageName,
		arg.ResizePercentage,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteImage = `-- name: DeleteImage :execrows
DELETE FROM
    images
WHERE
    images.question_id = ?1
    AND images.user_id = ?2
    AND EXISTS (SELECT 1 FROM questions q WHERE q.id = images.question_id AND q.user_id = ?2)
`

type DeleteImageParams struct {
	QuestionID int64
	UserID     int64
}

func (q *Queries) DeleteImage(ctx context.Context, arg DeleteImageParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteImage, arg.QuestionID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getImageByQuestionID = `-- name: GetImageByQuestionID :one
SELECT
    id, question_id, image_name, resize_percentage, user_id
FROM
    images
WHERE
    images.question_id = ?1
    AND images.user_id = ?2
    AND EXISTS (SELECT 1 FROM questions q WHERE q.id = images.question_id AND q.user_id = ?2)
`

type GetImageByQuestionIDParams struct {
	QuestionID int64
	UserID     int64
}

func (q *Queries) GetImageByQuestionID(ctx context.Context, arg GetImageByQuestionIDParams) (Image, error) {
	row := q.db.QueryRowContext(ctx, getImageByQuestionID, arg.QuestionID, arg.UserID)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.QuestionID,
		&i.ImageName,
		&i.ResizePercentage,
		&i.UserID,
	)
	return i, err
}

const listAllImageNames = `-- name: ListAllImageNames :many
SELECT image_name
FROM images
ORDER BY image_name
`

func (q *Queries) ListAllImageNames(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listAllImageNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var image_name string
		if err := rows.Scan(&image_name); err != nil {
			return nil, err
		}
		items = append(items, image_name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSizeImage = `-- name: UpdateSizeImage :execrows
UPDATE
    images
SET
    resize_percentage = ?1
WHERE
    images.question_id = ?2
    AND images.user_id = ?3
    AND EXISTS (SELECT 1 FROM questions q WHERE q.id = images.question_id AND q.user_id = ?3)
`

type UpdateSizeImageParams struct {
	ResizePercentage int64
	QuestionID       int64
	UserID           int64
}

func (q *Queries) UpdateSizeImage(ctx context.Context, arg UpdateSizeImageParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateSizeImage, arg.ResizePercentage, arg.QuestionID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const userOwnsImage = `-- name: UserOwnsImage :one
SELECT EXISTS (
    SELECT 1 FROM images i WHERE i.image_name = ?1 AND i.user_id = ?2
    UNION ALL
    SELECT 1 FROM alt_images ai WHERE ai.image_name = ?1 AND ai.user_id = ?2
)
`

type UserOwnsImageParams struct {
	RequestedImageName string
	UserID             int64
}

func (q *Queries) UserOwnsImage(ctx context.Context, arg UserOwnsImageParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, userOwnsImage, arg.RequestedImageName, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
