// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: images.sql

package db

import (
	"context"
)

const createImage = `-- name: CreateImage :exec
INSERT INTO
    images (
        question_id,
        image_name,
        resize_percentage,
        user_id
    )
VALUES
    (
        ?1,
        ?2,
        ?3,
        ?4
    )
`

type CreateImageParams struct {
	QuestionID       int64
	ImageName        string
	ResizePercentage int64
	UserID           int64
}

func (q *Queries) CreateImage(ctx context.Context, arg CreateImageParams) error {
	_, err := q.db.ExecContext(ctx, createImage,
		arg.QuestionID,
		arg.ImageName,
		arg.ResizePercentage,
		arg.UserID,
	)
	return err
}

const deleteImage = `-- name: DeleteImage :exec
DELETE FROM
    images
WHERE
    question_id = ?1
    AND user_id = ?2
`

type DeleteImageParams struct {
	QuestionID int64
	UserID     int64
}

func (q *Queries) DeleteImage(ctx context.Context, arg DeleteImageParams) error {
	_, err := q.db.ExecContext(ctx, deleteImage, arg.QuestionID, arg.UserID)
	return err
}

const getImageByQuestionID = `-- name: GetImageByQuestionID :one
SELECT
    id, question_id, image_name, resize_percentage, user_id
FROM
    images
WHERE
    question_id = ?1
    AND user_id = ?2
`

type GetImageByQuestionIDParams struct {
	QuestionID int64
	UserID     int64
}

func (q *Queries) GetImageByQuestionID(ctx context.Context, arg GetImageByQuestionIDParams) (Image, error) {
	row := q.db.QueryRowContext(ctx, getImageByQuestionID, arg.QuestionID, arg.UserID)
	var i Image
	err := row.Scan(
		&i.ID,
		&i.QuestionID,
		&i.ImageName,
		&i.ResizePercentage,
		&i.UserID,
	)
	return i, err
}

const updateSizeImage = `-- name: UpdateSizeImage :exec
UPDATE
    images
SET
    resize_percentage = ?1
WHERE
    question_id = ?2
    AND user_id = ?3
`

type UpdateSizeImageParams struct {
	ResizePercentage int64
	QuestionID       int64
	UserID           int64
}

func (q *Queries) UpdateSizeImage(ctx context.Context, arg UpdateSizeImageParams) error {
	_, err := q.db.ExecContext(ctx, updateSizeImage, arg.ResizePercentage, arg.QuestionID, arg.UserID)
	return err
}
