// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: images.sql

package db

import (
	"context"
)

const createImage = `-- name: CreateImage :exec
INSERT INTO
    images (
        question_id,
        image_name,
        resize_percentage,
        user_id
    )
VALUES
    (
        ?1,
        ?2,
        ?3,
        ?4
    )
`

type CreateImageParams struct {
	QuestionID       int64
	ImageName        string
	ResizePercentage int64
	UserID           int64
}

func (q *Queries) CreateImage(ctx context.Context, arg CreateImageParams) error {
	_, err := q.db.ExecContext(ctx, createImage,
		arg.QuestionID,
		arg.ImageName,
		arg.ResizePercentage,
		arg.UserID,
	)
	return err
}

const deleteImage = `-- name: DeleteImage :exec
DELETE FROM
    images
WHERE
    id = ?1
    AND user_id = ?2
`

type DeleteImageParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteImage(ctx context.Context, arg DeleteImageParams) error {
	_, err := q.db.ExecContext(ctx, deleteImage, arg.ID, arg.UserID)
	return err
}

const getAllimages = `-- name: GetAllimages :many
SELECT
    id, question_id, image_name, resize_percentage, user_id
FROM
    images
WHERE
    user_id = ?1
ORDER BY
    image_name
`

func (q *Queries) GetAllimages(ctx context.Context, userID int64) ([]Image, error) {
	rows, err := q.db.QueryContext(ctx, getAllimages, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Image
	for rows.Next() {
		var i Image
		if err := rows.Scan(
			&i.ID,
			&i.QuestionID,
			&i.ImageName,
			&i.ResizePercentage,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateimage = `-- name: Updateimage :exec
UPDATE
    images
SET
    image_name = ?1
WHERE
    id = ?2
    AND user_id = ?3
`

type UpdateimageParams struct {
	ImageName string
	ID        int64
	UserID    int64
}

func (q *Queries) Updateimage(ctx context.Context, arg UpdateimageParams) error {
	_, err := q.db.ExecContext(ctx, updateimage, arg.ImageName, arg.ID, arg.UserID)
	return err
}
