// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: markingJobs.sql

package db

import (
	"context"
	"database/sql"
)

const createMarkingJob = `-- name: CreateMarkingJob :one
INSERT INTO
    marking_jobs (user_id, total_pages)
VALUES
    (?1, ?2) RETURNING id
`

type CreateMarkingJobParams struct {
	UserID     int64
	TotalPages sql.NullInt64
}

func (q *Queries) CreateMarkingJob(ctx context.Context, arg CreateMarkingJobParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createMarkingJob, arg.UserID, arg.TotalPages)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const updateMarkingJobExamDone = `-- name: UpdateMarkingJobExamDone :exec
UPDATE
    marking_jobs
SET
    done_exams = done_exams + 1
WHERE
    id = ?1
    AND user_id = ?2
`

type UpdateMarkingJobExamDoneParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) UpdateMarkingJobExamDone(ctx context.Context, arg UpdateMarkingJobExamDoneParams) error {
	_, err := q.db.ExecContext(ctx, updateMarkingJobExamDone, arg.ID, arg.UserID)
	return err
}

const updateMarkingJobPageDone = `-- name: UpdateMarkingJobPageDone :exec
UPDATE
    marking_jobs
SET
    done_pages = done_pages + 1
WHERE
    id = ?1
    AND user_id = ?2
`

type UpdateMarkingJobPageDoneParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) UpdateMarkingJobPageDone(ctx context.Context, arg UpdateMarkingJobPageDoneParams) error {
	_, err := q.db.ExecContext(ctx, updateMarkingJobPageDone, arg.ID, arg.UserID)
	return err
}

const updateMarkingJobStatus = `-- name: UpdateMarkingJobStatus :exec
UPDATE
    marking_jobs
SET
    status = ?1
WHERE
    id = ?2
    AND user_id = ?3
`

type UpdateMarkingJobStatusParams struct {
	Status string
	ID     int64
	UserID int64
}

func (q *Queries) UpdateMarkingJobStatus(ctx context.Context, arg UpdateMarkingJobStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateMarkingJobStatus, arg.Status, arg.ID, arg.UserID)
	return err
}

const updateMarkingJobTotalExam = `-- name: UpdateMarkingJobTotalExam :exec
UPDATE
    marking_jobs
SET
    total_exams = ?1
WHERE
    id = ?2
    AND user_id = ?3
`

type UpdateMarkingJobTotalExamParams struct {
	TotalExams sql.NullInt64
	ID         int64
	UserID     int64
}

func (q *Queries) UpdateMarkingJobTotalExam(ctx context.Context, arg UpdateMarkingJobTotalExamParams) error {
	_, err := q.db.ExecContext(ctx, updateMarkingJobTotalExam, arg.TotalExams, arg.ID, arg.UserID)
	return err
}
