// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: markingReviews.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const advanceMarkingJobReviewRevision = `-- name: AdvanceMarkingJobReviewRevision :execrows
UPDATE marking_jobs
SET
    review_revision = review_revision + 1,
    artifacts_revision = CASE
        WHEN CAST(?1 AS INTEGER) = 0
         AND artifacts_revision = review_revision
        THEN review_revision + 1
        ELSE artifacts_revision
    END
WHERE id = ?2
  AND user_id = ?3
  AND status = 'success'
  AND review_revision = ?4
`

type AdvanceMarkingJobReviewRevisionParams struct {
	EffectiveChanged       int64
	MarkingJobID           int64
	UserID                 int64
	ExpectedReviewRevision int64
}

func (q *Queries) AdvanceMarkingJobReviewRevision(ctx context.Context, arg AdvanceMarkingJobReviewRevisionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, advanceMarkingJobReviewRevision,
		arg.EffectiveChanged,
		arg.MarkingJobID,
		arg.UserID,
		arg.ExpectedReviewRevision,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createMarkingAlignedPage = `-- name: CreateMarkingAlignedPage :one
INSERT INTO marking_aligned_pages (
    user_id,
    copy_result_id,
    page_exam,
    storage_key,
    width,
    height,
    sha256
)
SELECT
    ?1,
    mcr.id,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6
FROM marking_copy_results AS mcr
JOIN marking_jobs AS mj
  ON mj.id = mcr.marking_job_id
 AND mj.user_id = mcr.user_id
WHERE mcr.id = ?7
  AND mcr.user_id = ?1
  AND mj.user_id = ?1
  AND mcr.outcome = 'corrected'
  AND ?3 = printf(
      'aligned/student-exam-%d/page-%d.png',
      mcr.student_exam_id,
      ?2
  )
  AND (SELECT COUNT(*)
       FROM student_exam_page_content AS sep
       WHERE sep.student_exam_id = mcr.student_exam_id
         AND sep.user_id = mcr.user_id
         AND sep.page = ?2) = 1
RETURNING id
`

type CreateMarkingAlignedPageParams struct {
	UserID       int64
	PageExam     int64
	StorageKey   string
	Width        int64
	Height       int64
	Sha256       string
	CopyResultID int64
}

func (q *Queries) CreateMarkingAlignedPage(ctx context.Context, arg CreateMarkingAlignedPageParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createMarkingAlignedPage,
		arg.UserID,
		arg.PageExam,
		arg.StorageKey,
		arg.Width,
		arg.Height,
		arg.Sha256,
		arg.CopyResultID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createMarkingAnswerReview = `-- name: CreateMarkingAnswerReview :one
INSERT INTO marking_answer_reviews (
    answer_detection_id,
    reviewer_user_id,
    reviewed_state
)
SELECT
    mad.id,
    ?1,
    ?2
FROM marking_answer_detections AS mad
JOIN marking_question_results AS mqr ON mqr.id = mad.question_result_id
JOIN marking_copy_results AS mcr ON mcr.id = mqr.copy_result_id
JOIN marking_jobs AS mj
  ON mj.id = mcr.marking_job_id
 AND mj.user_id = mcr.user_id
WHERE mad.id = ?3
  AND mj.user_id = ?1
RETURNING id
`

type CreateMarkingAnswerReviewParams struct {
	ReviewerUserID    int64
	ReviewedState     int64
	AnswerDetectionID int64
}

func (q *Queries) CreateMarkingAnswerReview(ctx context.Context, arg CreateMarkingAnswerReviewParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createMarkingAnswerReview, arg.ReviewerUserID, arg.ReviewedState, arg.AnswerDetectionID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getEffectiveAnswerDetection = `-- name: GetEffectiveAnswerDetection :one
SELECT
    mad.id,
    mad.detected_state,
    mad.mean_gray,
    mar.reviewed_state AS "reviewed_state?",
    COALESCE(mar.reviewed_state, mad.detected_state) AS effective_state,
    mar.reviewed_at,
    mar.revision
FROM marking_answer_detections AS mad
JOIN marking_question_results AS mqr ON mqr.id = mad.question_result_id
JOIN marking_copy_results AS mcr ON mcr.id = mqr.copy_result_id
JOIN marking_jobs AS mj
  ON mj.id = mcr.marking_job_id
 AND mj.user_id = mcr.user_id
LEFT JOIN marking_answer_reviews AS mar ON mar.answer_detection_id = mad.id
WHERE mad.id = ?1
  AND mj.user_id = ?2
`

type GetEffectiveAnswerDetectionParams struct {
	AnswerDetectionID int64
	UserID            int64
}

type GetEffectiveAnswerDetectionRow struct {
	ID             int64
	DetectedState  int64
	MeanGray       float64
	ReviewedState  sql.NullInt64
	EffectiveState int64
	ReviewedAt     sql.NullTime
	Revision       sql.NullInt64
}

func (q *Queries) GetEffectiveAnswerDetection(ctx context.Context, arg GetEffectiveAnswerDetectionParams) (GetEffectiveAnswerDetectionRow, error) {
	row := q.db.QueryRowContext(ctx, getEffectiveAnswerDetection, arg.AnswerDetectionID, arg.UserID)
	var i GetEffectiveAnswerDetectionRow
	err := row.Scan(
		&i.ID,
		&i.DetectedState,
		&i.MeanGray,
		&i.ReviewedState,
		&i.EffectiveState,
		&i.ReviewedAt,
		&i.Revision,
	)
	return i, err
}

const getMarkingAlignedPage = `-- name: GetMarkingAlignedPage :one
SELECT
    map.id,
    map.user_id,
    map.copy_result_id,
    map.page_exam,
    map.storage_key,
    map.width,
    map.height,
    map.sha256,
    map.created_at,
    mcr.student_exam_id,
    mcr.marking_job_id,
    u.username
FROM marking_aligned_pages AS map
JOIN marking_copy_results AS mcr ON mcr.id = map.copy_result_id
JOIN marking_jobs AS mj
  ON mj.id = mcr.marking_job_id
 AND mj.user_id = mcr.user_id
JOIN users AS u ON u.id = mj.user_id
WHERE map.copy_result_id = ?1
  AND map.page_exam = ?2
  AND mj.user_id = ?3
`

type GetMarkingAlignedPageParams struct {
	CopyResultID int64
	PageExam     int64
	UserID       int64
}

type GetMarkingAlignedPageRow struct {
	ID            int64
	UserID        int64
	CopyResultID  int64
	PageExam      int64
	StorageKey    string
	Width         int64
	Height        int64
	Sha256        string
	CreatedAt     time.Time
	StudentExamID int64
	MarkingJobID  int64
	Username      string
}

func (q *Queries) GetMarkingAlignedPage(ctx context.Context, arg GetMarkingAlignedPageParams) (GetMarkingAlignedPageRow, error) {
	row := q.db.QueryRowContext(ctx, getMarkingAlignedPage, arg.CopyResultID, arg.PageExam, arg.UserID)
	var i GetMarkingAlignedPageRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CopyResultID,
		&i.PageExam,
		&i.StorageKey,
		&i.Width,
		&i.Height,
		&i.Sha256,
		&i.CreatedAt,
		&i.StudentExamID,
		&i.MarkingJobID,
		&i.Username,
	)
	return i, err
}

const getMarkingAnswerReview = `-- name: GetMarkingAnswerReview :one
SELECT mar.id, mar.answer_detection_id, mar.reviewer_user_id, mar.reviewed_state, mar.reviewed_at, mar.revision
FROM marking_answer_reviews AS mar
JOIN marking_answer_detections AS mad ON mad.id = mar.answer_detection_id
JOIN marking_question_results AS mqr ON mqr.id = mad.question_result_id
JOIN marking_copy_results AS mcr ON mcr.id = mqr.copy_result_id
JOIN marking_jobs AS mj
  ON mj.id = mcr.marking_job_id
 AND mj.user_id = mcr.user_id
WHERE mar.answer_detection_id = ?1
  AND mj.user_id = ?2
`

type GetMarkingAnswerReviewParams struct {
	AnswerDetectionID int64
	UserID            int64
}

func (q *Queries) GetMarkingAnswerReview(ctx context.Context, arg GetMarkingAnswerReviewParams) (MarkingAnswerReview, error) {
	row := q.db.QueryRowContext(ctx, getMarkingAnswerReview, arg.AnswerDetectionID, arg.UserID)
	var i MarkingAnswerReview
	err := row.Scan(
		&i.ID,
		&i.AnswerDetectionID,
		&i.ReviewerUserID,
		&i.ReviewedState,
		&i.ReviewedAt,
		&i.Revision,
	)
	return i, err
}

const getMarkingAnswerReviewTarget = `-- name: GetMarkingAnswerReviewTarget :one
SELECT
    mj.review_revision AS job_review_revision,
    mj.artifacts_revision,
    mcr.id AS copy_result_id,
    mcr.student_exam_id,
    mqr.id AS question_result_id,
    mqr.question_index,
    mqr.total_points,
    mad.detected_state,
    mar.reviewed_state AS "reviewed_state?",
    COALESCE(mar.reviewed_state, mad.detected_state) AS effective_state,
    mar.revision AS "answer_review_revision?",
    sec.content AS snapshot_content
FROM marking_jobs AS mj
JOIN marking_copy_results AS mcr
  ON mcr.marking_job_id = mj.id
 AND mcr.user_id = mj.user_id
 AND mcr.outcome = 'corrected'
JOIN marking_question_results AS mqr ON mqr.copy_result_id = mcr.id
JOIN marking_answer_detections AS mad ON mad.question_result_id = mqr.id
JOIN student_exam_content AS sec
  ON sec.student_exam_id = mcr.student_exam_id
 AND sec.user_id = mcr.user_id
LEFT JOIN marking_answer_reviews AS mar ON mar.answer_detection_id = mad.id
WHERE mj.id = ?1
  AND mj.user_id = ?2
  AND mj.status = 'success'
  AND mad.id = ?3
`

type GetMarkingAnswerReviewTargetParams struct {
	MarkingJobID      int64
	UserID            int64
	AnswerDetectionID int64
}

type GetMarkingAnswerReviewTargetRow struct {
	JobReviewRevision    int64
	ArtifactsRevision    int64
	CopyResultID         int64
	StudentExamID        int64
	QuestionResultID     int64
	QuestionIndex        int64
	TotalPoints          int64
	DetectedState        int64
	ReviewedState        sql.NullInt64
	EffectiveState       int64
	AnswerReviewRevision sql.NullInt64
	SnapshotContent      string
}

func (q *Queries) GetMarkingAnswerReviewTarget(ctx context.Context, arg GetMarkingAnswerReviewTargetParams) (GetMarkingAnswerReviewTargetRow, error) {
	row := q.db.QueryRowContext(ctx, getMarkingAnswerReviewTarget, arg.MarkingJobID, arg.UserID, arg.AnswerDetectionID)
	var i GetMarkingAnswerReviewTargetRow
	err := row.Scan(
		&i.JobReviewRevision,
		&i.ArtifactsRevision,
		&i.CopyResultID,
		&i.StudentExamID,
		&i.QuestionResultID,
		&i.QuestionIndex,
		&i.TotalPoints,
		&i.DetectedState,
		&i.ReviewedState,
		&i.EffectiveState,
		&i.AnswerReviewRevision,
		&i.SnapshotContent,
	)
	return i, err
}

const getMarkingReviewSummary = `-- name: GetMarkingReviewSummary :one
SELECT
    mj.ambiguity_delta,
    COUNT(mad.id) AS total_candidates,
    COUNT(mar.id) AS reviewed_candidates,
    COUNT(mad.id) - COUNT(mar.id) AS pending_candidates
FROM marking_jobs AS mj
LEFT JOIN marking_copy_results AS mcr
  ON mcr.marking_job_id = mj.id
 AND mcr.user_id = mj.user_id
 AND mcr.outcome = 'corrected'
LEFT JOIN marking_question_results AS mqr ON mqr.copy_result_id = mcr.id
LEFT JOIN marking_answer_detections AS mad
  ON mad.question_result_id = mqr.id
 AND mj.detection_threshold IS NOT NULL
 AND mj.ambiguity_delta IS NOT NULL
 AND ABS(mad.mean_gray - mj.detection_threshold) <= mj.ambiguity_delta
LEFT JOIN marking_answer_reviews AS mar ON mar.answer_detection_id = mad.id
WHERE mj.id = ?1
  AND mj.user_id = ?2
  AND mj.status = 'success'
GROUP BY mj.id, mj.ambiguity_delta
`

type GetMarkingReviewSummaryParams struct {
	MarkingJobID int64
	UserID       int64
}

type GetMarkingReviewSummaryRow struct {
	AmbiguityDelta     sql.NullFloat64
	TotalCandidates    int64
	ReviewedCandidates int64
	PendingCandidates  int64
}

func (q *Queries) GetMarkingReviewSummary(ctx context.Context, arg GetMarkingReviewSummaryParams) (GetMarkingReviewSummaryRow, error) {
	row := q.db.QueryRowContext(ctx, getMarkingReviewSummary, arg.MarkingJobID, arg.UserID)
	var i GetMarkingReviewSummaryRow
	err := row.Scan(
		&i.AmbiguityDelta,
		&i.TotalCandidates,
		&i.ReviewedCandidates,
		&i.PendingCandidates,
	)
	return i, err
}

const listEffectiveQuestionAnswersForReview = `-- name: ListEffectiveQuestionAnswersForReview :many
SELECT
    mad.answer_index,
    mad.detected_state,
    mar.reviewed_state AS "reviewed_state?",
    COALESCE(mar.reviewed_state, mad.detected_state) AS effective_state
FROM marking_answer_detections AS mad
JOIN marking_question_results AS mqr ON mqr.id = mad.question_result_id
JOIN marking_copy_results AS mcr ON mcr.id = mqr.copy_result_id
JOIN marking_jobs AS mj
  ON mj.id = mcr.marking_job_id
 AND mj.user_id = mcr.user_id
LEFT JOIN marking_answer_reviews AS mar ON mar.answer_detection_id = mad.id
WHERE mad.question_result_id = ?1
  AND mcr.id = ?2
  AND mj.id = ?3
  AND mj.user_id = ?4
  AND mj.status = 'success'
  AND mcr.outcome = 'corrected'
ORDER BY mad.answer_index
`

type ListEffectiveQuestionAnswersForReviewParams struct {
	QuestionResultID int64
	CopyResultID     int64
	MarkingJobID     int64
	UserID           int64
}

type ListEffectiveQuestionAnswersForReviewRow struct {
	AnswerIndex    int64
	DetectedState  int64
	ReviewedState  sql.NullInt64
	EffectiveState int64
}

func (q *Queries) ListEffectiveQuestionAnswersForReview(ctx context.Context, arg ListEffectiveQuestionAnswersForReviewParams) ([]ListEffectiveQuestionAnswersForReviewRow, error) {
	rows, err := q.db.QueryContext(ctx, listEffectiveQuestionAnswersForReview,
		arg.QuestionResultID,
		arg.CopyResultID,
		arg.MarkingJobID,
		arg.UserID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEffectiveQuestionAnswersForReviewRow
	for rows.Next() {
		var i ListEffectiveQuestionAnswersForReviewRow
		if err := rows.Scan(
			&i.AnswerIndex,
			&i.DetectedState,
			&i.ReviewedState,
			&i.EffectiveState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMarkingReviewCandidates = `-- name: ListMarkingReviewCandidates :many
SELECT
    mad.id AS answer_detection_id,
    mcr.id AS copy_result_id,
    mcr.student_exam_id,
    mqr.question_index,
    mad.answer_index,
    mad.detected_state,
    mar.reviewed_state AS "reviewed_state?",
    COALESCE(mar.reviewed_state, mad.detected_state) AS effective_state,
    mad.mean_gray,
    mj.detection_threshold AS threshold,
    mj.ambiguity_delta,
    map.id AS aligned_page_id,
    map.page_exam,
    map.storage_key
FROM marking_jobs AS mj
JOIN marking_copy_results AS mcr
  ON mcr.marking_job_id = mj.id
 AND mcr.user_id = mj.user_id
 AND mcr.outcome = 'corrected'
JOIN marking_question_results AS mqr ON mqr.copy_result_id = mcr.id
JOIN marking_answer_detections AS mad ON mad.question_result_id = mqr.id
JOIN student_exam_page_content AS sep
  ON sep.student_exam_id = mcr.student_exam_id
 AND sep.user_id = mcr.user_id
 AND mqr.question_index >= (
     SELECT COALESCE(SUM(json_array_length(previous.content, '$.questions')), 0)
     FROM student_exam_page_content AS previous
     WHERE previous.student_exam_id = sep.student_exam_id
       AND previous.user_id = sep.user_id
       AND previous.page < sep.page
 )
 AND mqr.question_index < (
     SELECT COALESCE(SUM(json_array_length(previous.content, '$.questions')), 0)
     FROM student_exam_page_content AS previous
     WHERE previous.student_exam_id = sep.student_exam_id
       AND previous.user_id = sep.user_id
       AND previous.page < sep.page
 ) + json_array_length(sep.content, '$.questions')
JOIN marking_aligned_pages AS map
  ON map.copy_result_id = mcr.id
 AND map.user_id = mcr.user_id
 AND map.page_exam = sep.page
LEFT JOIN marking_answer_reviews AS mar ON mar.answer_detection_id = mad.id
WHERE mj.id = ?1
  AND mj.user_id = ?2
  AND mj.status = 'success'
  AND mj.detection_threshold IS NOT NULL
  AND mj.ambiguity_delta IS NOT NULL
  AND ABS(mad.mean_gray - mj.detection_threshold) <= mj.ambiguity_delta
ORDER BY mcr.student_exam_id, mqr.question_index, mad.answer_index
`

type ListMarkingReviewCandidatesParams struct {
	MarkingJobID int64
	UserID       int64
}

type ListMarkingReviewCandidatesRow struct {
	AnswerDetectionID int64
	CopyResultID      int64
	StudentExamID     int64
	QuestionIndex     int64
	AnswerIndex       int64
	DetectedState     int64
	ReviewedState     sql.NullInt64
	EffectiveState    int64
	MeanGray          float64
	Threshold         sql.NullFloat64
	AmbiguityDelta    sql.NullFloat64
	AlignedPageID     int64
	PageExam          int64
	StorageKey        string
}

func (q *Queries) ListMarkingReviewCandidates(ctx context.Context, arg ListMarkingReviewCandidatesParams) ([]ListMarkingReviewCandidatesRow, error) {
	rows, err := q.db.QueryContext(ctx, listMarkingReviewCandidates, arg.MarkingJobID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMarkingReviewCandidatesRow
	for rows.Next() {
		var i ListMarkingReviewCandidatesRow
		if err := rows.Scan(
			&i.AnswerDetectionID,
			&i.CopyResultID,
			&i.StudentExamID,
			&i.QuestionIndex,
			&i.AnswerIndex,
			&i.DetectedState,
			&i.ReviewedState,
			&i.EffectiveState,
			&i.MeanGray,
			&i.Threshold,
			&i.AmbiguityDelta,
			&i.AlignedPageID,
			&i.PageExam,
			&i.StorageKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingMarkingReviewCandidates = `-- name: ListPendingMarkingReviewCandidates :many
SELECT
    mad.id AS answer_detection_id,
    mcr.id AS copy_result_id,
    mcr.student_exam_id,
    mqr.question_index,
    mad.answer_index,
    mad.detected_state,
    mad.mean_gray,
    mj.detection_threshold AS threshold,
    mj.ambiguity_delta,
    map.id AS aligned_page_id,
    map.page_exam,
    map.storage_key
FROM marking_jobs AS mj
JOIN marking_copy_results AS mcr
  ON mcr.marking_job_id = mj.id
 AND mcr.user_id = mj.user_id
 AND mcr.outcome = 'corrected'
JOIN marking_question_results AS mqr ON mqr.copy_result_id = mcr.id
JOIN marking_answer_detections AS mad ON mad.question_result_id = mqr.id
LEFT JOIN marking_answer_reviews AS mar ON mar.answer_detection_id = mad.id
JOIN student_exam_page_content AS sep
  ON sep.student_exam_id = mcr.student_exam_id
 AND sep.user_id = mcr.user_id
 AND mqr.question_index >= (
     SELECT COALESCE(SUM(json_array_length(previous.content, '$.questions')), 0)
     FROM student_exam_page_content AS previous
     WHERE previous.student_exam_id = sep.student_exam_id
       AND previous.user_id = sep.user_id
       AND previous.page < sep.page
 )
 AND mqr.question_index < (
     SELECT COALESCE(SUM(json_array_length(previous.content, '$.questions')), 0)
     FROM student_exam_page_content AS previous
     WHERE previous.student_exam_id = sep.student_exam_id
       AND previous.user_id = sep.user_id
       AND previous.page < sep.page
 ) + json_array_length(sep.content, '$.questions')
JOIN marking_aligned_pages AS map
  ON map.copy_result_id = mcr.id
 AND map.user_id = mcr.user_id
 AND map.page_exam = sep.page
WHERE mj.id = ?1
  AND mj.user_id = ?2
  AND mj.status = 'success'
  AND mj.detection_threshold IS NOT NULL
  AND mj.ambiguity_delta IS NOT NULL
  AND ABS(mad.mean_gray - mj.detection_threshold) <= mj.ambiguity_delta
  AND mar.id IS NULL
ORDER BY mcr.student_exam_id, mqr.question_index, mad.answer_index
`

type ListPendingMarkingReviewCandidatesParams struct {
	MarkingJobID int64
	UserID       int64
}

type ListPendingMarkingReviewCandidatesRow struct {
	AnswerDetectionID int64
	CopyResultID      int64
	StudentExamID     int64
	QuestionIndex     int64
	AnswerIndex       int64
	DetectedState     int64
	MeanGray          float64
	Threshold         sql.NullFloat64
	AmbiguityDelta    sql.NullFloat64
	AlignedPageID     int64
	PageExam          int64
	StorageKey        string
}

func (q *Queries) ListPendingMarkingReviewCandidates(ctx context.Context, arg ListPendingMarkingReviewCandidatesParams) ([]ListPendingMarkingReviewCandidatesRow, error) {
	rows, err := q.db.QueryContext(ctx, listPendingMarkingReviewCandidates, arg.MarkingJobID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingMarkingReviewCandidatesRow
	for rows.Next() {
		var i ListPendingMarkingReviewCandidatesRow
		if err := rows.Scan(
			&i.AnswerDetectionID,
			&i.CopyResultID,
			&i.StudentExamID,
			&i.QuestionIndex,
			&i.AnswerIndex,
			&i.DetectedState,
			&i.MeanGray,
			&i.Threshold,
			&i.AmbiguityDelta,
			&i.AlignedPageID,
			&i.PageExam,
			&i.StorageKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recalculateMarkingCopyScoreFromQuestions = `-- name: RecalculateMarkingCopyScoreFromQuestions :execrows
UPDATE marking_copy_results
SET score_half_units = (
    SELECT COALESCE(SUM(mqr.score_half_units), 0)
    FROM marking_question_results AS mqr
    WHERE mqr.copy_result_id = marking_copy_results.id
)
WHERE marking_copy_results.id = ?1
  AND marking_copy_results.user_id = ?2
  AND marking_copy_results.marking_job_id = ?3
  AND marking_copy_results.outcome = 'corrected'
  AND EXISTS (
      SELECT 1
      FROM marking_jobs AS mj
      WHERE mj.id = marking_copy_results.marking_job_id
        AND mj.user_id = marking_copy_results.user_id
        AND mj.status = 'success'
  )
`

type RecalculateMarkingCopyScoreFromQuestionsParams struct {
	CopyResultID int64
	UserID       int64
	MarkingJobID int64
}

func (q *Queries) RecalculateMarkingCopyScoreFromQuestions(ctx context.Context, arg RecalculateMarkingCopyScoreFromQuestionsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, recalculateMarkingCopyScoreFromQuestions, arg.CopyResultID, arg.UserID, arg.MarkingJobID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateMarkingAnswerReview = `-- name: UpdateMarkingAnswerReview :execrows
UPDATE marking_answer_reviews
SET
    reviewed_state = ?1,
    reviewed_at = CURRENT_TIMESTAMP,
    revision = revision + 1
WHERE answer_detection_id = ?2
  AND reviewer_user_id = ?3
  AND revision = ?4
  AND EXISTS (
      SELECT 1
      FROM marking_answer_detections AS mad
      JOIN marking_question_results AS mqr ON mqr.id = mad.question_result_id
      JOIN marking_copy_results AS mcr ON mcr.id = mqr.copy_result_id
      JOIN marking_jobs AS mj
        ON mj.id = mcr.marking_job_id
       AND mj.user_id = mcr.user_id
      WHERE mad.id = marking_answer_reviews.answer_detection_id
        AND mj.user_id = ?3
  )
`

type UpdateMarkingAnswerReviewParams struct {
	ReviewedState     int64
	AnswerDetectionID int64
	ReviewerUserID    int64
	ExpectedRevision  int64
}

func (q *Queries) UpdateMarkingAnswerReview(ctx context.Context, arg UpdateMarkingAnswerReviewParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateMarkingAnswerReview,
		arg.ReviewedState,
		arg.AnswerDetectionID,
		arg.ReviewerUserID,
		arg.ExpectedRevision,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateMarkingQuestionResultFromReview = `-- name: UpdateMarkingQuestionResultFromReview :execrows
UPDATE marking_question_results
SET
    state = ?1,
    score_half_units = ?2
WHERE marking_question_results.id = ?3
  AND marking_question_results.copy_result_id = ?4
  AND EXISTS (
      SELECT 1
      FROM marking_copy_results AS mcr
      JOIN marking_jobs AS mj
        ON mj.id = mcr.marking_job_id
       AND mj.user_id = mcr.user_id
      WHERE mcr.id = marking_question_results.copy_result_id
        AND mcr.user_id = ?5
        AND mcr.outcome = 'corrected'
        AND mj.id = ?6
        AND mj.status = 'success'
  )
`

type UpdateMarkingQuestionResultFromReviewParams struct {
	State            string
	ScoreHalfUnits   int64
	QuestionResultID int64
	CopyResultID     int64
	UserID           int64
	MarkingJobID     int64
}

func (q *Queries) UpdateMarkingQuestionResultFromReview(ctx context.Context, arg UpdateMarkingQuestionResultFromReviewParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateMarkingQuestionResultFromReview,
		arg.State,
		arg.ScoreHalfUnits,
		arg.QuestionResultID,
		arg.CopyResultID,
		arg.UserID,
		arg.MarkingJobID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const validateMarkingAlignedPageTarget = `-- name: ValidateMarkingAlignedPageTarget :one
SELECT mcr.id
FROM marking_copy_results AS mcr
JOIN marking_jobs AS mj
  ON mj.id = mcr.marking_job_id
 AND mj.user_id = mcr.user_id
WHERE mcr.id = ?1
  AND mcr.marking_job_id = ?2
  AND mcr.student_exam_id = ?3
  AND mcr.user_id = ?4
  AND mcr.outcome = 'corrected'
  AND (SELECT COUNT(*)
       FROM student_exam_page_content AS sep
       WHERE sep.student_exam_id = mcr.student_exam_id
         AND sep.user_id = mcr.user_id
         AND sep.page = ?5) = 1
`

type ValidateMarkingAlignedPageTargetParams struct {
	CopyResultID  int64
	MarkingJobID  int64
	StudentExamID int64
	UserID        int64
	PageExam      int64
}

func (q *Queries) ValidateMarkingAlignedPageTarget(ctx context.Context, arg ValidateMarkingAlignedPageTargetParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, validateMarkingAlignedPageTarget,
		arg.CopyResultID,
		arg.MarkingJobID,
		arg.StudentExamID,
		arg.UserID,
		arg.PageExam,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
