// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: markingWorkflow.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const getMarkingGeneration = `-- name: GetMarkingGeneration :one
SELECT eg.id, e.name AS exam_name, cc.name AS class_name
FROM exams_generated AS eg
JOIN exams AS e ON e.id = eg.exam_id AND e.user_id = eg.user_id
JOIN class_codes AS cc ON cc.id = e.class_code_id AND cc.user_id = eg.user_id
WHERE eg.id = ?1 AND eg.user_id = ?2
  AND eg.status = 'success'
`

type GetMarkingGenerationParams struct {
	GenerationID int64
	UserID       int64
}

type GetMarkingGenerationRow struct {
	ID        int64
	ExamName  string
	ClassName string
}

func (q *Queries) GetMarkingGeneration(ctx context.Context, arg GetMarkingGenerationParams) (GetMarkingGenerationRow, error) {
	row := q.db.QueryRowContext(ctx, getMarkingGeneration, arg.GenerationID, arg.UserID)
	var i GetMarkingGenerationRow
	err := row.Scan(&i.ID, &i.ExamName, &i.ClassName)
	return i, err
}

const getMarkingJobGeneration = `-- name: GetMarkingJobGeneration :one
SELECT exam_generated_id FROM marking_jobs
WHERE id = ?1 AND user_id = ?2
`

type GetMarkingJobGenerationParams struct {
	MarkingJobID int64
	UserID       int64
}

func (q *Queries) GetMarkingJobGeneration(ctx context.Context, arg GetMarkingJobGenerationParams) (sql.NullInt64, error) {
	row := q.db.QueryRowContext(ctx, getMarkingJobGeneration, arg.MarkingJobID, arg.UserID)
	var exam_generated_id sql.NullInt64
	err := row.Scan(&exam_generated_id)
	return exam_generated_id, err
}

const listCurrentExamResultsForGeneration = `-- name: ListCurrentExamResultsForGeneration :many
WITH selected_generation AS (
    SELECT anchor.id AS exam_generated_id
    FROM exams_generated AS anchor
    WHERE anchor.id = ?2
      AND anchor.user_id = ?1
),
ranked_results AS (
    SELECT
        mcr.id AS copy_result_id,
        mcr.student_exam_id,
        mcr.marking_job_id,
        mcr.outcome,
        mcr.score_half_units,
        mcr.total_points,
        mcr.completed_at,
        ROW_NUMBER() OVER (
            PARTITION BY mcr.student_exam_id
            ORDER BY
                CASE WHEN mcr.outcome = 'corrected' THEN 0 ELSE 1 END,
                mj.id DESC,
                mcr.id DESC
        ) AS result_rank
    FROM marking_copy_results AS mcr
    JOIN marking_jobs AS mj
      ON mj.id = mcr.marking_job_id
     AND mj.user_id = mcr.user_id
    JOIN selected_generation AS selected
      ON selected.exam_generated_id = mj.exam_generated_id
    WHERE mcr.user_id = ?1
      AND mj.status = 'success'
      AND mj.status_pdf = 'success'
)
SELECT
    ranked.copy_result_id,
    ranked.student_exam_id,
    ranked.marking_job_id,
    s.first_name,
    s.last_name,
    ranked.outcome,
    ranked.score_half_units,
    ranked.total_points,
    ranked.completed_at,
    CAST(COALESCE((
        SELECT sec.content FROM student_exam_content AS sec
        WHERE sec.student_exam_id = ranked.student_exam_id
          AND sec.user_id = ?1
    ), '') AS TEXT) AS snapshot_content,
    CAST((
        SELECT json_group_array(json_object(
            'question_index', mqr.question_index,
            'state', mqr.state,
            'score_half_units', mqr.score_half_units,
            'total_points', mqr.total_points
        ))
        FROM marking_question_results AS mqr
        WHERE mqr.copy_result_id = ranked.copy_result_id
    ) AS TEXT) AS question_results,
    CAST(COALESCE((
        SELECT COUNT(*)
        FROM marking_question_results AS mqr
        JOIN marking_answer_detections AS mad ON mad.question_result_id = mqr.id
        JOIN marking_jobs AS result_job ON result_job.id = ranked.marking_job_id
        LEFT JOIN marking_answer_reviews AS mar ON mar.answer_detection_id = mad.id
        WHERE mqr.copy_result_id = ranked.copy_result_id
          AND mar.id IS NULL
          AND (
              (result_job.review_policy_version IN ('detector-agreement-v1', 'detector-color-confidence-v1')
               AND mad.review_reason = 'detector_disagreement')
              OR
              (result_job.review_policy_version IS NULL
               AND result_job.detection_threshold IS NOT NULL
               AND result_job.ambiguity_delta IS NOT NULL
               AND ABS(mad.mean_gray - result_job.detection_threshold) <= result_job.ambiguity_delta)
          )
    ), 0) AS INTEGER) AS pending_reviews
FROM ranked_results AS ranked
JOIN student_exam AS se
  ON se.id = ranked.student_exam_id
 AND se.user_id = ?1
JOIN students AS s
  ON s.id = se.student_id
 AND s.user_id = ?1
WHERE ranked.result_rank = 1
`

type ListCurrentExamResultsForGenerationParams struct {
	UserID       int64
	GenerationID int64
}

type ListCurrentExamResultsForGenerationRow struct {
	CopyResultID    int64
	StudentExamID   int64
	MarkingJobID    int64
	FirstName       string
	LastName        string
	Outcome         string
	ScoreHalfUnits  sql.NullInt64
	TotalPoints     sql.NullInt64
	CompletedAt     time.Time
	SnapshotContent string
	QuestionResults string
	PendingReviews  int64
}

// Presentation order is applied once by buildMarkingExamSummary using French
// collation, shared by HTML and PDF (SQLite NOCASE only handles ASCII).
func (q *Queries) ListCurrentExamResultsForGeneration(ctx context.Context, arg ListCurrentExamResultsForGenerationParams) ([]ListCurrentExamResultsForGenerationRow, error) {
	rows, err := q.db.QueryContext(ctx, listCurrentExamResultsForGeneration, arg.UserID, arg.GenerationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCurrentExamResultsForGenerationRow
	for rows.Next() {
		var i ListCurrentExamResultsForGenerationRow
		if err := rows.Scan(
			&i.CopyResultID,
			&i.StudentExamID,
			&i.MarkingJobID,
			&i.FirstName,
			&i.LastName,
			&i.Outcome,
			&i.ScoreHalfUnits,
			&i.TotalPoints,
			&i.CompletedAt,
			&i.SnapshotContent,
			&i.QuestionResults,
			&i.PendingReviews,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMarkingJobHistory = `-- name: ListMarkingJobHistory :many
SELECT
    mj.id,
    mj.exam_generated_id,
    e.name AS exam_name,
    cc.name AS class_code_name,
    mj.source_pdf_filename,
    mj.status,
    mj.status_pdf,
    mj.completed_at,
    COUNT(DISTINCT mcr.id) FILTER (WHERE mcr.outcome = 'corrected') AS corrected_copies,
    COUNT(DISTINCT mcr.id) FILTER (WHERE mcr.outcome IN ('incomplete', 'error')) AS issue_copies,
    COUNT(DISTINCT mcr.id) FILTER (WHERE mcr.outcome = 'not_seen') AS not_seen_copies,
    CAST(COALESCE(SUM(CASE WHEN
        mcr.outcome = 'corrected'
        AND mad.id IS NOT NULL
        AND mar.id IS NULL
        AND (
            (mj.review_policy_version IN ('detector-agreement-v1', 'detector-color-confidence-v1')
             AND mad.review_reason = 'detector_disagreement')
            OR
            (mj.review_policy_version IS NULL
             AND mj.detection_threshold IS NOT NULL
             AND mj.ambiguity_delta IS NOT NULL
             AND ABS(mad.mean_gray - mj.detection_threshold) <= mj.ambiguity_delta)
        )
        THEN 1 ELSE 0 END), 0) AS INTEGER) AS pending_reviews
FROM marking_jobs AS mj
JOIN exams_generated AS eg
  ON eg.id = mj.exam_generated_id
 AND eg.user_id = mj.user_id
JOIN exams AS e
  ON e.id = eg.exam_id
 AND e.user_id = mj.user_id
JOIN class_codes AS cc
  ON cc.id = e.class_code_id
 AND cc.user_id = mj.user_id
LEFT JOIN marking_copy_results AS mcr
  ON mcr.marking_job_id = mj.id
 AND mcr.user_id = mj.user_id
LEFT JOIN marking_question_results AS mqr ON mqr.copy_result_id = mcr.id
LEFT JOIN marking_answer_detections AS mad ON mad.question_result_id = mqr.id
LEFT JOIN marking_answer_reviews AS mar ON mar.answer_detection_id = mad.id
WHERE mj.user_id = ?1
  AND (?2 = 0 OR mj.exam_generated_id = ?2)
GROUP BY mj.id
ORDER BY mj.id DESC
LIMIT CASE WHEN ?2 = 0 THEN 20 ELSE -1 END
`

type ListMarkingJobHistoryParams struct {
	UserID       int64
	GenerationID interface{}
}

type ListMarkingJobHistoryRow struct {
	ID                int64
	ExamGeneratedID   sql.NullInt64
	ExamName          string
	ClassCodeName     string
	SourcePdfFilename sql.NullString
	Status            string
	StatusPdf         string
	CompletedAt       sql.NullTime
	CorrectedCopies   int64
	IssueCopies       int64
	NotSeenCopies     int64
	PendingReviews    int64
}

func (q *Queries) ListMarkingJobHistory(ctx context.Context, arg ListMarkingJobHistoryParams) ([]ListMarkingJobHistoryRow, error) {
	rows, err := q.db.QueryContext(ctx, listMarkingJobHistory, arg.UserID, arg.GenerationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMarkingJobHistoryRow
	for rows.Next() {
		var i ListMarkingJobHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.ExamGeneratedID,
			&i.ExamName,
			&i.ClassCodeName,
			&i.SourcePdfFilename,
			&i.Status,
			&i.StatusPdf,
			&i.CompletedAt,
			&i.CorrectedCopies,
			&i.IssueCopies,
			&i.NotSeenCopies,
			&i.PendingReviews,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
