// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: markingJobs.sql

package db

import (
	"context"
	"database/sql"
)

const completeMarkingJob = `-- name: CompleteMarkingJob :execrows
UPDATE
    marking_jobs
SET
    status = 'success',
    status_pdf = 'success',
    exam_name = ?1,
    mark_table_name = ?2,
    completed_at = CURRENT_TIMESTAMP
WHERE
    id = ?3
    AND user_id = ?4
    AND status = 'running'
`

type CompleteMarkingJobParams struct {
	ExamName      sql.NullString
	MarkTableName sql.NullString
	ID            int64
	UserID        int64
}

func (q *Queries) CompleteMarkingJob(ctx context.Context, arg CompleteMarkingJobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, completeMarkingJob,
		arg.ExamName,
		arg.MarkTableName,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createMarkingJob = `-- name: CreateMarkingJob :one
INSERT INTO
    marking_jobs (user_id)
VALUES
    (?1) RETURNING id
`

func (q *Queries) CreateMarkingJob(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, createMarkingJob, userID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteMarkingJob = `-- name: DeleteMarkingJob :execrows
DELETE FROM
    marking_jobs
WHERE
    id = ?1
    AND user_id = ?2
`

type DeleteMarkingJobParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteMarkingJob(ctx context.Context, arg DeleteMarkingJobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteMarkingJob, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const failMarkingJob = `-- name: FailMarkingJob :execrows
UPDATE
    marking_jobs
SET
    status = 'failed',
    completed_at = CURRENT_TIMESTAMP
WHERE
    id = ?1
    AND user_id = ?2
    AND status = 'running'
`

type FailMarkingJobParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) FailMarkingJob(ctx context.Context, arg FailMarkingJobParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, failMarkingJob, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getExamAndMarkName = `-- name: GetExamAndMarkName :one
SELECT
    exam_name,
    mark_table_name
FROM
    marking_jobs
WHERE
    id = ?1
    AND user_id = ?2
    AND status = 'success'
    AND status_pdf = 'success'
    AND exam_name IS NOT NULL
    AND mark_table_name IS NOT NULL
`

type GetExamAndMarkNameParams struct {
	ID     int64
	UserID int64
}

type GetExamAndMarkNameRow struct {
	ExamName      sql.NullString
	MarkTableName sql.NullString
}

func (q *Queries) GetExamAndMarkName(ctx context.Context, arg GetExamAndMarkNameParams) (GetExamAndMarkNameRow, error) {
	row := q.db.QueryRowContext(ctx, getExamAndMarkName, arg.ID, arg.UserID)
	var i GetExamAndMarkNameRow
	err := row.Scan(&i.ExamName, &i.MarkTableName)
	return i, err
}

const getMarkingProgress = `-- name: GetMarkingProgress :one
SELECT
    total_pages,
    done_pages,
    total_exams,
    done_exams
FROM
    marking_jobs
WHERE
    id = ?1
    AND user_id = ?2
`

type GetMarkingProgressParams struct {
	ID     int64
	UserID int64
}

type GetMarkingProgressRow struct {
	TotalPages sql.NullInt64
	DonePages  sql.NullInt64
	TotalExams sql.NullInt64
	DoneExams  sql.NullInt64
}

func (q *Queries) GetMarkingProgress(ctx context.Context, arg GetMarkingProgressParams) (GetMarkingProgressRow, error) {
	row := q.db.QueryRowContext(ctx, getMarkingProgress, arg.ID, arg.UserID)
	var i GetMarkingProgressRow
	err := row.Scan(
		&i.TotalPages,
		&i.DonePages,
		&i.TotalExams,
		&i.DoneExams,
	)
	return i, err
}

const getMarkingStatus = `-- name: GetMarkingStatus :one
SELECT
    status,
    status_pdf
FROM
    marking_jobs
WHERE
    id = ?1
    AND user_id = ?2
`

type GetMarkingStatusParams struct {
	ID     int64
	UserID int64
}

type GetMarkingStatusRow struct {
	Status    string
	StatusPdf string
}

func (q *Queries) GetMarkingStatus(ctx context.Context, arg GetMarkingStatusParams) (GetMarkingStatusRow, error) {
	row := q.db.QueryRowContext(ctx, getMarkingStatus, arg.ID, arg.UserID)
	var i GetMarkingStatusRow
	err := row.Scan(&i.Status, &i.StatusPdf)
	return i, err
}

const listExpiredMarkingJobs = `-- name: ListExpiredMarkingJobs :many
SELECT
    mj.id,
    mj.user_id,
    u.username
FROM marking_jobs AS mj
JOIN users AS u ON u.id = mj.user_id
WHERE mj.status IN ('success', 'failed')
  AND mj.completed_at IS NOT NULL
  AND unixepoch(mj.completed_at) < unixepoch(?1)
`

type ListExpiredMarkingJobsRow struct {
	ID       int64
	UserID   int64
	Username string
}

func (q *Queries) ListExpiredMarkingJobs(ctx context.Context, cutoff interface{}) ([]ListExpiredMarkingJobsRow, error) {
	rows, err := q.db.QueryContext(ctx, listExpiredMarkingJobs, cutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExpiredMarkingJobsRow
	for rows.Next() {
		var i ListExpiredMarkingJobsRow
		if err := rows.Scan(&i.ID, &i.UserID, &i.Username); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunningMarkingJobs = `-- name: ListRunningMarkingJobs :many
SELECT
    mj.id,
    mj.user_id,
    u.username
FROM marking_jobs AS mj
JOIN users AS u ON u.id = mj.user_id
WHERE mj.status = 'running'
`

type ListRunningMarkingJobsRow struct {
	ID       int64
	UserID   int64
	Username string
}

func (q *Queries) ListRunningMarkingJobs(ctx context.Context) ([]ListRunningMarkingJobsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRunningMarkingJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRunningMarkingJobsRow
	for rows.Next() {
		var i ListRunningMarkingJobsRow
		if err := rows.Scan(&i.ID, &i.UserID, &i.Username); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMarkingJobExamDone = `-- name: UpdateMarkingJobExamDone :execrows
UPDATE
    marking_jobs
SET
    done_exams = done_exams + 1
WHERE
    id = ?1
    AND user_id = ?2
    AND status = 'running'
    AND (total_exams IS NULL OR done_exams < total_exams)
`

type UpdateMarkingJobExamDoneParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) UpdateMarkingJobExamDone(ctx context.Context, arg UpdateMarkingJobExamDoneParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateMarkingJobExamDone, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateMarkingJobPageDone = `-- name: UpdateMarkingJobPageDone :execrows
UPDATE
    marking_jobs
SET
    done_pages = done_pages + 1
WHERE
    id = ?1
    AND user_id = ?2
    AND status = 'running'
    AND (total_pages IS NULL OR done_pages < total_pages)
`

type UpdateMarkingJobPageDoneParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) UpdateMarkingJobPageDone(ctx context.Context, arg UpdateMarkingJobPageDoneParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateMarkingJobPageDone, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateMarkingJobTotalExam = `-- name: UpdateMarkingJobTotalExam :execrows
UPDATE
    marking_jobs
SET
    total_exams = ?1
WHERE
    id = ?2
    AND user_id = ?3
    AND status = 'running'
`

type UpdateMarkingJobTotalExamParams struct {
	TotalExams sql.NullInt64
	ID         int64
	UserID     int64
}

func (q *Queries) UpdateMarkingJobTotalExam(ctx context.Context, arg UpdateMarkingJobTotalExamParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateMarkingJobTotalExam, arg.TotalExams, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateMarkingJobTotalPages = `-- name: UpdateMarkingJobTotalPages :execrows
UPDATE
    marking_jobs
SET
    total_pages = ?1
WHERE
    id = ?2
    AND user_id = ?3
    AND status = 'running'
`

type UpdateMarkingJobTotalPagesParams struct {
	TotalPages sql.NullInt64
	ID         int64
	UserID     int64
}

func (q *Queries) UpdateMarkingJobTotalPages(ctx context.Context, arg UpdateMarkingJobTotalPagesParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateMarkingJobTotalPages, arg.TotalPages, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
