// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: markingJobs.sql

package db

import (
	"context"
	"database/sql"
)

const completeMarkingJob = `-- name: CompleteMarkingJob :exec
UPDATE
    marking_jobs
SET
    status = 'success',
    status_pdf = 'success',
    exam_name = ?1,
    mark_table_name = ?2
WHERE
    id = ?3
    AND user_id = ?4
`

type CompleteMarkingJobParams struct {
	ExamName      sql.NullString
	MarkTableName sql.NullString
	ID            int64
	UserID        int64
}

func (q *Queries) CompleteMarkingJob(ctx context.Context, arg CompleteMarkingJobParams) error {
	_, err := q.db.ExecContext(ctx, completeMarkingJob,
		arg.ExamName,
		arg.MarkTableName,
		arg.ID,
		arg.UserID,
	)
	return err
}

const createMarkingJob = `-- name: CreateMarkingJob :one
INSERT INTO
    marking_jobs (user_id)
VALUES
    (?1) RETURNING id
`

func (q *Queries) CreateMarkingJob(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, createMarkingJob, userID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteMarkingJob = `-- name: DeleteMarkingJob :exec
DELETE FROM
    marking_jobs
WHERE
    id = ?1
    AND user_id = ?2
`

type DeleteMarkingJobParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteMarkingJob(ctx context.Context, arg DeleteMarkingJobParams) error {
	_, err := q.db.ExecContext(ctx, deleteMarkingJob, arg.ID, arg.UserID)
	return err
}

const getExamAndMarkName = `-- name: GetExamAndMarkName :one
SELECT
    exam_name,
    mark_table_name
FROM
    marking_jobs
WHERE
    id = ?1
    AND user_id = ?2
`

type GetExamAndMarkNameParams struct {
	ID     int64
	UserID int64
}

type GetExamAndMarkNameRow struct {
	ExamName      sql.NullString
	MarkTableName sql.NullString
}

func (q *Queries) GetExamAndMarkName(ctx context.Context, arg GetExamAndMarkNameParams) (GetExamAndMarkNameRow, error) {
	row := q.db.QueryRowContext(ctx, getExamAndMarkName, arg.ID, arg.UserID)
	var i GetExamAndMarkNameRow
	err := row.Scan(&i.ExamName, &i.MarkTableName)
	return i, err
}

const getMarkingProgress = `-- name: GetMarkingProgress :one
SELECT
    total_pages,
    done_pages,
    total_exams,
    done_exams
FROM
    marking_jobs
WHERE
    id = ?1
    AND user_id = ?2
`

type GetMarkingProgressParams struct {
	ID     int64
	UserID int64
}

type GetMarkingProgressRow struct {
	TotalPages sql.NullInt64
	DonePages  sql.NullInt64
	TotalExams sql.NullInt64
	DoneExams  sql.NullInt64
}

func (q *Queries) GetMarkingProgress(ctx context.Context, arg GetMarkingProgressParams) (GetMarkingProgressRow, error) {
	row := q.db.QueryRowContext(ctx, getMarkingProgress, arg.ID, arg.UserID)
	var i GetMarkingProgressRow
	err := row.Scan(
		&i.TotalPages,
		&i.DonePages,
		&i.TotalExams,
		&i.DoneExams,
	)
	return i, err
}

const getMarkingStatus = `-- name: GetMarkingStatus :one
SELECT
    status,
    status_pdf
FROM
    marking_jobs
WHERE
    id = ?1
    AND user_id = ?2
`

type GetMarkingStatusParams struct {
	ID     int64
	UserID int64
}

type GetMarkingStatusRow struct {
	Status    string
	StatusPdf string
}

func (q *Queries) GetMarkingStatus(ctx context.Context, arg GetMarkingStatusParams) (GetMarkingStatusRow, error) {
	row := q.db.QueryRowContext(ctx, getMarkingStatus, arg.ID, arg.UserID)
	var i GetMarkingStatusRow
	err := row.Scan(&i.Status, &i.StatusPdf)
	return i, err
}

const updateMarkingJobExamDone = `-- name: UpdateMarkingJobExamDone :exec
UPDATE
    marking_jobs
SET
    done_exams = done_exams + 1
WHERE
    id = ?1
    AND user_id = ?2
`

type UpdateMarkingJobExamDoneParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) UpdateMarkingJobExamDone(ctx context.Context, arg UpdateMarkingJobExamDoneParams) error {
	_, err := q.db.ExecContext(ctx, updateMarkingJobExamDone, arg.ID, arg.UserID)
	return err
}

const updateMarkingJobPageDone = `-- name: UpdateMarkingJobPageDone :exec
UPDATE
    marking_jobs
SET
    done_pages = done_pages + 1
WHERE
    id = ?1
    AND user_id = ?2
`

type UpdateMarkingJobPageDoneParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) UpdateMarkingJobPageDone(ctx context.Context, arg UpdateMarkingJobPageDoneParams) error {
	_, err := q.db.ExecContext(ctx, updateMarkingJobPageDone, arg.ID, arg.UserID)
	return err
}

const updateMarkingJobStatus = `-- name: UpdateMarkingJobStatus :exec
UPDATE
    marking_jobs
SET
    status = ?1
WHERE
    id = ?2
    AND user_id = ?3
`

type UpdateMarkingJobStatusParams struct {
	Status string
	ID     int64
	UserID int64
}

func (q *Queries) UpdateMarkingJobStatus(ctx context.Context, arg UpdateMarkingJobStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateMarkingJobStatus, arg.Status, arg.ID, arg.UserID)
	return err
}

const updateMarkingJobStatusPDF = `-- name: UpdateMarkingJobStatusPDF :exec
UPDATE
    marking_jobs
SET
    status_pdf = ?1,
    exam_name = ?2,
    mark_table_name = ?3
WHERE
    id = ?4
    AND user_id = ?5
`

type UpdateMarkingJobStatusPDFParams struct {
	StatusPdf     string
	ExamName      sql.NullString
	MarkTableName sql.NullString
	ID            int64
	UserID        int64
}

func (q *Queries) UpdateMarkingJobStatusPDF(ctx context.Context, arg UpdateMarkingJobStatusPDFParams) error {
	_, err := q.db.ExecContext(ctx, updateMarkingJobStatusPDF,
		arg.StatusPdf,
		arg.ExamName,
		arg.MarkTableName,
		arg.ID,
		arg.UserID,
	)
	return err
}

const updateMarkingJobTotalExam = `-- name: UpdateMarkingJobTotalExam :exec
UPDATE
    marking_jobs
SET
    total_exams = ?1
WHERE
    id = ?2
    AND user_id = ?3
`

type UpdateMarkingJobTotalExamParams struct {
	TotalExams sql.NullInt64
	ID         int64
	UserID     int64
}

func (q *Queries) UpdateMarkingJobTotalExam(ctx context.Context, arg UpdateMarkingJobTotalExamParams) error {
	_, err := q.db.ExecContext(ctx, updateMarkingJobTotalExam, arg.TotalExams, arg.ID, arg.UserID)
	return err
}

const updateMarkingJobTotalPages = `-- name: UpdateMarkingJobTotalPages :exec
UPDATE
    marking_jobs
SET
    total_pages = ?1
WHERE
    id = ?2
    AND user_id = ?3
`

type UpdateMarkingJobTotalPagesParams struct {
	TotalPages sql.NullInt64
	ID         int64
	UserID     int64
}

func (q *Queries) UpdateMarkingJobTotalPages(ctx context.Context, arg UpdateMarkingJobTotalPagesParams) error {
	_, err := q.db.ExecContext(ctx, updateMarkingJobTotalPages, arg.TotalPages, arg.ID, arg.UserID)
	return err
}
