// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: markingResults.sql

package db

import (
	"context"
	"database/sql"
)

const createMarkingAnswerDetection = `-- name: CreateMarkingAnswerDetection :one
INSERT INTO marking_answer_detections (
    question_result_id,
    answer_index,
    detected_state,
    mean_gray
)
VALUES (
    ?1,
    ?2,
    ?3,
    ?4
)
RETURNING id
`

type CreateMarkingAnswerDetectionParams struct {
	QuestionResultID int64
	AnswerIndex      int64
	DetectedState    int64
	MeanGray         float64
}

func (q *Queries) CreateMarkingAnswerDetection(ctx context.Context, arg CreateMarkingAnswerDetectionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createMarkingAnswerDetection,
		arg.QuestionResultID,
		arg.AnswerIndex,
		arg.DetectedState,
		arg.MeanGray,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createMarkingCopyResult = `-- name: CreateMarkingCopyResult :one
INSERT INTO marking_copy_results (
    user_id,
    marking_job_id,
    student_exam_id,
    outcome,
    expected_pages,
    detected_pages,
    score_half_units,
    total_points,
    failure_code,
    failure_detail
)
SELECT
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7,
    ?8,
    ?9,
    ?10
FROM marking_jobs AS mj
JOIN student_exam AS se
  ON se.exam_generated_id = mj.exam_generated_id
 AND se.user_id = mj.user_id
WHERE mj.id = ?2
  AND mj.user_id = ?1
  AND se.id = ?3
RETURNING id
`

type CreateMarkingCopyResultParams struct {
	UserID         int64
	MarkingJobID   int64
	StudentExamID  int64
	Outcome        string
	ExpectedPages  int64
	DetectedPages  int64
	ScoreHalfUnits sql.NullInt64
	TotalPoints    sql.NullInt64
	FailureCode    sql.NullString
	FailureDetail  sql.NullString
}

func (q *Queries) CreateMarkingCopyResult(ctx context.Context, arg CreateMarkingCopyResultParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createMarkingCopyResult,
		arg.UserID,
		arg.MarkingJobID,
		arg.StudentExamID,
		arg.Outcome,
		arg.ExpectedPages,
		arg.DetectedPages,
		arg.ScoreHalfUnits,
		arg.TotalPoints,
		arg.FailureCode,
		arg.FailureDetail,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createMarkingQuestionResult = `-- name: CreateMarkingQuestionResult :one
INSERT INTO marking_question_results (
    copy_result_id,
    question_index,
    state,
    score_half_units,
    total_points
)
VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5
)
RETURNING id
`

type CreateMarkingQuestionResultParams struct {
	CopyResultID   int64
	QuestionIndex  int64
	State          string
	ScoreHalfUnits int64
	TotalPoints    int64
}

func (q *Queries) CreateMarkingQuestionResult(ctx context.Context, arg CreateMarkingQuestionResultParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createMarkingQuestionResult,
		arg.CopyResultID,
		arg.QuestionIndex,
		arg.State,
		arg.ScoreHalfUnits,
		arg.TotalPoints,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getMarkingCopyResult = `-- name: GetMarkingCopyResult :one
SELECT id, user_id, marking_job_id, student_exam_id, outcome, expected_pages, detected_pages, score_half_units, total_points, failure_code, failure_detail, completed_at
FROM marking_copy_results
WHERE id = ?1 AND user_id = ?2
`

type GetMarkingCopyResultParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetMarkingCopyResult(ctx context.Context, arg GetMarkingCopyResultParams) (MarkingCopyResult, error) {
	row := q.db.QueryRowContext(ctx, getMarkingCopyResult, arg.ID, arg.UserID)
	var i MarkingCopyResult
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MarkingJobID,
		&i.StudentExamID,
		&i.Outcome,
		&i.ExpectedPages,
		&i.DetectedPages,
		&i.ScoreHalfUnits,
		&i.TotalPoints,
		&i.FailureCode,
		&i.FailureDetail,
		&i.CompletedAt,
	)
	return i, err
}

const getMarkingResultCoverage = `-- name: GetMarkingResultCoverage :one
SELECT
    (SELECT COUNT(*)
     FROM student_exam AS se
     WHERE se.exam_generated_id = mj.exam_generated_id
       AND se.user_id = mj.user_id) AS expected_count,
    (SELECT COUNT(*)
     FROM marking_copy_results AS mcr
     WHERE mcr.marking_job_id = mj.id
       AND mcr.user_id = mj.user_id) AS result_count
FROM marking_jobs AS mj
WHERE mj.id = ?1
  AND mj.user_id = ?2
`

type GetMarkingResultCoverageParams struct {
	MarkingJobID int64
	UserID       int64
}

type GetMarkingResultCoverageRow struct {
	ExpectedCount int64
	ResultCount   int64
}

func (q *Queries) GetMarkingResultCoverage(ctx context.Context, arg GetMarkingResultCoverageParams) (GetMarkingResultCoverageRow, error) {
	row := q.db.QueryRowContext(ctx, getMarkingResultCoverage, arg.MarkingJobID, arg.UserID)
	var i GetMarkingResultCoverageRow
	err := row.Scan(&i.ExpectedCount, &i.ResultCount)
	return i, err
}

const listExpectedStudentExamsForMarkingJob = `-- name: ListExpectedStudentExamsForMarkingJob :many
SELECT
    se.id AS student_exam_id,
    sec.page_tot AS expected_pages
FROM marking_jobs AS mj
JOIN student_exam AS se
  ON se.exam_generated_id = mj.exam_generated_id
 AND se.user_id = mj.user_id
JOIN student_exam_content AS sec
  ON sec.student_exam_id = se.id
 AND sec.user_id = se.user_id
WHERE mj.id = ?1
  AND mj.user_id = ?2
ORDER BY se.id
`

type ListExpectedStudentExamsForMarkingJobParams struct {
	MarkingJobID int64
	UserID       int64
}

type ListExpectedStudentExamsForMarkingJobRow struct {
	StudentExamID int64
	ExpectedPages int64
}

func (q *Queries) ListExpectedStudentExamsForMarkingJob(ctx context.Context, arg ListExpectedStudentExamsForMarkingJobParams) ([]ListExpectedStudentExamsForMarkingJobRow, error) {
	rows, err := q.db.QueryContext(ctx, listExpectedStudentExamsForMarkingJob, arg.MarkingJobID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExpectedStudentExamsForMarkingJobRow
	for rows.Next() {
		var i ListExpectedStudentExamsForMarkingJobRow
		if err := rows.Scan(&i.StudentExamID, &i.ExpectedPages); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMarkingAnswerDetections = `-- name: ListMarkingAnswerDetections :many
SELECT mad.id, mad.question_result_id, mad.answer_index, mad.detected_state, mad.mean_gray
FROM marking_answer_detections AS mad
JOIN marking_question_results AS mqr ON mqr.id = mad.question_result_id
JOIN marking_copy_results AS mcr ON mcr.id = mqr.copy_result_id
WHERE mad.question_result_id = ?1
  AND mcr.user_id = ?2
ORDER BY mad.answer_index
`

type ListMarkingAnswerDetectionsParams struct {
	QuestionResultID int64
	UserID           int64
}

func (q *Queries) ListMarkingAnswerDetections(ctx context.Context, arg ListMarkingAnswerDetectionsParams) ([]MarkingAnswerDetection, error) {
	rows, err := q.db.QueryContext(ctx, listMarkingAnswerDetections, arg.QuestionResultID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MarkingAnswerDetection
	for rows.Next() {
		var i MarkingAnswerDetection
		if err := rows.Scan(
			&i.ID,
			&i.QuestionResultID,
			&i.AnswerIndex,
			&i.DetectedState,
			&i.MeanGray,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMarkingQuestionResults = `-- name: ListMarkingQuestionResults :many
SELECT mqr.id, mqr.copy_result_id, mqr.question_index, mqr.state, mqr.score_half_units, mqr.total_points
FROM marking_question_results AS mqr
JOIN marking_copy_results AS mcr ON mcr.id = mqr.copy_result_id
WHERE mqr.copy_result_id = ?1
  AND mcr.user_id = ?2
ORDER BY mqr.question_index
`

type ListMarkingQuestionResultsParams struct {
	CopyResultID int64
	UserID       int64
}

func (q *Queries) ListMarkingQuestionResults(ctx context.Context, arg ListMarkingQuestionResultsParams) ([]MarkingQuestionResult, error) {
	rows, err := q.db.QueryContext(ctx, listMarkingQuestionResults, arg.CopyResultID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MarkingQuestionResult
	for rows.Next() {
		var i MarkingQuestionResult
		if err := rows.Scan(
			&i.ID,
			&i.CopyResultID,
			&i.QuestionIndex,
			&i.State,
			&i.ScoreHalfUnits,
			&i.TotalPoints,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
