// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: markingReviews.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createMarkingAlignedPage = `-- name: CreateMarkingAlignedPage :one
INSERT INTO marking_aligned_pages (
    user_id,
    copy_result_id,
    page_exam,
    storage_key,
    width,
    height,
    sha256
)
SELECT
    ?1,
    mcr.id,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6
FROM marking_copy_results AS mcr
JOIN marking_jobs AS mj
  ON mj.id = mcr.marking_job_id
 AND mj.user_id = mcr.user_id
WHERE mcr.id = ?7
  AND mcr.user_id = ?1
  AND mj.user_id = ?1
  AND mcr.outcome = 'corrected'
  AND ?3 = printf(
      'aligned/student-exam-%d/page-%d.png',
      mcr.student_exam_id,
      ?2
  )
  AND (SELECT COUNT(*)
       FROM student_exam_page_content AS sep
       WHERE sep.student_exam_id = mcr.student_exam_id
         AND sep.user_id = mcr.user_id
         AND sep.page = ?2) = 1
RETURNING id
`

type CreateMarkingAlignedPageParams struct {
	UserID       int64
	PageExam     int64
	StorageKey   string
	Width        int64
	Height       int64
	Sha256       string
	CopyResultID int64
}

func (q *Queries) CreateMarkingAlignedPage(ctx context.Context, arg CreateMarkingAlignedPageParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createMarkingAlignedPage,
		arg.UserID,
		arg.PageExam,
		arg.StorageKey,
		arg.Width,
		arg.Height,
		arg.Sha256,
		arg.CopyResultID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createMarkingAnswerReview = `-- name: CreateMarkingAnswerReview :one
INSERT INTO marking_answer_reviews (
    answer_detection_id,
    reviewer_user_id,
    reviewed_state
)
SELECT
    mad.id,
    ?1,
    ?2
FROM marking_answer_detections AS mad
JOIN marking_question_results AS mqr ON mqr.id = mad.question_result_id
JOIN marking_copy_results AS mcr ON mcr.id = mqr.copy_result_id
JOIN marking_jobs AS mj
  ON mj.id = mcr.marking_job_id
 AND mj.user_id = mcr.user_id
WHERE mad.id = ?3
  AND mj.user_id = ?1
RETURNING id
`

type CreateMarkingAnswerReviewParams struct {
	ReviewerUserID    int64
	ReviewedState     int64
	AnswerDetectionID int64
}

func (q *Queries) CreateMarkingAnswerReview(ctx context.Context, arg CreateMarkingAnswerReviewParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createMarkingAnswerReview, arg.ReviewerUserID, arg.ReviewedState, arg.AnswerDetectionID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getEffectiveAnswerDetection = `-- name: GetEffectiveAnswerDetection :one
SELECT
    mad.id,
    mad.detected_state,
    mad.mean_gray,
    mar.reviewed_state,
    COALESCE(mar.reviewed_state, mad.detected_state) AS effective_state,
    mar.reviewed_at,
    mar.revision
FROM marking_answer_detections AS mad
JOIN marking_question_results AS mqr ON mqr.id = mad.question_result_id
JOIN marking_copy_results AS mcr ON mcr.id = mqr.copy_result_id
JOIN marking_jobs AS mj
  ON mj.id = mcr.marking_job_id
 AND mj.user_id = mcr.user_id
LEFT JOIN marking_answer_reviews AS mar ON mar.answer_detection_id = mad.id
WHERE mad.id = ?1
  AND mj.user_id = ?2
`

type GetEffectiveAnswerDetectionParams struct {
	AnswerDetectionID int64
	UserID            int64
}

type GetEffectiveAnswerDetectionRow struct {
	ID             int64
	DetectedState  int64
	MeanGray       float64
	ReviewedState  sql.NullInt64
	EffectiveState int64
	ReviewedAt     sql.NullTime
	Revision       sql.NullInt64
}

func (q *Queries) GetEffectiveAnswerDetection(ctx context.Context, arg GetEffectiveAnswerDetectionParams) (GetEffectiveAnswerDetectionRow, error) {
	row := q.db.QueryRowContext(ctx, getEffectiveAnswerDetection, arg.AnswerDetectionID, arg.UserID)
	var i GetEffectiveAnswerDetectionRow
	err := row.Scan(
		&i.ID,
		&i.DetectedState,
		&i.MeanGray,
		&i.ReviewedState,
		&i.EffectiveState,
		&i.ReviewedAt,
		&i.Revision,
	)
	return i, err
}

const getMarkingAlignedPage = `-- name: GetMarkingAlignedPage :one
SELECT
    map.id,
    map.user_id,
    map.copy_result_id,
    map.page_exam,
    map.storage_key,
    map.width,
    map.height,
    map.sha256,
    map.created_at,
    mcr.student_exam_id,
    mcr.marking_job_id,
    u.username
FROM marking_aligned_pages AS map
JOIN marking_copy_results AS mcr ON mcr.id = map.copy_result_id
JOIN marking_jobs AS mj
  ON mj.id = mcr.marking_job_id
 AND mj.user_id = mcr.user_id
JOIN users AS u ON u.id = mj.user_id
WHERE map.copy_result_id = ?1
  AND map.page_exam = ?2
  AND mj.user_id = ?3
`

type GetMarkingAlignedPageParams struct {
	CopyResultID int64
	PageExam     int64
	UserID       int64
}

type GetMarkingAlignedPageRow struct {
	ID            int64
	UserID        int64
	CopyResultID  int64
	PageExam      int64
	StorageKey    string
	Width         int64
	Height        int64
	Sha256        string
	CreatedAt     time.Time
	StudentExamID int64
	MarkingJobID  int64
	Username      string
}

func (q *Queries) GetMarkingAlignedPage(ctx context.Context, arg GetMarkingAlignedPageParams) (GetMarkingAlignedPageRow, error) {
	row := q.db.QueryRowContext(ctx, getMarkingAlignedPage, arg.CopyResultID, arg.PageExam, arg.UserID)
	var i GetMarkingAlignedPageRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CopyResultID,
		&i.PageExam,
		&i.StorageKey,
		&i.Width,
		&i.Height,
		&i.Sha256,
		&i.CreatedAt,
		&i.StudentExamID,
		&i.MarkingJobID,
		&i.Username,
	)
	return i, err
}

const getMarkingAnswerReview = `-- name: GetMarkingAnswerReview :one
SELECT mar.id, mar.answer_detection_id, mar.reviewer_user_id, mar.reviewed_state, mar.reviewed_at, mar.revision
FROM marking_answer_reviews AS mar
JOIN marking_answer_detections AS mad ON mad.id = mar.answer_detection_id
JOIN marking_question_results AS mqr ON mqr.id = mad.question_result_id
JOIN marking_copy_results AS mcr ON mcr.id = mqr.copy_result_id
JOIN marking_jobs AS mj
  ON mj.id = mcr.marking_job_id
 AND mj.user_id = mcr.user_id
WHERE mar.answer_detection_id = ?1
  AND mj.user_id = ?2
`

type GetMarkingAnswerReviewParams struct {
	AnswerDetectionID int64
	UserID            int64
}

func (q *Queries) GetMarkingAnswerReview(ctx context.Context, arg GetMarkingAnswerReviewParams) (MarkingAnswerReview, error) {
	row := q.db.QueryRowContext(ctx, getMarkingAnswerReview, arg.AnswerDetectionID, arg.UserID)
	var i MarkingAnswerReview
	err := row.Scan(
		&i.ID,
		&i.AnswerDetectionID,
		&i.ReviewerUserID,
		&i.ReviewedState,
		&i.ReviewedAt,
		&i.Revision,
	)
	return i, err
}

const updateMarkingAnswerReview = `-- name: UpdateMarkingAnswerReview :execrows
UPDATE marking_answer_reviews
SET
    reviewed_state = ?1,
    reviewed_at = CURRENT_TIMESTAMP,
    revision = revision + 1
WHERE answer_detection_id = ?2
  AND reviewer_user_id = ?3
  AND revision = ?4
  AND EXISTS (
      SELECT 1
      FROM marking_answer_detections AS mad
      JOIN marking_question_results AS mqr ON mqr.id = mad.question_result_id
      JOIN marking_copy_results AS mcr ON mcr.id = mqr.copy_result_id
      JOIN marking_jobs AS mj
        ON mj.id = mcr.marking_job_id
       AND mj.user_id = mcr.user_id
      WHERE mad.id = marking_answer_reviews.answer_detection_id
        AND mj.user_id = ?3
  )
`

type UpdateMarkingAnswerReviewParams struct {
	ReviewedState     int64
	AnswerDetectionID int64
	ReviewerUserID    int64
	ExpectedRevision  int64
}

func (q *Queries) UpdateMarkingAnswerReview(ctx context.Context, arg UpdateMarkingAnswerReviewParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateMarkingAnswerReview,
		arg.ReviewedState,
		arg.AnswerDetectionID,
		arg.ReviewerUserID,
		arg.ExpectedRevision,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const validateMarkingAlignedPageTarget = `-- name: ValidateMarkingAlignedPageTarget :one
SELECT mcr.id
FROM marking_copy_results AS mcr
JOIN marking_jobs AS mj
  ON mj.id = mcr.marking_job_id
 AND mj.user_id = mcr.user_id
WHERE mcr.id = ?1
  AND mcr.marking_job_id = ?2
  AND mcr.student_exam_id = ?3
  AND mcr.user_id = ?4
  AND mcr.outcome = 'corrected'
  AND (SELECT COUNT(*)
       FROM student_exam_page_content AS sep
       WHERE sep.student_exam_id = mcr.student_exam_id
         AND sep.user_id = mcr.user_id
         AND sep.page = ?5) = 1
`

type ValidateMarkingAlignedPageTargetParams struct {
	CopyResultID  int64
	MarkingJobID  int64
	StudentExamID int64
	UserID        int64
	PageExam      int64
}

func (q *Queries) ValidateMarkingAlignedPageTarget(ctx context.Context, arg ValidateMarkingAlignedPageTargetParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, validateMarkingAlignedPageTarget,
		arg.CopyResultID,
		arg.MarkingJobID,
		arg.StudentExamID,
		arg.UserID,
		arg.PageExam,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
