// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type AltAnswer struct {
	ID            int64
	AltQuestionID int64
	State         int64
	Content       string
	UserID        int64
}

type AltImage struct {
	ID               int64
	AltQuestionID    int64
	ImageName        string
	ResizePercentage int64
	UserID           int64
}

type AltQuestion struct {
	ID         int64
	QuestionID int64
	Content    string
	UserID     int64
}

type Answer struct {
	ID         int64
	QuestionID int64
	State      int64
	Content    string
	UserID     int64
}

type ClassCode struct {
	ID     int64
	Name   string
	UserID int64
}

type Difficulty struct {
	ID     int64
	Name   string
	UserID int64
}

type Exam struct {
	ID          int64
	Name        string
	QcmID       int64
	ClassCodeID int64
	PeriodID    int64
	YearID      int64
	UserID      int64
}

type ExamsGenerated struct {
	ID                int64
	ExamID            int64
	ProcessedStudents int64
	TotalStudents     int64
	CreatedAt         sql.NullTime
	Status            string
	UserID            int64
}

type Image struct {
	ID               int64
	QuestionID       int64
	ImageName        string
	ResizePercentage int64
	UserID           int64
}

type MarkingAlignedPage struct {
	ID           int64
	UserID       int64
	CopyResultID int64
	PageExam     int64
	StorageKey   string
	Width        int64
	Height       int64
	Sha256       string
	CreatedAt    time.Time
}

type MarkingAnswerDetection struct {
	ID               int64
	QuestionResultID int64
	AnswerIndex      int64
	DetectedState    int64
	MeanGray         float64
	HistoricalState  sql.NullInt64
	V2State          sql.NullInt64
	DarkRatio        sql.NullFloat64
	ChromaRatio      sql.NullFloat64
	GrayscaleSignal  sql.NullInt64
	ColorSignal      sql.NullInt64
	AutomaticState   sql.NullInt64
	ReviewReason     sql.NullString
}

type MarkingAnswerReview struct {
	ID                int64
	AnswerDetectionID int64
	ReviewerUserID    int64
	ReviewedState     int64
	ReviewedAt        time.Time
	Revision          int64
}

type MarkingCopyResult struct {
	ID             int64
	UserID         int64
	MarkingJobID   int64
	StudentExamID  int64
	Outcome        string
	ExpectedPages  int64
	DetectedPages  int64
	ScoreHalfUnits sql.NullInt64
	TotalPoints    sql.NullInt64
	FailureCode    sql.NullString
	FailureDetail  sql.NullString
	CompletedAt    time.Time
}

type MarkingJob struct {
	ID                      int64
	UserID                  int64
	TotalPages              sql.NullInt64
	DonePages               sql.NullInt64
	TotalExams              sql.NullInt64
	DoneExams               sql.NullInt64
	Status                  string
	StatusPdf               string
	ExamName                sql.NullString
	MarkTableName           sql.NullString
	CompletedAt             sql.NullTime
	ExamGeneratedID         sql.NullInt64
	ResultSchemaVersion     sql.NullInt64
	MarkingAlgorithmVersion sql.NullString
	DetectionThreshold      sql.NullFloat64
	AmbiguityDelta          sql.NullFloat64
	ReviewRevision          int64
	ArtifactsRevision       int64
	ReviewPolicyVersion     sql.NullString
	V2RoiRadiusRatio        sql.NullFloat64
	V2DarkPixelThreshold    sql.NullFloat64
	V2DarkRatioThreshold    sql.NullFloat64
	V2ChromaPixelThreshold  sql.NullFloat64
	V2ChromaRatioThreshold  sql.NullFloat64
}

type MarkingQuestionResult struct {
	ID             int64
	CopyResultID   int64
	QuestionIndex  int64
	State          string
	ScoreHalfUnits int64
	TotalPoints    int64
}

type PasswordReset struct {
	ID        int64
	UserID    int64
	Token     string
	ExpiresAt time.Time
	Used      sql.NullBool
}

type Period struct {
	ID     int64
	Name   string
	UserID int64
}

type Point struct {
	ID         int64
	PointValue int64
	UserID     int64
}

type Qcm struct {
	ID     int64
	Name   string
	UserID int64
}

type QcmQuestion struct {
	ID         int64
	QcmID      int64
	QuestionID int64
	UserID     int64
	Position   int64
}

type Question struct {
	ID           int64
	SubjectID    int64
	ThemeID      int64
	YearLevelID  int64
	SkillID      int64
	DifficultyID int64
	PointID      int64
	Content      string
	UserID       int64
}

type Skill struct {
	ID     int64
	Name   string
	UserID int64
}

type Student struct {
	ID        int64
	FirstName string
	LastName  string
	UserID    int64
}

type StudentClassCode struct {
	ID          int64
	StudentID   int64
	ClassCodeID int64
	UserID      int64
}

type StudentExam struct {
	ID              int64
	ExamGeneratedID int64
	StudentID       int64
	UserID          int64
}

type StudentExamContent struct {
	ID            int64
	StudentExamID int64
	PageTot       int64
	Content       string
	UserID        int64
}

type StudentExamPageContent struct {
	ID                  int64
	StudentExamID       int64
	Page                int64
	Content             string
	UserID              int64
	ReferenceStorageKey sql.NullString
	ReferenceWidth      sql.NullInt64
	ReferenceHeight     sql.NullInt64
	ReferenceDpi        sql.NullInt64
	ReferenceSha256     sql.NullString
}

type Subject struct {
	ID     int64
	Name   string
	UserID int64
}

type Theme struct {
	ID     int64
	Name   string
	UserID int64
}

type User struct {
	ID           int64
	Username     string
	Email        string
	Hashpassword string
}

type Year struct {
	ID     int64
	Name   string
	UserID int64
}

type YearLevel struct {
	ID     int64
	Name   string
	UserID int64
}
