// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type AltAnswer struct {
	ID            int64
	AltQuestionID int64
	State         int64
	Content       string
	UserID        int64
}

type AltImage struct {
	ID               int64
	AltQuestionID    int64
	ImageName        string
	ResizePercentage int64
	UserID           int64
}

type AltQuestion struct {
	ID         int64
	QuestionID int64
	Content    string
	UserID     int64
}

type Answer struct {
	ID         int64
	QuestionID int64
	State      int64
	Content    string
	UserID     int64
}

type ClassCode struct {
	ID     int64
	Name   string
	UserID int64
}

type Difficulty struct {
	ID     int64
	Name   string
	UserID int64
}

type Exam struct {
	ID          int64
	Name        string
	QcmID       int64
	ClassCodeID int64
	PeriodID    int64
	YearID      int64
	UserID      int64
}

type ExamsGenerated struct {
	ID                int64
	ExamID            int64
	ProcessedStudents int64
	TotalStudents     int64
	CreatedAt         sql.NullTime
	Status            string
	UserID            int64
}

type Image struct {
	ID               int64
	QuestionID       int64
	ImageName        string
	ResizePercentage int64
	UserID           int64
}

type MarkingJob struct {
	ID            int64
	UserID        int64
	TotalPages    sql.NullInt64
	DonePages     sql.NullInt64
	TotalExams    sql.NullInt64
	DoneExams     sql.NullInt64
	Status        string
	StatusPdf     string
	ExamName      sql.NullString
	MarkTableName sql.NullString
}

type PasswordReset struct {
	ID        int64
	UserID    int64
	Token     string
	ExpiresAt time.Time
	Used      sql.NullBool
}

type Period struct {
	ID     int64
	Name   string
	UserID int64
}

type Point struct {
	ID         int64
	PointValue int64
	UserID     int64
}

type Qcm struct {
	ID     int64
	Name   string
	UserID int64
}

type QcmQuestion struct {
	ID         int64
	QcmID      int64
	QuestionID int64
	UserID     int64
}

type Question struct {
	ID           int64
	SubjectID    int64
	ThemeID      int64
	YearLevelID  int64
	SkillID      int64
	DifficultyID int64
	PointID      int64
	Content      string
	UserID       int64
}

type Skill struct {
	ID     int64
	Name   string
	UserID int64
}

type Student struct {
	ID        int64
	FirstName string
	LastName  string
	UserID    int64
}

type StudentClassCode struct {
	ID          int64
	StudentID   int64
	ClassCodeID int64
	UserID      int64
}

type StudentExam struct {
	ID              int64
	ExamGeneratedID int64
	StudentID       int64
	UserID          int64
}

type StudentExamContent struct {
	ID            int64
	StudentExamID int64
	PageTot       int64
	Content       string
	UserID        int64
}

type StudentExamPageContent struct {
	ID            int64
	StudentExamID int64
	Page          int64
	Content       string
	UserID        int64
}

type Subject struct {
	ID     int64
	Name   string
	UserID int64
}

type Theme struct {
	ID     int64
	Name   string
	UserID int64
}

type User struct {
	ID           int64
	Username     string
	Email        string
	Hashpassword string
}

type Year struct {
	ID     int64
	Name   string
	UserID int64
}

type YearLevel struct {
	ID     int64
	Name   string
	UserID int64
}
