// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: periods.sql

package db

import (
	"context"
)

const createPeriod = `-- name: CreatePeriod :exec
INSERT INTO
    periods (name, user_id)
VALUES
    (?1, ?2)
`

type CreatePeriodParams struct {
	Name   string
	UserID int64
}

func (q *Queries) CreatePeriod(ctx context.Context, arg CreatePeriodParams) error {
	_, err := q.db.ExecContext(ctx, createPeriod, arg.Name, arg.UserID)
	return err
}

const deletePeriod = `-- name: DeletePeriod :execrows
DELETE FROM
    periods
WHERE
    id = ?1
    AND user_id = ?2
`

type DeletePeriodParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeletePeriod(ctx context.Context, arg DeletePeriodParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePeriod, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAllPeriods = `-- name: GetAllPeriods :many
SELECT
    id, name, user_id
FROM
    periods
WHERE
    user_id = ?1
ORDER BY
    name
`

func (q *Queries) GetAllPeriods(ctx context.Context, userID int64) ([]Period, error) {
	rows, err := q.db.QueryContext(ctx, getAllPeriods, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Period
	for rows.Next() {
		var i Period
		if err := rows.Scan(&i.ID, &i.Name, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPeriodNameByID = `-- name: GetPeriodNameByID :one
SELECT
    name
FROM
    periods
WHERE
    id = ?1
    AND user_id = ?2
`

type GetPeriodNameByIDParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetPeriodNameByID(ctx context.Context, arg GetPeriodNameByIDParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getPeriodNameByID, arg.ID, arg.UserID)
	var name string
	err := row.Scan(&name)
	return name, err
}

const updatePeriod = `-- name: UpdatePeriod :execrows
UPDATE
    periods
SET
    name = ?1
WHERE
    id = ?2
    AND user_id = ?3
`

type UpdatePeriodParams struct {
	Name   string
	ID     int64
	UserID int64
}

func (q *Queries) UpdatePeriod(ctx context.Context, arg UpdatePeriodParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updatePeriod, arg.Name, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
