// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: points.sql

package db

import (
	"context"
)

const createPoint = `-- name: CreatePoint :exec
INSERT INTO
    points (point_value, user_id)
VALUES
    (?1, ?2)
`

type CreatePointParams struct {
	PointValue int64
	UserID     int64
}

func (q *Queries) CreatePoint(ctx context.Context, arg CreatePointParams) error {
	_, err := q.db.ExecContext(ctx, createPoint, arg.PointValue, arg.UserID)
	return err
}

const deletePoint = `-- name: DeletePoint :exec
DELETE FROM
    points
WHERE
    id = ?1
    AND user_id = ?2
`

type DeletePointParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeletePoint(ctx context.Context, arg DeletePointParams) error {
	_, err := q.db.ExecContext(ctx, deletePoint, arg.ID, arg.UserID)
	return err
}

const getAllPoints = `-- name: GetAllPoints :many
SELECT
    id, point_value, user_id
FROM
    points
WHERE
    user_id = ?1
ORDER BY
    point_value ASC
`

func (q *Queries) GetAllPoints(ctx context.Context, userID int64) ([]Point, error) {
	rows, err := q.db.QueryContext(ctx, getAllPoints, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Point
	for rows.Next() {
		var i Point
		if err := rows.Scan(&i.ID, &i.PointValue, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePoint = `-- name: UpdatePoint :exec
UPDATE
    points
SET
    point_value = ?1
WHERE
    id = ?2
    AND user_id = ?3
`

type UpdatePointParams struct {
	PointValue int64
	ID         int64
	UserID     int64
}

func (q *Queries) UpdatePoint(ctx context.Context, arg UpdatePointParams) error {
	_, err := q.db.ExecContext(ctx, updatePoint, arg.PointValue, arg.ID, arg.UserID)
	return err
}
