// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: qcm.sql

package db

import (
	"context"
)

const createQCM = `-- name: CreateQCM :exec
INSERT INTO
    qcm (name, user_id)
VALUES
    (?1, ?2)
`

type CreateQCMParams struct {
	Name   string
	UserID int64
}

func (q *Queries) CreateQCM(ctx context.Context, arg CreateQCMParams) error {
	_, err := q.db.ExecContext(ctx, createQCM, arg.Name, arg.UserID)
	return err
}

const deleteQCM = `-- name: DeleteQCM :execrows
DELETE FROM
   qcm 
WHERE
    id = ?1
    AND user_id = ?2
`

type DeleteQCMParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteQCM(ctx context.Context, arg DeleteQCMParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteQCM, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAllQCM = `-- name: GetAllQCM :many
SELECT
    qcm.id,
    qcm.name,
    qcm.user_id,
    COUNT(qcm_questions.id) AS question_count
FROM
   qcm
LEFT JOIN qcm_questions
    ON qcm_questions.qcm_id = qcm.id
    AND qcm_questions.user_id = qcm.user_id
WHERE
    qcm.user_id = ?1
GROUP BY
    qcm.id,
    qcm.name,
    qcm.user_id
ORDER BY
    qcm.id DESC
`

type GetAllQCMRow struct {
	ID            int64
	Name          string
	UserID        int64
	QuestionCount int64
}

func (q *Queries) GetAllQCM(ctx context.Context, userID int64) ([]GetAllQCMRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllQCM, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllQCMRow
	for rows.Next() {
		var i GetAllQCMRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.UserID,
			&i.QuestionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getQCMNameByID = `-- name: GetQCMNameByID :one
SELECT
    name
FROM
   qcm 
WHERE
    id = ?1
    AND user_id = ?2
`

type GetQCMNameByIDParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetQCMNameByID(ctx context.Context, arg GetQCMNameByIDParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getQCMNameByID, arg.ID, arg.UserID)
	var name string
	err := row.Scan(&name)
	return name, err
}

const updateQCM = `-- name: UpdateQCM :execrows
UPDATE
   qcm 
SET
    name = ?1
WHERE
    id = ?2
    AND user_id = ?3
`

type UpdateQCMParams struct {
	Name   string
	ID     int64
	UserID int64
}

func (q *Queries) UpdateQCM(ctx context.Context, arg UpdateQCMParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateQCM, arg.Name, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
