// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: qcm.sql

package db

import (
	"context"
)

const createQCM = `-- name: CreateQCM :exec
INSERT INTO
    qcm (name, user_id)
VALUES
    (?1, ?2)
`

type CreateQCMParams struct {
	Name   string
	UserID int64
}

func (q *Queries) CreateQCM(ctx context.Context, arg CreateQCMParams) error {
	_, err := q.db.ExecContext(ctx, createQCM, arg.Name, arg.UserID)
	return err
}

const deleteQCM = `-- name: DeleteQCM :exec
DELETE FROM
   qcm 
WHERE
    id = ?1
    AND user_id = ?2
`

type DeleteQCMParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteQCM(ctx context.Context, arg DeleteQCMParams) error {
	_, err := q.db.ExecContext(ctx, deleteQCM, arg.ID, arg.UserID)
	return err
}

const getAllQCM = `-- name: GetAllQCM :many
SELECT
    id, name, user_id
FROM
   qcm 
WHERE
    user_id = ?1
ORDER BY
    id DESC
`

func (q *Queries) GetAllQCM(ctx context.Context, userID int64) ([]Qcm, error) {
	rows, err := q.db.QueryContext(ctx, getAllQCM, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Qcm
	for rows.Next() {
		var i Qcm
		if err := rows.Scan(&i.ID, &i.Name, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getQCMNameByID = `-- name: GetQCMNameByID :one
SELECT
    name
FROM
   qcm 
WHERE
    id = ?1
    AND user_id = ?2
`

type GetQCMNameByIDParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetQCMNameByID(ctx context.Context, arg GetQCMNameByIDParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getQCMNameByID, arg.ID, arg.UserID)
	var name string
	err := row.Scan(&name)
	return name, err
}

const updateQCM = `-- name: UpdateQCM :exec
UPDATE
   qcm 
SET
    name = ?1
WHERE
    id = ?2
    AND user_id = ?3
`

type UpdateQCMParams struct {
	Name   string
	ID     int64
	UserID int64
}

func (q *Queries) UpdateQCM(ctx context.Context, arg UpdateQCMParams) error {
	_, err := q.db.ExecContext(ctx, updateQCM, arg.Name, arg.ID, arg.UserID)
	return err
}
