// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: qcmquestion.sql

package db

import (
	"context"
)

const compactQCMQuestionPositions = `-- name: CompactQCMQuestionPositions :execrows
UPDATE qcm_questions
SET position = qcm_questions.position - ?1 - 1
WHERE qcm_questions.qcm_id = ?2
  AND qcm_questions.user_id = ?3
  AND qcm_questions.position > ?1
  AND EXISTS (
      SELECT 1 FROM qcm q
      WHERE q.id = ?2 AND q.user_id = ?3
  )
`

type CompactQCMQuestionPositionsParams struct {
	MaxPosition int64
	QcmID       int64
	UserID      int64
}

func (q *Queries) CompactQCMQuestionPositions(ctx context.Context, arg CompactQCMQuestionPositionsParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, compactQCMQuestionPositions, arg.MaxPosition, arg.QcmID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createQCMQuestion = `-- name: CreateQCMQuestion :execrows
INSERT INTO qcm_questions (qcm_id, question_id, user_id, position)
SELECT
    ?1,
    ?2,
    ?3,
    COALESCE((
        SELECT MAX(position)
        FROM qcm_questions
        WHERE qcm_id = ?1
    ), 0) + 1
WHERE EXISTS (
    SELECT 1 FROM qcm
    WHERE id = ?1 AND user_id = ?3
)
AND EXISTS (
    SELECT 1 FROM questions
    WHERE id = ?2 AND user_id = ?3
)
`

type CreateQCMQuestionParams struct {
	QcmID      int64
	QuestionID int64
	UserID     int64
}

func (q *Queries) CreateQCMQuestion(ctx context.Context, arg CreateQCMQuestionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createQCMQuestion, arg.QcmID, arg.QuestionID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteQCMQuestion = `-- name: DeleteQCMQuestion :execrows
DELETE FROM
   qcm_questions 
WHERE
    qcm_questions.id = ?1
    AND qcm_questions.qcm_id = ?2
    AND qcm_questions.user_id = ?3
    AND EXISTS (
        SELECT 1 FROM qcm
        WHERE id = ?2 AND user_id = ?3
    )
`

type DeleteQCMQuestionParams struct {
	ID     int64
	QcmID  int64
	UserID int64
}

func (q *Queries) DeleteQCMQuestion(ctx context.Context, arg DeleteQCMQuestionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteQCMQuestion, arg.ID, arg.QcmID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAllQuestionsByQCMID = `-- name: GetAllQuestionsByQCMID :many
SELECT
    questions.id         AS question_id,
    questions.content    AS question_content,
    qcm_questions.id     AS qcm_question_id,
    qcm_questions.position
FROM questions
JOIN qcm_questions 
    ON qcm_questions.question_id = questions.id
WHERE questions.user_id = ?1
  AND qcm_questions.user_id = ?1
  AND qcm_questions.qcm_id = ?2
  AND EXISTS (
      SELECT 1 FROM qcm
      WHERE id = ?2 AND user_id = ?1
  )
ORDER BY qcm_questions.position ASC
`

type GetAllQuestionsByQCMIDParams struct {
	UserID int64
	QcmID  int64
}

type GetAllQuestionsByQCMIDRow struct {
	QuestionID      int64
	QuestionContent string
	QcmQuestionID   int64
	Position        int64
}

func (q *Queries) GetAllQuestionsByQCMID(ctx context.Context, arg GetAllQuestionsByQCMIDParams) ([]GetAllQuestionsByQCMIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllQuestionsByQCMID, arg.UserID, arg.QcmID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllQuestionsByQCMIDRow
	for rows.Next() {
		var i GetAllQuestionsByQCMIDRow
		if err := rows.Scan(
			&i.QuestionID,
			&i.QuestionContent,
			&i.QcmQuestionID,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getQCMQuestionPosition = `-- name: GetQCMQuestionPosition :one
SELECT
    qcm_questions.position,
    (
        SELECT sibling.position
        FROM qcm_questions sibling
        WHERE sibling.qcm_id = ?1
          AND sibling.user_id = ?2
        ORDER BY sibling.position DESC
        LIMIT 1
    ) AS max_position
FROM qcm_questions
WHERE qcm_questions.id = ?3
  AND qcm_questions.qcm_id = ?1
  AND qcm_questions.user_id = ?2
  AND EXISTS (
      SELECT 1 FROM qcm
      WHERE id = ?1 AND user_id = ?2
  )
`

type GetQCMQuestionPositionParams struct {
	QcmID  int64
	UserID int64
	ID     int64
}

type GetQCMQuestionPositionRow struct {
	Position    int64
	MaxPosition int64
}

func (q *Queries) GetQCMQuestionPosition(ctx context.Context, arg GetQCMQuestionPositionParams) (GetQCMQuestionPositionRow, error) {
	row := q.db.QueryRowContext(ctx, getQCMQuestionPosition, arg.QcmID, arg.UserID, arg.ID)
	var i GetQCMQuestionPositionRow
	err := row.Scan(&i.Position, &i.MaxPosition)
	return i, err
}

const getQCMQuestionsIDs = `-- name: GetQCMQuestionsIDs :many
SELECT question_id
FROM qcm_questions
WHERE qcm_questions.user_id = ?1
  AND qcm_id = ?2
  AND EXISTS (
      SELECT 1 FROM qcm
      WHERE id = ?2 AND user_id = ?1
  )
ORDER BY position ASC
`

type GetQCMQuestionsIDsParams struct {
	UserID int64
	QcmID  int64
}

func (q *Queries) GetQCMQuestionsIDs(ctx context.Context, arg GetQCMQuestionsIDsParams) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, getQCMQuestionsIDs, arg.UserID, arg.QcmID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var question_id int64
		if err := rows.Scan(&question_id); err != nil {
			return nil, err
		}
		items = append(items, question_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getQuestionContentByQCMQuestionID = `-- name: GetQuestionContentByQCMQuestionID :one
SELECT
    questions.content
FROM questions
JOIN qcm_questions
    ON questions.id = qcm_questions.question_id
WHERE qcm_questions.user_id = ?1
  AND questions.user_id = ?1
  AND qcm_questions.id = ?2
  AND qcm_questions.qcm_id = ?3
  AND EXISTS (
      SELECT 1 FROM qcm
      WHERE id = ?3 AND user_id = ?1
  )
`

type GetQuestionContentByQCMQuestionIDParams struct {
	UserID        int64
	QcmQuestionID int64
	QcmID         int64
}

func (q *Queries) GetQuestionContentByQCMQuestionID(ctx context.Context, arg GetQuestionContentByQCMQuestionIDParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getQuestionContentByQCMQuestionID, arg.UserID, arg.QcmQuestionID, arg.QcmID)
	var content string
	err := row.Scan(&content)
	return content, err
}

const moveQCMQuestionPositionsToTemporaryRange = `-- name: MoveQCMQuestionPositionsToTemporaryRange :execrows
UPDATE qcm_questions
SET position = qcm_questions.position + ?1
WHERE qcm_questions.qcm_id = ?2
  AND qcm_questions.user_id = ?3
  AND qcm_questions.position > ?4
  AND EXISTS (
      SELECT 1 FROM qcm q
      WHERE q.id = ?2 AND q.user_id = ?3
  )
`

type MoveQCMQuestionPositionsToTemporaryRangeParams struct {
	MaxPosition     int64
	QcmID           int64
	UserID          int64
	DeletedPosition int64
}

func (q *Queries) MoveQCMQuestionPositionsToTemporaryRange(ctx context.Context, arg MoveQCMQuestionPositionsToTemporaryRangeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, moveQCMQuestionPositionsToTemporaryRange,
		arg.MaxPosition,
		arg.QcmID,
		arg.UserID,
		arg.DeletedPosition,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
