// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: qcmquestion.sql

package db

import (
	"context"
)

const getAllQuestionsByQCMID = `-- name: GetAllQuestionsByQCMID :many
SELECT
    questions.id         AS question_id,
    questions.content    AS question_content,
    qcm_questions.id     AS qcm_question_id
FROM questions
JOIN qcm_questions 
    ON qcm_questions.question_id = questions.id
WHERE questions.user_id = ?1
  AND qcm_questions.qcm_id = ?2
`

type GetAllQuestionsByQCMIDParams struct {
	UserID int64
	QcmID  int64
}

type GetAllQuestionsByQCMIDRow struct {
	QuestionID      int64
	QuestionContent string
	QcmQuestionID   int64
}

func (q *Queries) GetAllQuestionsByQCMID(ctx context.Context, arg GetAllQuestionsByQCMIDParams) ([]GetAllQuestionsByQCMIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllQuestionsByQCMID, arg.UserID, arg.QcmID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllQuestionsByQCMIDRow
	for rows.Next() {
		var i GetAllQuestionsByQCMIDRow
		if err := rows.Scan(&i.QuestionID, &i.QuestionContent, &i.QcmQuestionID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
