// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: qcmquestion.sql

package db

import (
	"context"
)

const createQCMQuestion = `-- name: CreateQCMQuestion :exec
INSERT INTO qcm_questions (qcm_id, question_id, user_id)
VALUES (?1, ?2, ?3)
`

type CreateQCMQuestionParams struct {
	QcmID      int64
	QuestionID int64
	UserID     int64
}

func (q *Queries) CreateQCMQuestion(ctx context.Context, arg CreateQCMQuestionParams) error {
	_, err := q.db.ExecContext(ctx, createQCMQuestion, arg.QcmID, arg.QuestionID, arg.UserID)
	return err
}

const deleteQCMQuestion = `-- name: DeleteQCMQuestion :exec
DELETE FROM
   qcm_questions 
WHERE
    id = ?1
    AND user_id = ?2
`

type DeleteQCMQuestionParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteQCMQuestion(ctx context.Context, arg DeleteQCMQuestionParams) error {
	_, err := q.db.ExecContext(ctx, deleteQCMQuestion, arg.ID, arg.UserID)
	return err
}

const getAllQuestionsByQCMID = `-- name: GetAllQuestionsByQCMID :many
SELECT
    questions.id         AS question_id,
    questions.content    AS question_content,
    qcm_questions.id     AS qcm_question_id
FROM questions
JOIN qcm_questions 
    ON qcm_questions.question_id = questions.id
WHERE questions.user_id = ?1
  AND qcm_questions.qcm_id = ?2
`

type GetAllQuestionsByQCMIDParams struct {
	UserID int64
	QcmID  int64
}

type GetAllQuestionsByQCMIDRow struct {
	QuestionID      int64
	QuestionContent string
	QcmQuestionID   int64
}

func (q *Queries) GetAllQuestionsByQCMID(ctx context.Context, arg GetAllQuestionsByQCMIDParams) ([]GetAllQuestionsByQCMIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllQuestionsByQCMID, arg.UserID, arg.QcmID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllQuestionsByQCMIDRow
	for rows.Next() {
		var i GetAllQuestionsByQCMIDRow
		if err := rows.Scan(&i.QuestionID, &i.QuestionContent, &i.QcmQuestionID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getQCMQuestionIDs = `-- name: GetQCMQuestionIDs :many
SELECT question_id
FROM qcm_questions
WHERE user_id = ?1
  AND qcm_id = ?2
ORDER BY question_id
`

type GetQCMQuestionIDsParams struct {
	UserID int64
	QcmID  int64
}

func (q *Queries) GetQCMQuestionIDs(ctx context.Context, arg GetQCMQuestionIDsParams) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, getQCMQuestionIDs, arg.UserID, arg.QcmID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var question_id int64
		if err := rows.Scan(&question_id); err != nil {
			return nil, err
		}
		items = append(items, question_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getQuestionContentByQCMQuestionID = `-- name: GetQuestionContentByQCMQuestionID :one
SELECT
    questions.content
FROM questions
JOIN qcm_questions
    ON questions.id = qcm_questions.question_id
WHERE qcm_questions.user_id = ?1
  AND qcm_questions.id = ?2
`

type GetQuestionContentByQCMQuestionIDParams struct {
	UserID        int64
	QcmQuestionID int64
}

func (q *Queries) GetQuestionContentByQCMQuestionID(ctx context.Context, arg GetQuestionContentByQCMQuestionIDParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getQuestionContentByQCMQuestionID, arg.UserID, arg.QcmQuestionID)
	var content string
	err := row.Scan(&content)
	return content, err
}
