// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: qcmSharing.sql

package db

import (
	"context"
)

const getOwnedQCMSharing = `-- name: GetOwnedQCMSharing :many
SELECT q.id, EXISTS(SELECT 1 FROM qcm_shares s WHERE s.qcm_id = q.id) AS shared,
COALESCE(o.source_author, '') AS source_author
FROM qcm q LEFT JOIN qcm_copy_origins o ON o.qcm_id = q.id
WHERE q.user_id = ?1
`

type GetOwnedQCMSharingRow struct {
	ID           int64
	Shared       bool
	SourceAuthor string
}

func (q *Queries) GetOwnedQCMSharing(ctx context.Context, userID int64) ([]GetOwnedQCMSharingRow, error) {
	rows, err := q.db.QueryContext(ctx, getOwnedQCMSharing, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOwnedQCMSharingRow
	for rows.Next() {
		var i GetOwnedQCMSharingRow
		if err := rows.Scan(&i.ID, &i.Shared, &i.SourceAuthor); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSharedQCM = `-- name: GetSharedQCM :one
SELECT q.id, q.name, q.user_id, u.username AS author,
(SELECT COUNT(*) FROM qcm_questions c WHERE c.qcm_id = q.id AND c.user_id = q.user_id) AS question_count
FROM qcm_shares sh JOIN qcm q ON q.id = sh.qcm_id
JOIN users u ON u.id = q.user_id
WHERE q.id = ?1
`

type GetSharedQCMRow struct {
	ID            int64
	Name          string
	UserID        int64
	Author        string
	QuestionCount int64
}

func (q *Queries) GetSharedQCM(ctx context.Context, qcmID int64) (GetSharedQCMRow, error) {
	row := q.db.QueryRowContext(ctx, getSharedQCM, qcmID)
	var i GetSharedQCMRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.UserID,
		&i.Author,
		&i.QuestionCount,
	)
	return i, err
}

const getSharedQCMClassifications = `-- name: GetSharedQCMClassifications :many
SELECT DISTINCT c.id AS qcm_id, s.name AS subject_name, y.name AS year_level_name
FROM qcm_shares sh JOIN qcm c ON c.id = sh.qcm_id
JOIN qcm_questions rel ON rel.qcm_id = c.id AND rel.user_id = c.user_id
JOIN questions q ON q.id = rel.question_id AND q.user_id = c.user_id
JOIN subjects s ON s.id = q.subject_id AND s.user_id = q.user_id
JOIN year_levels y ON y.id = q.year_level_id AND y.user_id = q.user_id
ORDER BY c.id, s.name, y.name
`

type GetSharedQCMClassificationsRow struct {
	QcmID         int64
	SubjectName   string
	YearLevelName string
}

func (q *Queries) GetSharedQCMClassifications(ctx context.Context) ([]GetSharedQCMClassificationsRow, error) {
	rows, err := q.db.QueryContext(ctx, getSharedQCMClassifications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSharedQCMClassificationsRow
	for rows.Next() {
		var i GetSharedQCMClassificationsRow
		if err := rows.Scan(&i.QcmID, &i.SubjectName, &i.YearLevelName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSharedQCMComposition = `-- name: GetSharedQCMComposition :many
SELECT rel.question_id, rel.position
FROM qcm_shares sh JOIN qcm c ON c.id = sh.qcm_id
JOIN qcm_questions rel ON rel.qcm_id = c.id AND rel.user_id = c.user_id
JOIN questions q ON q.id = rel.question_id AND q.user_id = c.user_id
WHERE c.id = ?1
ORDER BY rel.position
`

type GetSharedQCMCompositionRow struct {
	QuestionID int64
	Position   int64
}

func (q *Queries) GetSharedQCMComposition(ctx context.Context, qcmID int64) ([]GetSharedQCMCompositionRow, error) {
	rows, err := q.db.QueryContext(ctx, getSharedQCMComposition, qcmID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSharedQCMCompositionRow
	for rows.Next() {
		var i GetSharedQCMCompositionRow
		if err := rows.Scan(&i.QuestionID, &i.Position); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSharedQCMFamily = `-- name: GetSharedQCMFamily :one
SELECT q.id, q.user_id, q.content, q.instruction, u.username AS author,
s.name AS subject_name, y.name AS year_level_name, t.name AS theme_name,
k.name AS skill_name, d.name AS difficulty_name, p.point_value
FROM questions q
JOIN users u ON u.id = q.user_id
JOIN subjects s ON s.id = q.subject_id AND s.user_id = q.user_id
JOIN year_levels y ON y.id = q.year_level_id AND y.user_id = q.user_id
JOIN themes t ON t.id = q.theme_id AND t.user_id = q.user_id
JOIN skills k ON k.id = q.skill_id AND k.user_id = q.user_id
JOIN difficulties d ON d.id = q.difficulty_id AND d.user_id = q.user_id
JOIN points p ON p.id = q.point_id AND p.user_id = q.user_id
WHERE q.id = ?1 AND EXISTS (
    SELECT 1 FROM qcm_shares sh JOIN qcm c ON c.id = sh.qcm_id
    JOIN qcm_questions rel ON rel.qcm_id = c.id AND rel.user_id = c.user_id
    WHERE c.id = ?2 AND c.user_id = q.user_id AND rel.question_id = q.id
)
`

type GetSharedQCMFamilyParams struct {
	QuestionID int64
	QcmID      int64
}

type GetSharedQCMFamilyRow struct {
	ID             int64
	UserID         int64
	Content        string
	Instruction    string
	Author         string
	SubjectName    string
	YearLevelName  string
	ThemeName      string
	SkillName      string
	DifficultyName string
	PointValue     int64
}

func (q *Queries) GetSharedQCMFamily(ctx context.Context, arg GetSharedQCMFamilyParams) (GetSharedQCMFamilyRow, error) {
	row := q.db.QueryRowContext(ctx, getSharedQCMFamily, arg.QuestionID, arg.QcmID)
	var i GetSharedQCMFamilyRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Content,
		&i.Instruction,
		&i.Author,
		&i.SubjectName,
		&i.YearLevelName,
		&i.ThemeName,
		&i.SkillName,
		&i.DifficultyName,
		&i.PointValue,
	)
	return i, err
}

const getSharedQCMs = `-- name: GetSharedQCMs :many
SELECT q.id, q.name, q.user_id, u.username AS author,
(SELECT COUNT(*) FROM qcm_questions c WHERE c.qcm_id = q.id AND c.user_id = q.user_id) AS question_count
FROM qcm_shares sh JOIN qcm q ON q.id = sh.qcm_id
JOIN users u ON u.id = q.user_id
ORDER BY q.id DESC
`

type GetSharedQCMsRow struct {
	ID            int64
	Name          string
	UserID        int64
	Author        string
	QuestionCount int64
}

func (q *Queries) GetSharedQCMs(ctx context.Context) ([]GetSharedQCMsRow, error) {
	rows, err := q.db.QueryContext(ctx, getSharedQCMs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSharedQCMsRow
	for rows.Next() {
		var i GetSharedQCMsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.UserID,
			&i.Author,
			&i.QuestionCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const shareQCM = `-- name: ShareQCM :execrows
INSERT INTO qcm_shares(qcm_id)
SELECT id FROM qcm WHERE id = ?1 AND user_id = ?2
ON CONFLICT(qcm_id) DO NOTHING
`

type ShareQCMParams struct {
	QcmID  int64
	UserID int64
}

func (q *Queries) ShareQCM(ctx context.Context, arg ShareQCMParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, shareQCM, arg.QcmID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const unshareQCM = `-- name: UnshareQCM :execrows
DELETE FROM qcm_shares WHERE qcm_id = ?1
AND EXISTS (SELECT 1 FROM qcm WHERE id = ?1 AND user_id = ?2)
`

type UnshareQCMParams struct {
	QcmID  int64
	UserID int64
}

func (q *Queries) UnshareQCM(ctx context.Context, arg UnshareQCMParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, unshareQCM, arg.QcmID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
