// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: questionSharing.sql

package db

import (
	"context"
)

const getOwnedQuestionSharing = `-- name: GetOwnedQuestionSharing :many
SELECT q.id, EXISTS(SELECT 1 FROM question_shares s WHERE s.question_id = q.id) AS shared,
COALESCE(o.source_author, '') AS source_author
FROM questions q LEFT JOIN question_copy_origins o ON o.question_id = q.id
WHERE q.user_id = ?1
`

type GetOwnedQuestionSharingRow struct {
	ID           int64
	Shared       bool
	SourceAuthor string
}

func (q *Queries) GetOwnedQuestionSharing(ctx context.Context, userID int64) ([]GetOwnedQuestionSharingRow, error) {
	rows, err := q.db.QueryContext(ctx, getOwnedQuestionSharing, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOwnedQuestionSharingRow
	for rows.Next() {
		var i GetOwnedQuestionSharingRow
		if err := rows.Scan(&i.ID, &i.Shared, &i.SourceAuthor); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSharedQuestion = `-- name: GetSharedQuestion :one
SELECT q.id, q.user_id, q.content, q.instruction, u.username AS author,
s.name AS subject_name, y.name AS year_level_name, t.name AS theme_name,
k.name AS skill_name, d.name AS difficulty_name, p.point_value
FROM question_shares sh JOIN questions q ON q.id = sh.question_id
JOIN users u ON u.id = q.user_id
JOIN subjects s ON s.id = q.subject_id AND s.user_id = q.user_id
JOIN year_levels y ON y.id = q.year_level_id AND y.user_id = q.user_id
JOIN themes t ON t.id = q.theme_id AND t.user_id = q.user_id
JOIN skills k ON k.id = q.skill_id AND k.user_id = q.user_id
JOIN difficulties d ON d.id = q.difficulty_id AND d.user_id = q.user_id
JOIN points p ON p.id = q.point_id AND p.user_id = q.user_id
WHERE q.id = ?1
`

type GetSharedQuestionRow struct {
	ID             int64
	UserID         int64
	Content        string
	Instruction    string
	Author         string
	SubjectName    string
	YearLevelName  string
	ThemeName      string
	SkillName      string
	DifficultyName string
	PointValue     int64
}

func (q *Queries) GetSharedQuestion(ctx context.Context, questionID int64) (GetSharedQuestionRow, error) {
	row := q.db.QueryRowContext(ctx, getSharedQuestion, questionID)
	var i GetSharedQuestionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Content,
		&i.Instruction,
		&i.Author,
		&i.SubjectName,
		&i.YearLevelName,
		&i.ThemeName,
		&i.SkillName,
		&i.DifficultyName,
		&i.PointValue,
	)
	return i, err
}

const getSharedQuestions = `-- name: GetSharedQuestions :many
SELECT q.id, q.user_id, q.content, q.instruction, u.username AS author,
s.name AS subject_name, y.name AS year_level_name, t.name AS theme_name,
k.name AS skill_name, d.name AS difficulty_name, p.point_value
FROM question_shares sh JOIN questions q ON q.id = sh.question_id
JOIN users u ON u.id = q.user_id
JOIN subjects s ON s.id = q.subject_id AND s.user_id = q.user_id
JOIN year_levels y ON y.id = q.year_level_id AND y.user_id = q.user_id
JOIN themes t ON t.id = q.theme_id AND t.user_id = q.user_id
JOIN skills k ON k.id = q.skill_id AND k.user_id = q.user_id
JOIN difficulties d ON d.id = q.difficulty_id AND d.user_id = q.user_id
JOIN points p ON p.id = q.point_id AND p.user_id = q.user_id
ORDER BY q.id DESC
`

type GetSharedQuestionsRow struct {
	ID             int64
	UserID         int64
	Content        string
	Instruction    string
	Author         string
	SubjectName    string
	YearLevelName  string
	ThemeName      string
	SkillName      string
	DifficultyName string
	PointValue     int64
}

func (q *Queries) GetSharedQuestions(ctx context.Context) ([]GetSharedQuestionsRow, error) {
	rows, err := q.db.QueryContext(ctx, getSharedQuestions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSharedQuestionsRow
	for rows.Next() {
		var i GetSharedQuestionsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Content,
			&i.Instruction,
			&i.Author,
			&i.SubjectName,
			&i.YearLevelName,
			&i.ThemeName,
			&i.SkillName,
			&i.DifficultyName,
			&i.PointValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSharedVariants = `-- name: GetSharedVariants :many
SELECT a.id, a.question_id, a.content, a.user_id FROM alt_questions a
JOIN questions q ON q.id = a.question_id AND q.user_id = a.user_id
JOIN question_shares s ON s.question_id = q.id
ORDER BY a.question_id, a.id
`

func (q *Queries) GetSharedVariants(ctx context.Context) ([]AltQuestion, error) {
	rows, err := q.db.QueryContext(ctx, getSharedVariants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AltQuestion
	for rows.Next() {
		var i AltQuestion
		if err := rows.Scan(
			&i.ID,
			&i.QuestionID,
			&i.Content,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const shareQuestion = `-- name: ShareQuestion :execrows
INSERT INTO question_shares(question_id)
SELECT id FROM questions WHERE id = ?1 AND user_id = ?2
ON CONFLICT(question_id) DO NOTHING
`

type ShareQuestionParams struct {
	QuestionID int64
	UserID     int64
}

func (q *Queries) ShareQuestion(ctx context.Context, arg ShareQuestionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, shareQuestion, arg.QuestionID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const unshareQuestion = `-- name: UnshareQuestion :execrows
DELETE FROM question_shares WHERE question_id = ?1
AND EXISTS (SELECT 1 FROM questions WHERE id = ?1 AND user_id = ?2)
`

type UnshareQuestionParams struct {
	QuestionID int64
	UserID     int64
}

func (q *Queries) UnshareQuestion(ctx context.Context, arg UnshareQuestionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, unshareQuestion, arg.QuestionID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
