// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: questions.sql

package db

import (
	"context"
	"database/sql"
)

const createQuestion = `-- name: CreateQuestion :exec
INSERT INTO
    questions (
        subject_id,
        theme_id,
        year_level_id,
        skill_id,
        difficulty_id,
        point_id,
        content,
        user_id
    )
VALUES
    (
        ?1,
        ?2,
        ?3,
        ?4,
        ?5,
        ?6,
        ?7,
        ?8
    )
`

type CreateQuestionParams struct {
	SubjectID    int64
	ThemeID      int64
	YearLevelID  int64
	SkillID      int64
	DifficultyID int64
	PointID      int64
	Content      string
	UserID       int64
}

func (q *Queries) CreateQuestion(ctx context.Context, arg CreateQuestionParams) error {
	_, err := q.db.ExecContext(ctx, createQuestion,
		arg.SubjectID,
		arg.ThemeID,
		arg.YearLevelID,
		arg.SkillID,
		arg.DifficultyID,
		arg.PointID,
		arg.Content,
		arg.UserID,
	)
	return err
}

const deleteQuestion = `-- name: DeleteQuestion :exec
DELETE FROM
    questions
WHERE
    id = ?1
    AND user_id = ?2
`

type DeleteQuestionParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteQuestion(ctx context.Context, arg DeleteQuestionParams) error {
	_, err := q.db.ExecContext(ctx, deleteQuestion, arg.ID, arg.UserID)
	return err
}

const getAllQuestions = `-- name: GetAllQuestions :many
SELECT
    id, subject_id, theme_id, year_level_id, skill_id, difficulty_id, point_id, content, user_id
FROM
    questions
WHERE
    user_id = ?1
ORDER BY
    id DESC
`

func (q *Queries) GetAllQuestions(ctx context.Context, userID int64) ([]Question, error) {
	rows, err := q.db.QueryContext(ctx, getAllQuestions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Question
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.SubjectID,
			&i.ThemeID,
			&i.YearLevelID,
			&i.SkillID,
			&i.DifficultyID,
			&i.PointID,
			&i.Content,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAltQuestionIDsWithImage = `-- name: GetAltQuestionIDsWithImage :many
SELECT
    alt_questions.id
FROM
    alt_questions
    JOIN alt_images ON alt_questions.id = alt_images.alt_question_id
WHERE
    alt_questions.question_id = ?
`

func (q *Queries) GetAltQuestionIDsWithImage(ctx context.Context, questionID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, getAltQuestionIDsWithImage, questionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFilteredQuestions = `-- name: GetFilteredQuestions :many
SELECT 
    q.id,
    q.content,
    s.name  AS subject_name,
    t.name  AS theme_name,
    y.name  AS year_level_name,
    sk.name AS skill_name,
    d.name  AS difficulty_name,
    p.point_value AS point_value
FROM (
    SELECT id, subject_id, theme_id, year_level_id, skill_id, difficulty_id, point_id, content, user_id
    FROM questions
    WHERE questions.user_id = ?1
      AND (CAST(?2 AS INTEGER) IS NULL OR subject_id     = CAST(?2 AS INTEGER))
      AND (CAST(?3 AS INTEGER) IS NULL OR theme_id         = CAST(?3 AS INTEGER))
      AND (CAST(?4 AS INTEGER) IS NULL OR year_level_id = CAST(?4 AS INTEGER))
      AND (CAST(?5 AS INTEGER) IS NULL OR skill_id         = CAST(?5 AS INTEGER))
      AND (CAST(?6 AS INTEGER) IS NULL OR difficulty_id = CAST(?6 AS INTEGER))
      AND (CAST(?7 AS INTEGER) IS NULL OR point_id         = CAST(?7 AS INTEGER))
) q
JOIN subjects     s  ON q.subject_id     = s.id
JOIN themes       t  ON q.theme_id       = t.id
JOIN year_levels  y  ON q.year_level_id  = y.id
JOIN skills       sk ON q.skill_id       = sk.id
JOIN difficulties d  ON q.difficulty_id  = d.id
JOIN points       p  ON q.point_id       = p.id
ORDER BY q.id
`

type GetFilteredQuestionsParams struct {
	UserID       int64
	SubjectID    sql.NullInt64
	ThemeID      sql.NullInt64
	YearLevelID  sql.NullInt64
	SkillID      sql.NullInt64
	DifficultyID sql.NullInt64
	PointID      sql.NullInt64
}

type GetFilteredQuestionsRow struct {
	ID             int64
	Content        string
	SubjectName    string
	ThemeName      string
	YearLevelName  string
	SkillName      string
	DifficultyName string
	PointValue     int64
}

func (q *Queries) GetFilteredQuestions(ctx context.Context, arg GetFilteredQuestionsParams) ([]GetFilteredQuestionsRow, error) {
	rows, err := q.db.QueryContext(ctx, getFilteredQuestions,
		arg.UserID,
		arg.SubjectID,
		arg.ThemeID,
		arg.YearLevelID,
		arg.SkillID,
		arg.DifficultyID,
		arg.PointID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFilteredQuestionsRow
	for rows.Next() {
		var i GetFilteredQuestionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.SubjectName,
			&i.ThemeName,
			&i.YearLevelName,
			&i.SkillName,
			&i.DifficultyName,
			&i.PointValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getQuestionByID = `-- name: GetQuestionByID :one
SELECT
    id, subject_id, theme_id, year_level_id, skill_id, difficulty_id, point_id, content, user_id
FROM
    questions
WHERE
    id = ?1
    AND user_id = ?2
`

type GetQuestionByIDParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetQuestionByID(ctx context.Context, arg GetQuestionByIDParams) (Question, error) {
	row := q.db.QueryRowContext(ctx, getQuestionByID, arg.ID, arg.UserID)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.ThemeID,
		&i.YearLevelID,
		&i.SkillID,
		&i.DifficultyID,
		&i.PointID,
		&i.Content,
		&i.UserID,
	)
	return i, err
}

const getRandomQuestionByQuestionID = `-- name: GetRandomQuestionByQuestionID :one
WITH pool AS (
  SELECT
    q.id      AS item_id,
    q.content AS content,
    0         AS is_alt
  FROM questions q
  WHERE q.id = ?1

  UNION ALL

  SELECT
    a.id      AS item_id,
    a.content AS content,
    1         AS is_alt
  FROM alt_questions a
  WHERE a.question_id = ?1
)
SELECT item_id, content, is_alt
FROM pool
ORDER BY RANDOM()
LIMIT 1
`

type GetRandomQuestionByQuestionIDRow struct {
	ItemID  int64
	Content string
	IsAlt   int64
}

func (q *Queries) GetRandomQuestionByQuestionID(ctx context.Context, questionID int64) (GetRandomQuestionByQuestionIDRow, error) {
	row := q.db.QueryRowContext(ctx, getRandomQuestionByQuestionID, questionID)
	var i GetRandomQuestionByQuestionIDRow
	err := row.Scan(&i.ItemID, &i.Content, &i.IsAlt)
	return i, err
}

const getTagsByQuestionID = `-- name: GetTagsByQuestionID :one
SELECT
    s.id AS subject_id,
    s.name AS subject_name,

    t.id AS theme_id,
    t.name AS theme_name,

    y.id AS year_level_id,
    y.name AS year_level_name,

    sk.id AS skill_id,
    sk.name AS skill_name,

    d.id AS difficulty_id,
    d.name AS difficulty_name,

    p.id AS point_id,
    p.point_value AS point_value
FROM questions q
JOIN subjects s ON q.subject_id = s.id
JOIN themes t ON q.theme_id = t.id
JOIN year_levels y ON q.year_level_id = y.id
JOIN skills sk ON q.skill_id = sk.id
JOIN difficulties d ON q.difficulty_id = d.id
JOIN points p ON q.point_id = p.id
WHERE q.id = ?1 AND q.user_id = ?2
`

type GetTagsByQuestionIDParams struct {
	QuestionID int64
	UserID     int64
}

type GetTagsByQuestionIDRow struct {
	SubjectID      int64
	SubjectName    string
	ThemeID        int64
	ThemeName      string
	YearLevelID    int64
	YearLevelName  string
	SkillID        int64
	SkillName      string
	DifficultyID   int64
	DifficultyName string
	PointID        int64
	PointValue     int64
}

func (q *Queries) GetTagsByQuestionID(ctx context.Context, arg GetTagsByQuestionIDParams) (GetTagsByQuestionIDRow, error) {
	row := q.db.QueryRowContext(ctx, getTagsByQuestionID, arg.QuestionID, arg.UserID)
	var i GetTagsByQuestionIDRow
	err := row.Scan(
		&i.SubjectID,
		&i.SubjectName,
		&i.ThemeID,
		&i.ThemeName,
		&i.YearLevelID,
		&i.YearLevelName,
		&i.SkillID,
		&i.SkillName,
		&i.DifficultyID,
		&i.DifficultyName,
		&i.PointID,
		&i.PointValue,
	)
	return i, err
}

const updateQuestion = `-- name: UpdateQuestion :exec
UPDATE
    questions
SET
    subject_id = ?1,
    theme_id = ?2,
    year_level_id = ?3,
    skill_id = ?4,
    difficulty_id = ?5,
    point_id = ?6,
    content = ?7
WHERE
    id = ?8
    AND user_id = ?9
`

type UpdateQuestionParams struct {
	SubjectID    int64
	ThemeID      int64
	YearLevelID  int64
	SkillID      int64
	DifficultyID int64
	PointID      int64
	Content      string
	ID           int64
	UserID       int64
}

func (q *Queries) UpdateQuestion(ctx context.Context, arg UpdateQuestionParams) error {
	_, err := q.db.ExecContext(ctx, updateQuestion,
		arg.SubjectID,
		arg.ThemeID,
		arg.YearLevelID,
		arg.SkillID,
		arg.DifficultyID,
		arg.PointID,
		arg.Content,
		arg.ID,
		arg.UserID,
	)
	return err
}
