// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: questions.sql

package db

import (
	"context"
)

const createQuestion = `-- name: CreateQuestion :exec
INSERT INTO
    questions (
        subject_id,
        theme_id,
        year_level_id,
        skill_id,
        difficulty_id,
        point_id,
        content,
        user_id
    )
VALUES
    (
        ?1,
        ?2,
        ?3,
        ?4,
        ?5,
        ?6,
        ?7,
        ?8
    )
`

type CreateQuestionParams struct {
	SubjectID    int64
	ThemeID      int64
	YearLevelID  int64
	SkillID      int64
	DifficultyID int64
	PointID      int64
	Content      string
	UserID       int64
}

func (q *Queries) CreateQuestion(ctx context.Context, arg CreateQuestionParams) error {
	_, err := q.db.ExecContext(ctx, createQuestion,
		arg.SubjectID,
		arg.ThemeID,
		arg.YearLevelID,
		arg.SkillID,
		arg.DifficultyID,
		arg.PointID,
		arg.Content,
		arg.UserID,
	)
	return err
}

const getAllQuestions = `-- name: GetAllQuestions :many
SELECT
    id, subject_id, theme_id, year_level_id, skill_id, difficulty_id, point_id, content, user_id
FROM
    questions
WHERE
    user_id = ?1
ORDER BY
    id DESC
`

func (q *Queries) GetAllQuestions(ctx context.Context, userID int64) ([]Question, error) {
	rows, err := q.db.QueryContext(ctx, getAllQuestions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Question
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.SubjectID,
			&i.ThemeID,
			&i.YearLevelID,
			&i.SkillID,
			&i.DifficultyID,
			&i.PointID,
			&i.Content,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getQuestionByID = `-- name: GetQuestionByID :one
SELECT
    id, subject_id, theme_id, year_level_id, skill_id, difficulty_id, point_id, content, user_id
FROM
    questions
WHERE
    id = ?1
    AND user_id = ?2
`

type GetQuestionByIDParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetQuestionByID(ctx context.Context, arg GetQuestionByIDParams) (Question, error) {
	row := q.db.QueryRowContext(ctx, getQuestionByID, arg.ID, arg.UserID)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.ThemeID,
		&i.YearLevelID,
		&i.SkillID,
		&i.DifficultyID,
		&i.PointID,
		&i.Content,
		&i.UserID,
	)
	return i, err
}

const updateQuestion = `-- name: UpdateQuestion :exec
UPDATE
    questions
SET
    subject_id = ?1,
    theme_id = ?2,
    year_level_id = ?3,
    skill_id = ?4,
    difficulty_id = ?5,
    point_id = ?6,
    content = ?7
WHERE
    id = ?8
    AND user_id = ?9
`

type UpdateQuestionParams struct {
	SubjectID    int64
	ThemeID      int64
	YearLevelID  int64
	SkillID      int64
	DifficultyID int64
	PointID      int64
	Content      string
	ID           int64
	UserID       int64
}

func (q *Queries) UpdateQuestion(ctx context.Context, arg UpdateQuestionParams) error {
	_, err := q.db.ExecContext(ctx, updateQuestion,
		arg.SubjectID,
		arg.ThemeID,
		arg.YearLevelID,
		arg.SkillID,
		arg.DifficultyID,
		arg.PointID,
		arg.Content,
		arg.ID,
		arg.UserID,
	)
	return err
}
