// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: questions.sql

package db

import (
	"context"
)

const getAllQuestions = `-- name: GetAllQuestions :many
SELECT
    id, subject_id, theme_id, year_level_id, skill_id, difficulty_id, point_id, content, user_id
FROM
    questions
WHERE
    user_id = ?1
ORDER BY
    id DESC
`

func (q *Queries) GetAllQuestions(ctx context.Context, userID int64) ([]Question, error) {
	rows, err := q.db.QueryContext(ctx, getAllQuestions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Question
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.SubjectID,
			&i.ThemeID,
			&i.YearLevelID,
			&i.SkillID,
			&i.DifficultyID,
			&i.PointID,
			&i.Content,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
