// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: resetpassword.sql

package db

import (
	"context"
	"time"
)

const createResetPassword = `-- name: CreateResetPassword :exec
INSERT INTO password_resets (
    user_id, token, expires_at
) VALUES (
    ?1, ?2, ?3
)
`

type CreateResetPasswordParams struct {
	UserID    int64
	Token     string
	ExpiresAt time.Time
}

func (q *Queries) CreateResetPassword(ctx context.Context, arg CreateResetPasswordParams) error {
	_, err := q.db.ExecContext(ctx, createResetPassword, arg.UserID, arg.Token, arg.ExpiresAt)
	return err
}

const deleteExpiredResetTokens = `-- name: DeleteExpiredResetTokens :exec
DELETE FROM password_resets
WHERE expires_at <= CURRENT_TIMESTAMP OR used = TRUE
`

func (q *Queries) DeleteExpiredResetTokens(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredResetTokens)
	return err
}

const getResetPasswordByToken = `-- name: GetResetPasswordByToken :one
SELECT id, user_id, token, expires_at, used FROM password_resets
WHERE token = ?1 AND used = FALSE AND expires_at > CURRENT_TIMESTAMP
`

func (q *Queries) GetResetPasswordByToken(ctx context.Context, token string) (PasswordReset, error) {
	row := q.db.QueryRowContext(ctx, getResetPasswordByToken, token)
	var i PasswordReset
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.Used,
	)
	return i, err
}

const markResetPasswordTokenUsed = `-- name: MarkResetPasswordTokenUsed :exec
UPDATE password_resets
SET used = TRUE
WHERE token = ?1
`

func (q *Queries) MarkResetPasswordTokenUsed(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, markResetPasswordTokenUsed, token)
	return err
}
