// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: skills.sql

package db

import (
	"context"
)

const createSkill = `-- name: CreateSkill :exec
INSERT INTO
    skills (name, user_id)
VALUES
    (?1, ?2)
`

type CreateSkillParams struct {
	Name   string
	UserID int64
}

func (q *Queries) CreateSkill(ctx context.Context, arg CreateSkillParams) error {
	_, err := q.db.ExecContext(ctx, createSkill, arg.Name, arg.UserID)
	return err
}

const deleteSkill = `-- name: DeleteSkill :exec
DELETE FROM
    skills
WHERE
    id = ?1
    AND user_id = ?2
`

type DeleteSkillParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteSkill(ctx context.Context, arg DeleteSkillParams) error {
	_, err := q.db.ExecContext(ctx, deleteSkill, arg.ID, arg.UserID)
	return err
}

const getAllSkills = `-- name: GetAllSkills :many
SELECT
    id, name, user_id
FROM
    skills
WHERE
    user_id = ?1
ORDER BY
    name
`

func (q *Queries) GetAllSkills(ctx context.Context, userID int64) ([]Skill, error) {
	rows, err := q.db.QueryContext(ctx, getAllSkills, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Skill
	for rows.Next() {
		var i Skill
		if err := rows.Scan(&i.ID, &i.Name, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSkillNameByID = `-- name: GetSkillNameByID :one
SELECT
    name
FROM
    skills
WHERE
    id = ?1
    AND user_id = ?2
`

type GetSkillNameByIDParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetSkillNameByID(ctx context.Context, arg GetSkillNameByIDParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getSkillNameByID, arg.ID, arg.UserID)
	var name string
	err := row.Scan(&name)
	return name, err
}

const updateSkill = `-- name: UpdateSkill :exec
UPDATE
    skills
SET
    name = ?1
WHERE
    id = ?2
    AND user_id = ?3
`

type UpdateSkillParams struct {
	Name   string
	ID     int64
	UserID int64
}

func (q *Queries) UpdateSkill(ctx context.Context, arg UpdateSkillParams) error {
	_, err := q.db.ExecContext(ctx, updateSkill, arg.Name, arg.ID, arg.UserID)
	return err
}
