// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: studentExamContent.sql

package db

import (
	"context"
)

const createStudentExamContent = `-- name: CreateStudentExamContent :exec
INSERT INTO
    student_exam_content (student_exam_id, page_tot, content, user_id)
VALUES
    (?1, ?2, ?3, ?4)
`

type CreateStudentExamContentParams struct {
	StudentExamID int64
	PageTot       int64
	Content       string
	UserID        int64
}

func (q *Queries) CreateStudentExamContent(ctx context.Context, arg CreateStudentExamContentParams) error {
	_, err := q.db.ExecContext(ctx, createStudentExamContent,
		arg.StudentExamID,
		arg.PageTot,
		arg.Content,
		arg.UserID,
	)
	return err
}

const getStudentContentExam = `-- name: GetStudentContentExam :one
SELECT
    page_tot,
    content
FROM
    student_exam_content
WHERE
    student_exam_content.student_exam_id = ?1
    AND student_exam_content.user_id = ?2
    AND EXISTS (
        SELECT 1 FROM student_exam
        WHERE student_exam.id = student_exam_content.student_exam_id
          AND student_exam.user_id = ?2
    )
`

type GetStudentContentExamParams struct {
	StudentExamID int64
	UserID        int64
}

type GetStudentContentExamRow struct {
	PageTot int64
	Content string
}

func (q *Queries) GetStudentContentExam(ctx context.Context, arg GetStudentContentExamParams) (GetStudentContentExamRow, error) {
	row := q.db.QueryRowContext(ctx, getStudentContentExam, arg.StudentExamID, arg.UserID)
	var i GetStudentContentExamRow
	err := row.Scan(&i.PageTot, &i.Content)
	return i, err
}
