// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: students.sql

package db

import (
	"context"
)

const createStudent = `-- name: CreateStudent :exec
INSERT INTO
    students (first_name, last_name, user_id)
VALUES
    (?1, ?2, ?3)
`

type CreateStudentParams struct {
	FirstName string
	LastName  string
	UserID    int64
}

func (q *Queries) CreateStudent(ctx context.Context, arg CreateStudentParams) error {
	_, err := q.db.ExecContext(ctx, createStudent, arg.FirstName, arg.LastName, arg.UserID)
	return err
}

const deleteStudent = `-- name: DeleteStudent :exec
DELETE FROM
    students
WHERE
    id = ?1
    AND user_id = ?2
`

type DeleteStudentParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteStudent(ctx context.Context, arg DeleteStudentParams) error {
	_, err := q.db.ExecContext(ctx, deleteStudent, arg.ID, arg.UserID)
	return err
}

const getAllStudents = `-- name: GetAllStudents :many
SELECT
    id, first_name, last_name, user_id
FROM
    students
WHERE
    user_id = ?1
`

func (q *Queries) GetAllStudents(ctx context.Context, userID int64) ([]Student, error) {
	rows, err := q.db.QueryContext(ctx, getAllStudents, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Student
	for rows.Next() {
		var i Student
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllStudentsWithClassCodesNames = `-- name: GetAllStudentsWithClassCodesNames :many
SELECT
    students.id AS student_id,
    students.first_name,
    students.last_name,
    class_codes.id AS class_code_id,
    class_codes.name AS class_code_name
FROM
    students
JOIN
    student_class_codes ON students.id = student_class_codes.student_id
JOIN
    class_codes ON student_class_codes.class_code_id = class_codes.id
WHERE
    students.user_id = ?1
`

type GetAllStudentsWithClassCodesNamesRow struct {
	StudentID     int64
	FirstName     string
	LastName      string
	ClassCodeID   int64
	ClassCodeName string
}

func (q *Queries) GetAllStudentsWithClassCodesNames(ctx context.Context, userID int64) ([]GetAllStudentsWithClassCodesNamesRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllStudentsWithClassCodesNames, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllStudentsWithClassCodesNamesRow
	for rows.Next() {
		var i GetAllStudentsWithClassCodesNamesRow
		if err := rows.Scan(
			&i.StudentID,
			&i.FirstName,
			&i.LastName,
			&i.ClassCodeID,
			&i.ClassCodeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStudentByID = `-- name: GetStudentByID :one
SELECT
id, first_name, last_name, user_id
FROM
    students
WHERE
    id = ?1
    AND user_id = ?2
`

type GetStudentByIDParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetStudentByID(ctx context.Context, arg GetStudentByIDParams) (Student, error) {
	row := q.db.QueryRowContext(ctx, getStudentByID, arg.ID, arg.UserID)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.UserID,
	)
	return i, err
}

const getStudentIDByNameAndUserID = `-- name: GetStudentIDByNameAndUserID :one
SELECT
id
FROM
students
WHERE
first_name = ?1 AND last_name = ?2 AND user_id = ?3
`

type GetStudentIDByNameAndUserIDParams struct {
	FirstName string
	LastName  string
	UserID    int64
}

func (q *Queries) GetStudentIDByNameAndUserID(ctx context.Context, arg GetStudentIDByNameAndUserIDParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getStudentIDByNameAndUserID, arg.FirstName, arg.LastName, arg.UserID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const updateStudent = `-- name: UpdateStudent :exec
UPDATE
    students
SET
    first_name = ?1,
    last_name = ?2
WHERE
    id = ?3
    AND user_id = ?4
`

type UpdateStudentParams struct {
	FirstName string
	LastName  string
	ID        int64
	UserID    int64
}

func (q *Queries) UpdateStudent(ctx context.Context, arg UpdateStudentParams) error {
	_, err := q.db.ExecContext(ctx, updateStudent,
		arg.FirstName,
		arg.LastName,
		arg.ID,
		arg.UserID,
	)
	return err
}
