// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: student_class_codes.sql

package db

import (
	"context"
)

const createStudentWithClassCode = `-- name: CreateStudentWithClassCode :exec
INSERT INTO
student_class_codes (student_id, class_code_id, user_id)
VALUES
    (?1, ?2, ?3)
`

type CreateStudentWithClassCodeParams struct {
	StudentID   int64
	ClassCodeID int64
	UserID      int64
}

func (q *Queries) CreateStudentWithClassCode(ctx context.Context, arg CreateStudentWithClassCodeParams) error {
	_, err := q.db.ExecContext(ctx, createStudentWithClassCode, arg.StudentID, arg.ClassCodeID, arg.UserID)
	return err
}
