// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: studentExamPageContent.sql

package db

import (
	"context"
)

const createStudentExamPageContent = `-- name: CreateStudentExamPageContent :exec
INSERT INTO
    student_exam_page_content (student_exam_id, page, content, user_id)
VALUES
    (?1, ?2, ?3, ?4)
`

type CreateStudentExamPageContentParams struct {
	StudentExamID int64
	Page          int64
	Content       string
	UserID        int64
}

func (q *Queries) CreateStudentExamPageContent(ctx context.Context, arg CreateStudentExamPageContentParams) error {
	_, err := q.db.ExecContext(ctx, createStudentExamPageContent,
		arg.StudentExamID,
		arg.Page,
		arg.Content,
		arg.UserID,
	)
	return err
}

const getPageContent = `-- name: GetPageContent :one
SELECT
    content
FROM
    student_exam_page_content
WHERE
    student_exam_page_content.student_exam_id = ?1
    AND student_exam_page_content.page = ?2
    AND student_exam_page_content.user_id = ?3
    AND EXISTS (
        SELECT 1 FROM student_exam
        WHERE student_exam.id = student_exam_page_content.student_exam_id
          AND student_exam.user_id = ?3
    )
`

type GetPageContentParams struct {
	StudentExamID int64
	Page          int64
	UserID        int64
}

func (q *Queries) GetPageContent(ctx context.Context, arg GetPageContentParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getPageContent, arg.StudentExamID, arg.Page, arg.UserID)
	var content string
	err := row.Scan(&content)
	return content, err
}
