// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: studentExam.sql

package db

import (
	"context"
)

const createStudentExam = `-- name: CreateStudentExam :one
INSERT INTO
    student_exam (exam_generated_id, student_id, user_id)
VALUES
    (?1, ?2, ?3) RETURNING id
`

type CreateStudentExamParams struct {
	ExamGeneratedID int64
	StudentID       int64
	UserID          int64
}

func (q *Queries) CreateStudentExam(ctx context.Context, arg CreateStudentExamParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createStudentExam, arg.ExamGeneratedID, arg.StudentID, arg.UserID)
	var id int64
	err := row.Scan(&id)
	return id, err
}
