// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: student_class_codes.sql

package db

import (
	"context"
)

const countStudentsInClass = `-- name: CountStudentsInClass :one
SELECT COUNT(*) AS total
FROM student_class_codes
WHERE class_code_id = ?1
  AND user_id = ?2
`

type CountStudentsInClassParams struct {
	ClassCodeID int64
	UserID      int64
}

func (q *Queries) CountStudentsInClass(ctx context.Context, arg CountStudentsInClassParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countStudentsInClass, arg.ClassCodeID, arg.UserID)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createStudentWithClassCode = `-- name: CreateStudentWithClassCode :execrows
INSERT INTO
student_class_codes (student_id, class_code_id, user_id)
SELECT ?1, ?2, ?3
WHERE EXISTS (
    SELECT 1 FROM students
    WHERE id = ?1 AND user_id = ?3
)
AND EXISTS (
    SELECT 1 FROM class_codes
    WHERE id = ?2 AND user_id = ?3
)
`

type CreateStudentWithClassCodeParams struct {
	StudentID   int64
	ClassCodeID int64
	UserID      int64
}

func (q *Queries) CreateStudentWithClassCode(ctx context.Context, arg CreateStudentWithClassCodeParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createStudentWithClassCode, arg.StudentID, arg.ClassCodeID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteStudentClassCodeByStudentID = `-- name: DeleteStudentClassCodeByStudentID :execrows
DELETE FROM
student_class_codes
WHERE
student_class_codes.student_id = ?1
AND student_class_codes.class_code_id = ?2
AND student_class_codes.user_id = ?3
AND EXISTS (
    SELECT 1 FROM students
    WHERE id = ?1 AND user_id = ?3
)
AND EXISTS (
    SELECT 1 FROM class_codes
    WHERE id = ?2 AND user_id = ?3
)
AND EXISTS (
    SELECT 1
    FROM student_class_codes AS remaining_relation
    WHERE remaining_relation.student_id = ?1
      AND remaining_relation.user_id = ?3
      AND remaining_relation.class_code_id <> ?2
)
`

type DeleteStudentClassCodeByStudentIDParams struct {
	StudentID   int64
	ClassCodeID int64
	UserID      int64
}

func (q *Queries) DeleteStudentClassCodeByStudentID(ctx context.Context, arg DeleteStudentClassCodeByStudentIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteStudentClassCodeByStudentID, arg.StudentID, arg.ClassCodeID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAllClassCodesByStudentID = `-- name: GetAllClassCodesByStudentID :many
SELECT
class_code_id
FROM
student_class_codes
WHERE
student_id = ?1 AND user_id = ?2
`

type GetAllClassCodesByStudentIDParams struct {
	StudentID int64
	UserID    int64
}

func (q *Queries) GetAllClassCodesByStudentID(ctx context.Context, arg GetAllClassCodesByStudentIDParams) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, getAllClassCodesByStudentID, arg.StudentID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var class_code_id int64
		if err := rows.Scan(&class_code_id); err != nil {
			return nil, err
		}
		items = append(items, class_code_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllStudentsByClassCodeID = `-- name: GetAllStudentsByClassCodeID :many
SELECT students.id, students.first_name, students.last_name, students.user_id
FROM students
JOIN student_class_codes 
    ON students.id = student_class_codes.student_id
WHERE student_class_codes.class_code_id = ?1
  AND students.user_id = ?2
  AND student_class_codes.user_id = ?2
`

type GetAllStudentsByClassCodeIDParams struct {
	ClassCodeID int64
	UserID      int64
}

func (q *Queries) GetAllStudentsByClassCodeID(ctx context.Context, arg GetAllStudentsByClassCodeIDParams) ([]Student, error) {
	rows, err := q.db.QueryContext(ctx, getAllStudentsByClassCodeID, arg.ClassCodeID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Student
	for rows.Next() {
		var i Student
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClassCodesNotAssignedToStudent = `-- name: ListClassCodesNotAssignedToStudent :many
SELECT
    class_codes.id   AS "class_codes_id",
    class_codes.name AS "class_codes_name"
FROM class_codes AS class_codes
LEFT JOIN student_class_codes AS student_class_codes
    ON class_codes.id = student_class_codes.class_code_id
    AND student_class_codes.student_id = ?1
WHERE class_codes.user_id = ?2
  AND EXISTS (
      SELECT 1 FROM students
      WHERE id = ?1 AND user_id = ?2
  )
  AND student_class_codes.id IS NULL
`

type ListClassCodesNotAssignedToStudentParams struct {
	StudentID int64
	UserID    int64
}

type ListClassCodesNotAssignedToStudentRow struct {
	ClassCodesID   int64
	ClassCodesName string
}

func (q *Queries) ListClassCodesNotAssignedToStudent(ctx context.Context, arg ListClassCodesNotAssignedToStudentParams) ([]ListClassCodesNotAssignedToStudentRow, error) {
	rows, err := q.db.QueryContext(ctx, listClassCodesNotAssignedToStudent, arg.StudentID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClassCodesNotAssignedToStudentRow
	for rows.Next() {
		var i ListClassCodesNotAssignedToStudentRow
		if err := rows.Scan(&i.ClassCodesID, &i.ClassCodesName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
