// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: students.sql

package db

import (
	"context"
)

const createStudent = `-- name: CreateStudent :exec
INSERT INTO
    students (first_name, last_name, user_id)
VALUES
    (?1, ?2, ?3)
`

type CreateStudentParams struct {
	FirstName string
	LastName  string
	UserID    int64
}

func (q *Queries) CreateStudent(ctx context.Context, arg CreateStudentParams) error {
	_, err := q.db.ExecContext(ctx, createStudent, arg.FirstName, arg.LastName, arg.UserID)
	return err
}

const deleteStudent = `-- name: DeleteStudent :exec
DELETE FROM
    students
WHERE
    id = ?1
    AND user_id = ?2
`

type DeleteStudentParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteStudent(ctx context.Context, arg DeleteStudentParams) error {
	_, err := q.db.ExecContext(ctx, deleteStudent, arg.ID, arg.UserID)
	return err
}

const getAllStudents = `-- name: GetAllStudents :many
SELECT
    id, first_name, last_name, user_id
FROM
    students
WHERE
    user_id = ?1
`

func (q *Queries) GetAllStudents(ctx context.Context, userID int64) ([]Student, error) {
	rows, err := q.db.QueryContext(ctx, getAllStudents, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Student
	for rows.Next() {
		var i Student
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStudentByID = `-- name: GetStudentByID :one
SELECT
id, first_name, last_name, user_id
FROM
    students
WHERE
    id = ?1
    AND user_id = ?2
`

type GetStudentByIDParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetStudentByID(ctx context.Context, arg GetStudentByIDParams) (Student, error) {
	row := q.db.QueryRowContext(ctx, getStudentByID, arg.ID, arg.UserID)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.UserID,
	)
	return i, err
}

const updateStudent = `-- name: UpdateStudent :exec
UPDATE
    students
SET
    first_name = ?1,
    last_name = ?2
WHERE
    id = ?3
    AND user_id = ?4
`

type UpdateStudentParams struct {
	FirstName string
	LastName  string
	ID        int64
	UserID    int64
}

func (q *Queries) UpdateStudent(ctx context.Context, arg UpdateStudentParams) error {
	_, err := q.db.ExecContext(ctx, updateStudent,
		arg.FirstName,
		arg.LastName,
		arg.ID,
		arg.UserID,
	)
	return err
}
