// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: studentExamContent.sql

package db

import (
	"context"
)

const createStudentExamContent = `-- name: CreateStudentExamContent :exec
INSERT INTO
    student_exam_content (student_exam_id, page_tot, content, user_id)
VALUES
    (?1, ?2, ?3, ?4)
`

type CreateStudentExamContentParams struct {
	StudentExamID int64
	PageTot       int64
	Content       string
	UserID        int64
}

func (q *Queries) CreateStudentExamContent(ctx context.Context, arg CreateStudentExamContentParams) error {
	_, err := q.db.ExecContext(ctx, createStudentExamContent,
		arg.StudentExamID,
		arg.PageTot,
		arg.Content,
		arg.UserID,
	)
	return err
}
