// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: studentExamPageContent.sql

package db

import (
	"context"
)

const createStudentExamPageContent = `-- name: CreateStudentExamPageContent :exec
INSERT INTO
    student_exam_page_content (student_exam_id, page, content, user_id)
VALUES
    (?1, ?2, ?3, ?4)
`

type CreateStudentExamPageContentParams struct {
	StudentExamID int64
	Page          int64
	Content       string
	UserID        int64
}

func (q *Queries) CreateStudentExamPageContent(ctx context.Context, arg CreateStudentExamPageContentParams) error {
	_, err := q.db.ExecContext(ctx, createStudentExamPageContent,
		arg.StudentExamID,
		arg.Page,
		arg.Content,
		arg.UserID,
	)
	return err
}
