// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: subjects.sql

package db

import (
	"context"
)

const createSubject = `-- name: CreateSubject :exec
INSERT INTO
    subjects (name, user_id)
VALUES
    (?1, ?2)
`

type CreateSubjectParams struct {
	Name   string
	UserID int64
}

func (q *Queries) CreateSubject(ctx context.Context, arg CreateSubjectParams) error {
	_, err := q.db.ExecContext(ctx, createSubject, arg.Name, arg.UserID)
	return err
}

const deleteSubject = `-- name: DeleteSubject :exec
DELETE FROM
    subjects
WHERE
    id = ?1
    AND user_id = ?2
`

type DeleteSubjectParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteSubject(ctx context.Context, arg DeleteSubjectParams) error {
	_, err := q.db.ExecContext(ctx, deleteSubject, arg.ID, arg.UserID)
	return err
}

const getAllSubjects = `-- name: GetAllSubjects :many
SELECT
    id, name, user_id
FROM
    subjects
WHERE
    user_id = ?1
ORDER BY
    name
`

func (q *Queries) GetAllSubjects(ctx context.Context, userID int64) ([]Subject, error) {
	rows, err := q.db.QueryContext(ctx, getAllSubjects, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subject
	for rows.Next() {
		var i Subject
		if err := rows.Scan(&i.ID, &i.Name, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubjectNameByID = `-- name: GetSubjectNameByID :one
SELECT
    name
FROM
    subjects
WHERE
    id = ?1
    AND user_id = ?2
`

type GetSubjectNameByIDParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetSubjectNameByID(ctx context.Context, arg GetSubjectNameByIDParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getSubjectNameByID, arg.ID, arg.UserID)
	var name string
	err := row.Scan(&name)
	return name, err
}

const updateSubject = `-- name: UpdateSubject :exec
UPDATE
    subjects
SET
    name = ?1
WHERE
    id = ?2
    AND user_id = ?3
`

type UpdateSubjectParams struct {
	Name   string
	ID     int64
	UserID int64
}

func (q *Queries) UpdateSubject(ctx context.Context, arg UpdateSubjectParams) error {
	_, err := q.db.ExecContext(ctx, updateSubject, arg.Name, arg.ID, arg.UserID)
	return err
}
