// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: themes.sql

package db

import (
	"context"
)

const createTheme = `-- name: CreateTheme :exec
INSERT INTO
    themes (name, user_id)
VALUES
    (?1, ?2)
`

type CreateThemeParams struct {
	Name   string
	UserID int64
}

func (q *Queries) CreateTheme(ctx context.Context, arg CreateThemeParams) error {
	_, err := q.db.ExecContext(ctx, createTheme, arg.Name, arg.UserID)
	return err
}

const deleteTheme = `-- name: DeleteTheme :exec
DELETE FROM
    themes
WHERE
    id = ?1
    AND user_id = ?2
`

type DeleteThemeParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteTheme(ctx context.Context, arg DeleteThemeParams) error {
	_, err := q.db.ExecContext(ctx, deleteTheme, arg.ID, arg.UserID)
	return err
}

const getAllThemes = `-- name: GetAllThemes :many
SELECT
    id, name, user_id
FROM
    themes
WHERE
    user_id = ?1
ORDER BY
    name
`

func (q *Queries) GetAllThemes(ctx context.Context, userID int64) ([]Theme, error) {
	rows, err := q.db.QueryContext(ctx, getAllThemes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Theme
	for rows.Next() {
		var i Theme
		if err := rows.Scan(&i.ID, &i.Name, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getThemeNameByID = `-- name: GetThemeNameByID :one
SELECT
    name
FROM
    themes
WHERE
    id = ?1
    AND user_id = ?2
`

type GetThemeNameByIDParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetThemeNameByID(ctx context.Context, arg GetThemeNameByIDParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getThemeNameByID, arg.ID, arg.UserID)
	var name string
	err := row.Scan(&name)
	return name, err
}

const updateTheme = `-- name: UpdateTheme :exec
UPDATE
    themes
SET
    name = ?1
WHERE
    id = ?2
    AND user_id = ?3
`

type UpdateThemeParams struct {
	Name   string
	ID     int64
	UserID int64
}

func (q *Queries) UpdateTheme(ctx context.Context, arg UpdateThemeParams) error {
	_, err := q.db.ExecContext(ctx, updateTheme, arg.Name, arg.ID, arg.UserID)
	return err
}
