// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: training.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const getPublishedTrainingDeck = `-- name: GetPublishedTrainingDeck :one
SELECT id, title, public_token FROM training_decks WHERE public_token = ? AND state = 'published'
`

type GetPublishedTrainingDeckRow struct {
	ID          int64
	Title       string
	PublicToken string
}

func (q *Queries) GetPublishedTrainingDeck(ctx context.Context, publicToken string) (GetPublishedTrainingDeckRow, error) {
	row := q.db.QueryRowContext(ctx, getPublishedTrainingDeck, publicToken)
	var i GetPublishedTrainingDeckRow
	err := row.Scan(&i.ID, &i.Title, &i.PublicToken)
	return i, err
}

const getTrainingDeck = `-- name: GetTrainingDeck :one
SELECT id, user_id, generation_id, title, public_token, state, created_at FROM training_decks WHERE id = ? AND user_id = ?
`

type GetTrainingDeckParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetTrainingDeck(ctx context.Context, arg GetTrainingDeckParams) (TrainingDeck, error) {
	row := q.db.QueryRowContext(ctx, getTrainingDeck, arg.ID, arg.UserID)
	var i TrainingDeck
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GenerationID,
		&i.Title,
		&i.PublicToken,
		&i.State,
		&i.CreatedAt,
	)
	return i, err
}

const insertTrainingCard = `-- name: InsertTrainingCard :exec
INSERT INTO training_cards (deck_id,position,selected,source_question_id,source_variant_type,source_variant_id,content_json) VALUES (?,?,?,?,?,?,?)
`

type InsertTrainingCardParams struct {
	DeckID            int64
	Position          int64
	Selected          int64
	SourceQuestionID  sql.NullInt64
	SourceVariantType sql.NullString
	SourceVariantID   sql.NullInt64
	ContentJson       string
}

func (q *Queries) InsertTrainingCard(ctx context.Context, arg InsertTrainingCardParams) error {
	_, err := q.db.ExecContext(ctx, insertTrainingCard,
		arg.DeckID,
		arg.Position,
		arg.Selected,
		arg.SourceQuestionID,
		arg.SourceVariantType,
		arg.SourceVariantID,
		arg.ContentJson,
	)
	return err
}

const insertTrainingDeck = `-- name: InsertTrainingDeck :one
INSERT INTO training_decks (user_id,generation_id,title,public_token) VALUES (?,?,?,?) RETURNING id
`

type InsertTrainingDeckParams struct {
	UserID       int64
	GenerationID sql.NullInt64
	Title        string
	PublicToken  string
}

func (q *Queries) InsertTrainingDeck(ctx context.Context, arg InsertTrainingDeckParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertTrainingDeck,
		arg.UserID,
		arg.GenerationID,
		arg.Title,
		arg.PublicToken,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listTrainingCards = `-- name: ListTrainingCards :many
SELECT id, deck_id, position, selected, source_question_id, source_variant_type, source_variant_id, content_json, rendered_json FROM training_cards WHERE deck_id = ? ORDER BY position,id
`

func (q *Queries) ListTrainingCards(ctx context.Context, deckID int64) ([]TrainingCard, error) {
	rows, err := q.db.QueryContext(ctx, listTrainingCards, deckID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrainingCard
	for rows.Next() {
		var i TrainingCard
		if err := rows.Scan(
			&i.ID,
			&i.DeckID,
			&i.Position,
			&i.Selected,
			&i.SourceQuestionID,
			&i.SourceVariantType,
			&i.SourceVariantID,
			&i.ContentJson,
			&i.RenderedJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrainingDecks = `-- name: ListTrainingDecks :many
SELECT id, title, state, generation_id, public_token, created_at FROM training_decks WHERE user_id = ? ORDER BY created_at DESC, id DESC
`

type ListTrainingDecksRow struct {
	ID           int64
	Title        string
	State        string
	GenerationID sql.NullInt64
	PublicToken  string
	CreatedAt    time.Time
}

func (q *Queries) ListTrainingDecks(ctx context.Context, userID int64) ([]ListTrainingDecksRow, error) {
	rows, err := q.db.QueryContext(ctx, listTrainingDecks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTrainingDecksRow
	for rows.Next() {
		var i ListTrainingDecksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.State,
			&i.GenerationID,
			&i.PublicToken,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTrainingRenderedCard = `-- name: SetTrainingRenderedCard :execrows
UPDATE training_cards SET rendered_json = ? WHERE training_cards.id = ? AND training_cards.deck_id = ? AND EXISTS (SELECT 1 FROM training_decks WHERE training_decks.id = training_cards.deck_id AND training_decks.user_id = ? AND training_decks.state = 'draft')
`

type SetTrainingRenderedCardParams struct {
	RenderedJson sql.NullString
	ID           int64
	DeckID       int64
	UserID       int64
}

func (q *Queries) SetTrainingRenderedCard(ctx context.Context, arg SetTrainingRenderedCardParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setTrainingRenderedCard,
		arg.RenderedJson,
		arg.ID,
		arg.DeckID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setTrainingState = `-- name: SetTrainingState :execrows
UPDATE training_decks SET state = ? WHERE id = ? AND user_id = ? AND state = ?
`

type SetTrainingStateParams struct {
	State   string
	ID      int64
	UserID  int64
	State_2 string
}

func (q *Queries) SetTrainingState(ctx context.Context, arg SetTrainingStateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setTrainingState,
		arg.State,
		arg.ID,
		arg.UserID,
		arg.State_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateTrainingCard = `-- name: UpdateTrainingCard :execrows
UPDATE training_cards SET selected = ?, position = ? WHERE training_cards.id = ? AND training_cards.deck_id = ? AND EXISTS (SELECT 1 FROM training_decks WHERE training_decks.id = training_cards.deck_id AND training_decks.user_id = ? AND training_decks.state = 'draft')
`

type UpdateTrainingCardParams struct {
	Selected int64
	Position int64
	ID       int64
	DeckID   int64
	UserID   int64
}

func (q *Queries) UpdateTrainingCard(ctx context.Context, arg UpdateTrainingCardParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateTrainingCard,
		arg.Selected,
		arg.Position,
		arg.ID,
		arg.DeckID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateTrainingTitle = `-- name: UpdateTrainingTitle :execrows
UPDATE training_decks SET title = ? WHERE id = ? AND user_id = ? AND state = 'draft'
`

type UpdateTrainingTitleParams struct {
	Title  string
	ID     int64
	UserID int64
}

func (q *Queries) UpdateTrainingTitle(ctx context.Context, arg UpdateTrainingTitleParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateTrainingTitle, arg.Title, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
