// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: year_levels.sql

package db

import (
	"context"
)

const createYearLevel = `-- name: CreateYearLevel :exec
INSERT INTO
    year_levels (name, user_id)
VALUES
    (?1, ?2)
`

type CreateYearLevelParams struct {
	Name   string
	UserID int64
}

func (q *Queries) CreateYearLevel(ctx context.Context, arg CreateYearLevelParams) error {
	_, err := q.db.ExecContext(ctx, createYearLevel, arg.Name, arg.UserID)
	return err
}

const deleteYearLevel = `-- name: DeleteYearLevel :exec
DELETE FROM
    year_levels
WHERE
    id = ?1
    AND user_id = ?2
`

type DeleteYearLevelParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteYearLevel(ctx context.Context, arg DeleteYearLevelParams) error {
	_, err := q.db.ExecContext(ctx, deleteYearLevel, arg.ID, arg.UserID)
	return err
}

const getAllYearLevels = `-- name: GetAllYearLevels :many
SELECT
    id, name, user_id
FROM
    year_levels
WHERE
    user_id = ?1
ORDER BY
    name
`

func (q *Queries) GetAllYearLevels(ctx context.Context, userID int64) ([]YearLevel, error) {
	rows, err := q.db.QueryContext(ctx, getAllYearLevels, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []YearLevel
	for rows.Next() {
		var i YearLevel
		if err := rows.Scan(&i.ID, &i.Name, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateYearLevel = `-- name: UpdateYearLevel :exec
UPDATE
    year_levels
SET
    name = ?1
WHERE
    id = ?2
    AND user_id = ?3
`

type UpdateYearLevelParams struct {
	Name   string
	ID     int64
	UserID int64
}

func (q *Queries) UpdateYearLevel(ctx context.Context, arg UpdateYearLevelParams) error {
	_, err := q.db.ExecContext(ctx, updateYearLevel, arg.Name, arg.ID, arg.UserID)
	return err
}
