// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: years.sql

package db

import (
	"context"
)

const createYear = `-- name: CreateYear :exec
INSERT INTO
    years (name, user_id)
VALUES
    (?1, ?2)
`

type CreateYearParams struct {
	Name   string
	UserID int64
}

func (q *Queries) CreateYear(ctx context.Context, arg CreateYearParams) error {
	_, err := q.db.ExecContext(ctx, createYear, arg.Name, arg.UserID)
	return err
}

const deleteYear = `-- name: DeleteYear :exec
DELETE FROM
    years
WHERE
    id = ?1
    AND user_id = ?2
`

type DeleteYearParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) DeleteYear(ctx context.Context, arg DeleteYearParams) error {
	_, err := q.db.ExecContext(ctx, deleteYear, arg.ID, arg.UserID)
	return err
}

const getAllYears = `-- name: GetAllYears :many
SELECT
    id, name, user_id
FROM
    years
WHERE
    user_id = ?1
ORDER BY
    name
`

func (q *Queries) GetAllYears(ctx context.Context, userID int64) ([]Year, error) {
	rows, err := q.db.QueryContext(ctx, getAllYears, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Year
	for rows.Next() {
		var i Year
		if err := rows.Scan(&i.ID, &i.Name, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getYearNameByID = `-- name: GetYearNameByID :one
SELECT
    name
FROM
    years
WHERE
    id = ?1
    AND user_id = ?2
`

type GetYearNameByIDParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) GetYearNameByID(ctx context.Context, arg GetYearNameByIDParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getYearNameByID, arg.ID, arg.UserID)
	var name string
	err := row.Scan(&name)
	return name, err
}

const updateYear = `-- name: UpdateYear :exec
UPDATE
    years
SET
    name = ?1
WHERE
    id = ?2
    AND user_id = ?3
`

type UpdateYearParams struct {
	Name   string
	ID     int64
	UserID int64
}

func (q *Queries) UpdateYear(ctx context.Context, arg UpdateYearParams) error {
	_, err := q.db.ExecContext(ctx, updateYear, arg.Name, arg.ID, arg.UserID)
	return err
}
